//! Validates `front::mir_dispatch::extract_opcode_dispatch_arms_from_mir`
//! against the real lowered `execute_opcode_step` dispatcher.
//!
//! Depends on the gitignored `build/llbc/pyre-interpreter.ullbc`
//! artefact (regenerated by `scripts/extract-llbc.sh`). When it is
//! absent the test skips loudly rather than failing, so a fresh checkout
//! without the extraction step stays green; environments that build the
//! artefact (the `pyre/check.py` path) exercise it.

use majit_charon_reader::Llbc;
use majit_translate::OpcodeDispatchSelector;
use majit_translate::front::mir::build_semantic_program_from_llbc;
use majit_translate::front::mir_dispatch::extract_opcode_dispatch_arms_from_mir;

fn interpreter_ullbc() -> Option<Llbc> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../build/llbc/pyre-interpreter.ullbc"
    );
    if !std::path::Path::new(path).exists() {
        eprintln!("SKIP test_mir_dispatch: {path} not present (run scripts/extract-llbc.sh)");
        return None;
    }
    Some(Llbc::load(path).expect("load interpreter ullbc"))
}

#[test]
fn mir_dispatch_reconstructs_all_opcode_arms() {
    let Some(llbc) = interpreter_ullbc() else {
        return;
    };
    let program = build_semantic_program_from_llbc(&llbc).expect("build program");
    let arms = extract_opcode_dispatch_arms_from_mir(&program);

    // One arm per source match arm: 106 opcode arms + the `_ =>` default.
    assert_eq!(arms.len(), 107, "expected 107 dispatch arms");

    // Every arm carries a synthesized body graph (no `None` placeholders
    // arise for the real dispatcher — every shape is recognized, else
    // build_arm_body_graph panics).
    assert!(
        arms.iter().all(|a| a.body_graph.is_some()),
        "every arm must have a body graph"
    );

    // Exactly one wildcard (the default `_ => execute_unsupported`).
    let wildcards = arms
        .iter()
        .filter(|a| matches!(a.selector, OpcodeDispatchSelector::Wildcard))
        .count();
    assert_eq!(wildcards, 1, "exactly one wildcard/default arm");

    // The four `A | B …` source arms collapse to four Or selectors:
    // the meta group, the async-stub group, MatchMapping|MatchSequence,
    // and LoadFast|LoadFastBorrow.
    let or_arms = arms
        .iter()
        .filter(|a| matches!(a.selector, OpcodeDispatchSelector::Or(_)))
        .count();
    assert_eq!(or_arms, 4, "expected four Or-pattern arms");

    // Selector key set (Or cases canonicalized by sorting) spot-checks.
    let keys: std::collections::HashSet<String> = arms
        .iter()
        .map(|a| canonical_sorted_key(&a.selector))
        .collect();
    assert!(keys.contains("Instruction::PopTop"), "PopTop arm present");
    assert!(keys.contains("Instruction::LoadConst"), "LoadConst present");
    assert!(
        keys.contains("Instruction::ExitInitCheck"),
        "ExitInitCheck present as its own arm"
    );
    assert!(keys.contains("_"), "wildcard key present");
    // Async-stub Or group, sorted.
    assert!(
        keys.contains(
            "Instruction::CleanupThrow | Instruction::EndAsyncFor | Instruction::GetAiter | \
             Instruction::GetAnext | Instruction::GetAwaitable"
        ),
        "async-stub Or group present (sorted): got {keys:?}"
    );

    // No duplicate selectors (the canonical dispatch builder rejects
    // duplicates; the MIR extractor must not produce any).
    assert_eq!(
        keys.len(),
        arms.len(),
        "selectors must be unique across arms"
    );
}

/// Canonical key with `Or` cases sorted — the order-insensitive form used
/// for cross-checking against the syn extractor (within-Or source order
/// is not represented in MIR).
fn canonical_sorted_key(selector: &OpcodeDispatchSelector) -> String {
    match selector {
        OpcodeDispatchSelector::Or(cases) => {
            let mut parts: Vec<String> = cases.iter().map(canonical_sorted_key).collect();
            parts.sort();
            parts.join(" | ")
        }
        other => other.canonical_key(),
    }
}
