//! RPython parity module for `rpython/jit/metainterp/optimizeopt/autogenintrules.py`.
//!
//! PyPy generates this file from `ruleopt/generate.py`; it defines
//! `OptIntAutoGenerated`, then `intbounds.py` mixes it into `OptIntBounds` via
//! `objectmodel.import_from_mixin(autogenintrules.OptIntAutoGenerated)`. Rust
//! models that mixin as a trait implemented for `OptIntBounds`; the dispatcher
//! in `intbounds.rs` calls these trait methods after importing the trait.

use crate::optimizeopt::intbounds::OptIntBounds;
use crate::optimizeopt::intutils::IntBound;
use crate::optimizeopt::{OptContext, OptimizationResult};
use majit_ir::{Op, OpCode, operand::Operand};

/// autogenintrules.py:14-18 `_eq(box1, bound1, box2, bound2)` helper:
/// `if box1 is box2: return True` — pure object identity, which is
/// `Operand`'s `==` (`Rc::ptr_eq` on every variant, two separately-minted
/// equal Consts are NOT equal). NOT `same_box`, which value-compares Const
/// operands; the constant-bound equality fallback below already covers two
/// equal Const operands, so `_eq` matches `is` semantics. Used by the
/// `optimize_INT_*` bodies that resolve operands to their `_forwarded`
/// terminal via `resolve_box`.
fn autogen_eq_b(box1: &Operand, bound1: &IntBound, box2: &Operand, bound2: &IntBound) -> bool {
    if box1 == box2 {
        return true;
    }
    if bound1.is_constant()
        && bound2.is_constant()
        && bound1.get_constant_int() == bound2.get_constant_int()
    {
        return true;
    }
    false
}

/// autogenintrules.py:54-55 rewrite helper:
/// `newop = self.replace_op_with(op, opcode, args=[...]);
///  self.optimizer.send_extra_operation(newop); return`.
/// Builds a fresh `Op` that reuses the original `op.pos` (preserving
/// Box identity) and returns `OptimizationResult::Restart` so the
/// dispatcher re-runs the new op from `first_optimization`, letting
/// chained OptIntBounds rules (add_zero, int_is_zero, further reassoc)
/// fire on the rewritten op. RPython's `send_extra_operation(opt=None)`
/// (optimizer.py:567-589) is what the dispatcher's `Restart` arm models.
fn replace_with(original: &Op, opcode: OpCode, args: &[Operand]) -> OptimizationResult {
    let new_op = Op::new(opcode, args);
    new_op.pos.set(original.pos.get());
    OptimizationResult::Restart(new_op)
}

/// autogenintrules.py helper `as_operation(box, opnum)`: the producing
/// op of an operand already resolved to its terminal box
/// (`resolve_box`), returned iff its opcode matches, else None. The
/// `op in self._emittedoperations` gate (optimizer.py:369-377) lives in
/// `ctx.get_producing_op`.
fn as_operation_b(b: &Operand, opcode: OpCode, ctx: &mut OptContext) -> Option<Op> {
    let op = ctx.get_producing_op(b)?;
    if op.opcode == opcode { Some(op) } else { None }
}
pub trait OptIntAutoGenerated {
    fn optimize_int_eq(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_ne(&mut self, op: &Op, ctx: &mut OptContext) -> OptimizationResult;
    fn optimize_int_add(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_sub(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_mul(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_and(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_or(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_xor(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_invert(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_neg(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_lshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_rshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_is_true(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_int_is_zero(&mut self, op: &Op, ctx: &mut OptContext) -> OptimizationResult;
    fn optimize_int_force_ge_zero(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
    fn optimize_uint_rshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult;
}

impl OptIntAutoGenerated for OptIntBounds {
    /// autogenintrules.py:1220-1320 optimize_INT_EQ — rules:
    /// eq_different_knownbits / eq_same / eq_one / eq_zero / eq_sub_eq.
    fn optimize_int_eq(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // eq_sub_eq: int_eq(int_sub(x, int_eq(x, a)), a) => 0 (4 forms)
        if let Some(arg0_sub) = as_operation_b(&arg0, OpCode::IntSub, ctx) {
            let arg0_0 = self.resolve_box(&arg0_sub.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_sub.arg(1), ctx);
            let b_arg0_0 = self.getintbound_b(&arg0_0, ctx);
            if let Some(inner_eq) = as_operation_b(&arg0_1, OpCode::IntEq, ctx) {
                let inner_0 = self.resolve_box(&inner_eq.arg(0), ctx);
                let inner_1 = self.resolve_box(&inner_eq.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // eq_sub_eq: int_eq(int_sub(x, int_eq(x, a)), a) => 0
                if autogen_eq_b(&inner_0, &b_inner_0, &arg0_0, &b_arg0_0)
                    && autogen_eq_b(&arg1, &b1, &inner_1, &b_inner_1)
                {
                    self.make_constant_int(op, 0, ctx);
                    return OptimizationResult::Remove;
                }
                // eq_sub_eq: int_eq(int_sub(x, int_eq(a, x)), a) => 0
                if autogen_eq_b(&inner_1, &b_inner_1, &arg0_0, &b_arg0_0)
                    && autogen_eq_b(&arg1, &b1, &inner_0, &b_inner_0)
                {
                    self.make_constant_int(op, 0, ctx);
                    return OptimizationResult::Remove;
                }
            }
        }
        if let Some(arg1_sub) = as_operation_b(&arg1, OpCode::IntSub, ctx) {
            let arg1_0 = self.resolve_box(&arg1_sub.arg(0), ctx);
            let arg1_1 = self.resolve_box(&arg1_sub.arg(1), ctx);
            let b_arg1_0 = self.getintbound_b(&arg1_0, ctx);
            if let Some(inner_eq) = as_operation_b(&arg1_1, OpCode::IntEq, ctx) {
                let inner_0 = self.resolve_box(&inner_eq.arg(0), ctx);
                let inner_1 = self.resolve_box(&inner_eq.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // eq_sub_eq: int_eq(a, int_sub(x, int_eq(x, a))) => 0
                if autogen_eq_b(&inner_0, &b_inner_0, &arg1_0, &b_arg1_0)
                    && autogen_eq_b(&inner_1, &b_inner_1, &arg0, &b0)
                {
                    self.make_constant_int(op, 0, ctx);
                    return OptimizationResult::Remove;
                }
                // eq_sub_eq: int_eq(a, int_sub(x, int_eq(a, x))) => 0
                if autogen_eq_b(&inner_0, &b_inner_0, &arg0, &b0)
                    && autogen_eq_b(&inner_1, &b_inner_1, &arg1_0, &b_arg1_0)
                {
                    self.make_constant_int(op, 0, ctx);
                    return OptimizationResult::Remove;
                }
            }
        }
        // eq_same: int_eq(x, x) => 1
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            self.make_constant_int(op, 1, ctx);
            return OptimizationResult::Remove;
        }
        // eq_different_knownbits: int_eq(x, y) => 0
        if b0.known_ne(&b1) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // eq_different_knownbits: int_eq(y, x) => 0
        if b1.known_ne(&b0) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // eq_one: int_eq(1, x) => x  (when x is bool)
        if b0.is_constant() && b0.get_constant_int() == 1 && b1.is_bool() {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg1);
            return OptimizationResult::Remove;
        }
        // eq_one: int_eq(x, 1) => x  (when x is bool)
        if b1.is_constant() && b1.get_constant_int() == 1 && b0.is_bool() {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // eq_zero: int_eq(0, x) => int_is_zero(x)
        if b0.is_constant() && b0.get_constant_int() == 0 {
            return replace_with(op, OpCode::IntIsZero, &[arg1.clone()]);
        }
        // eq_zero: int_eq(x, 0) => int_is_zero(x)
        if b1.is_constant() && b1.get_constant_int() == 0 {
            return replace_with(op, OpCode::IntIsZero, &[arg0.clone()]);
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1324-1360 optimize_INT_NE — rules:
    /// ne_different_knownbits / ne_same / ne_zero.
    fn optimize_int_ne(&mut self, op: &Op, ctx: &mut OptContext) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // ne_same: int_ne(x, x) => 0
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // ne_different_knownbits: int_ne(x, y) => 1
        if b0.known_ne(&b1) {
            self.make_constant_int(op, 1, ctx);
            return OptimizationResult::Remove;
        }
        // ne_different_knownbits: int_ne(y, x) => 1
        if b1.known_ne(&b0) {
            self.make_constant_int(op, 1, ctx);
            return OptimizationResult::Remove;
        }
        // ne_zero: int_ne(0, x) => int_is_true(x)
        if b0.is_constant() && b0.get_constant_int() == 0 {
            return replace_with(op, OpCode::IntIsTrue, &[arg1.clone()]);
        }
        // ne_zero: int_ne(x, 0) => int_is_true(x)
        if b1.is_constant() && b1.get_constant_int() == 0 {
            return replace_with(op, OpCode::IntIsTrue, &[arg0.clone()]);
        }
        OptimizationResult::PassOn
    }

    // ── autogenintrules.py ports ──
    //
    // rpython/jit/metainterp/optimizeopt/autogenintrules.py is machine-
    // generated by ruleopt/generate.py and mixed into OptIntBounds via
    // `objectmodel.import_from_mixin(autogenintrules.OptIntAutoGenerated)`
    // at intbounds.py:806. Each optimize_* method below is a direct port
    // of the corresponding `def optimize_INT_*` block.

    /// autogenintrules.py:23-143 optimize_INT_ADD — rules:
    /// add_zero / add_reassoc_consts / add_sub_x_c_c / add_sub_c_x_c.
    fn optimize_int_add(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // add_zero: int_add(0, x) => x
        if b0.is_constant() && b0.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg1);
            return OptimizationResult::Remove;
        }
        // add_zero: int_add(x, 0) => x
        if b1.is_constant() && b1.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // autogenintrules.py:42-88 — outer const on arg0, inner producer on arg1.
        if b0.is_constant() {
            let c_outer = b0.get_constant_int();
            if let Some(arg1_add) = as_operation_b(&arg1, OpCode::IntAdd, ctx) {
                let inner_0 = self.resolve_box(&arg1_add.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg1_add.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // add_reassoc_consts: int_add(C2, int_add(C1, x)) => int_add(x, C1+C2)
                if b_inner_0.is_constant() {
                    let folded = c_outer.wrapping_add(b_inner_0.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAdd,
                        &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
                // add_reassoc_consts: int_add(C2, int_add(x, C1)) => int_add(x, C1+C2)
                if b_inner_1.is_constant() {
                    let folded = c_outer.wrapping_add(b_inner_1.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAdd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            } else if let Some(arg1_sub) = as_operation_b(&arg1, OpCode::IntSub, ctx) {
                let inner_0 = self.resolve_box(&arg1_sub.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg1_sub.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // add_sub_c_x_c: int_add(C2, int_sub(C1, x)) => int_sub(C1+C2, x)
                if b_inner_0.is_constant() {
                    let folded = c_outer.wrapping_add(b_inner_0.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntSub,
                        &[ctx.materialize_operand_at(const_ref), inner_1.clone()],
                    );
                }
                // add_sub_x_c_c: int_add(C2, int_sub(x, C1)) => int_add(x, C2-C1)
                if b_inner_1.is_constant() {
                    let folded = c_outer.wrapping_sub(b_inner_1.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAdd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        } else {
            // autogenintrules.py:89-142 — inner producer on arg0, outer const on arg1.
            if let Some(arg0_add) = as_operation_b(&arg0, OpCode::IntAdd, ctx) {
                let inner_0 = self.resolve_box(&arg0_add.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg0_add.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                if b1.is_constant() {
                    let c_outer = b1.get_constant_int();
                    // add_reassoc_consts: int_add(int_add(C1, x), C2) => int_add(x, C1+C2)
                    if b_inner_0.is_constant() {
                        let folded = b_inner_0.get_constant_int().wrapping_add(c_outer);
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntAdd,
                            &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                    // add_reassoc_consts: int_add(int_add(x, C1), C2) => int_add(x, C1+C2)
                    if b_inner_1.is_constant() {
                        let folded = b_inner_1.get_constant_int().wrapping_add(c_outer);
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntAdd,
                            &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            } else if let Some(arg0_sub) = as_operation_b(&arg0, OpCode::IntSub, ctx) {
                let inner_0 = self.resolve_box(&arg0_sub.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg0_sub.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                if b1.is_constant() {
                    let c_outer = b1.get_constant_int();
                    // add_sub_c_x_c: int_add(int_sub(C1, x), C2) => int_sub(C1+C2, x)
                    if b_inner_0.is_constant() {
                        let folded = b_inner_0.get_constant_int().wrapping_add(c_outer);
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntSub,
                            &[ctx.materialize_operand_at(const_ref), inner_1.clone()],
                        );
                    }
                    // add_sub_x_c_c: int_add(int_sub(x, C1), C2) => int_add(x, C2-C1)
                    if b_inner_1.is_constant() {
                        let folded = c_outer.wrapping_sub(b_inner_1.get_constant_int());
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntAdd,
                            &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:147-311 optimize_INT_SUB — rules:
    /// sub_zero / sub_from_zero / sub_x_x / sub_add_consts / sub_add /
    /// sub_add_neg / sub_sub_left_x_c_c / sub_sub_left_c_x_c /
    /// sub_xor_x_y_y / sub_or_x_y_y / sub_invert_one.
    fn optimize_int_sub(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // sub_x_x: int_sub(x, x) => 0
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // sub_add: int_sub(int_add(x, y), y) => x / int_sub(int_add(y, x), y) => x
        if let Some(arg0_int_add) = as_operation_b(&arg0, OpCode::IntAdd, ctx) {
            let arg0_0 = self.resolve_box(&arg0_int_add.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_int_add.arg(1), ctx);
            let b0_0 = self.getintbound_b(&arg0_0, ctx);
            let b0_1 = self.getintbound_b(&arg0_1, ctx);
            if autogen_eq_b(&arg1, &b1, &arg0_1, &b0_1) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_0);
                return OptimizationResult::Remove;
            }
            if autogen_eq_b(&arg1, &b1, &arg0_0, &b0_0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_1);
                return OptimizationResult::Remove;
            }
        } else if let Some(arg0_int_or) = as_operation_b(&arg0, OpCode::IntOr, ctx) {
            // sub_or_x_y_y: int_sub(int_or(x, y), y) => x  (when x & y == 0)
            let arg0_0 = self.resolve_box(&arg0_int_or.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_int_or.arg(1), ctx);
            let b0_0 = self.getintbound_b(&arg0_0, ctx);
            let b0_1 = self.getintbound_b(&arg0_1, ctx);
            if autogen_eq_b(&arg1, &b1, &arg0_1, &b0_1) && b0_0.and_bound(&b0_1).known_eq_const(0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_0);
                return OptimizationResult::Remove;
            }
            if autogen_eq_b(&arg1, &b1, &arg0_0, &b0_0) && b0_1.and_bound(&b0_0).known_eq_const(0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_1);
                return OptimizationResult::Remove;
            }
        } else if let Some(arg0_int_xor) = as_operation_b(&arg0, OpCode::IntXor, ctx) {
            // sub_xor_x_y_y: int_sub(int_xor(x, y), y) => x  (when x & y == 0)
            let arg0_0 = self.resolve_box(&arg0_int_xor.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_int_xor.arg(1), ctx);
            let b0_0 = self.getintbound_b(&arg0_0, ctx);
            let b0_1 = self.getintbound_b(&arg0_1, ctx);
            if autogen_eq_b(&arg1, &b1, &arg0_1, &b0_1) && b0_0.and_bound(&b0_1).known_eq_const(0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_0);
                return OptimizationResult::Remove;
            }
            if autogen_eq_b(&arg1, &b1, &arg0_0, &b0_0) && b0_1.and_bound(&b0_0).known_eq_const(0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0_1);
                return OptimizationResult::Remove;
            }
        }
        // sub_zero: int_sub(x, 0) => x
        if b1.is_constant() && b1.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // sub_from_zero: int_sub(0, x) => int_neg(x)
        if b0.is_constant() && b0.get_constant_int() == 0 {
            return replace_with(op, OpCode::IntNeg, &[arg1.clone()]);
        }
        if let Some(arg0_int_invert) = as_operation_b(&arg0, OpCode::IntInvert, ctx) {
            let arg0_0 = self.resolve_box(&arg0_int_invert.arg(0), ctx);
            // sub_invert_one: int_sub(int_invert(x), -1) => int_neg(x)
            if b1.is_constant() && b1.get_constant_int() == -1 {
                return replace_with(op, OpCode::IntNeg, &[arg0_0.clone()]);
            }
        } else if let Some(arg0_int_add) = as_operation_b(&arg0, OpCode::IntAdd, ctx) {
            let arg0_0 = self.resolve_box(&arg0_int_add.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_int_add.arg(1), ctx);
            let b0_0 = self.getintbound_b(&arg0_0, ctx);
            let b0_1 = self.getintbound_b(&arg0_1, ctx);
            if b1.is_constant() {
                let c_outer = b1.get_constant_int();
                // sub_add_consts: int_sub(int_add(C1, x), C2) => int_sub(x, C-C1)
                if b0_0.is_constant() {
                    let folded = c_outer.wrapping_sub(b0_0.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntSub,
                        &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
                // sub_add_consts: int_sub(int_add(x, C1), C2) => int_sub(x, C-C1)
                if b0_1.is_constant() {
                    let folded = c_outer.wrapping_sub(b0_1.get_constant_int());
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntSub,
                        &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        } else if let Some(arg0_int_sub) = as_operation_b(&arg0, OpCode::IntSub, ctx) {
            let arg0_0 = self.resolve_box(&arg0_int_sub.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_int_sub.arg(1), ctx);
            let b0_0 = self.getintbound_b(&arg0_0, ctx);
            let b0_1 = self.getintbound_b(&arg0_1, ctx);
            if b1.is_constant() {
                let c_outer = b1.get_constant_int();
                // sub_sub_left_c_x_c: int_sub(int_sub(C1, x), C2) => int_sub(C1-C2, x)
                if b0_0.is_constant() {
                    let folded = b0_0.get_constant_int().wrapping_sub(c_outer);
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntSub,
                        &[ctx.materialize_operand_at(const_ref), arg0_1.clone()],
                    );
                }
                // sub_sub_left_x_c_c: int_sub(int_sub(x, C1), C2) => int_sub(x, C1+C2)
                if b0_1.is_constant() {
                    let folded = b0_1.get_constant_int().wrapping_add(c_outer);
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntSub,
                        &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        }
        if let Some(arg1_int_add) = as_operation_b(&arg1, OpCode::IntAdd, ctx) {
            let arg1_0 = self.resolve_box(&arg1_int_add.arg(0), ctx);
            let arg1_1 = self.resolve_box(&arg1_int_add.arg(1), ctx);
            let b1_0 = self.getintbound_b(&arg1_0, ctx);
            let b1_1 = self.getintbound_b(&arg1_1, ctx);
            // sub_add_neg: int_sub(y, int_add(x, y)) => int_neg(x)
            if autogen_eq_b(&arg1_1, &b1_1, &arg0, &b0) {
                return replace_with(op, OpCode::IntNeg, &[arg1_0.clone()]);
            }
            // sub_add_neg: int_sub(y, int_add(y, x)) => int_neg(x)
            if autogen_eq_b(&arg1_0, &b1_0, &arg0, &b0) {
                return replace_with(op, OpCode::IntNeg, &[arg1_1.clone()]);
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:315-410 optimize_INT_MUL — rules:
    /// mul_zero / mul_one / mul_minus_one / mul_pow2_const / mul_lshift.
    fn optimize_int_mul(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // mul_zero: int_mul(0, x) => 0
        if b0.is_constant() && b0.get_constant_int() == 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // mul_zero: int_mul(x, 0) => 0
        if b1.is_constant() && b1.get_constant_int() == 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // mul_one: int_mul(1, x) => x
        if b0.is_constant() && b0.get_constant_int() == 1 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg1);
            return OptimizationResult::Remove;
        }
        // mul_one: int_mul(x, 1) => x
        if b1.is_constant() && b1.get_constant_int() == 1 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // Outer const on arg0: mul_minus_one / mul_pow2_const
        if b0.is_constant() {
            let c = b0.get_constant_int();
            // mul_minus_one: int_mul(-1, x) => int_neg(x)
            if c == -1 {
                return replace_with(op, OpCode::IntNeg, &[arg1.clone()]);
            }
            // mul_pow2_const: int_mul(C, x) where C > 0 && (C & (C-1)) == 0
            // => int_lshift(x, highest_bit(C))
            if c > 0 && (c & c.wrapping_sub(1)) == 0 {
                let shift = c.trailing_zeros() as i64;
                let shift_ref = ctx.make_constant_int(shift);
                return replace_with(
                    op,
                    OpCode::IntLshift,
                    &[arg1.clone(), ctx.materialize_operand_at(shift_ref)],
                );
            }
        } else if let Some(arg0_lshift) = as_operation_b(&arg0, OpCode::IntLshift, ctx) {
            // mul_lshift: int_mul(int_lshift(1, y), x) => int_lshift(x, y)
            let inner_0 = self.resolve_box(&arg0_lshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_lshift.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_0.is_constant()
                && b_inner_0.get_constant_int() == 1
                && b_inner_1.known_ge_const(0)
                && b_inner_1.known_le_const(64)
            {
                return replace_with(op, OpCode::IntLshift, &[arg1.clone(), inner_1.clone()]);
            }
        }
        // Outer const on arg1: mul_minus_one / mul_pow2_const
        if b1.is_constant() {
            let c = b1.get_constant_int();
            // mul_minus_one: int_mul(x, -1) => int_neg(x)
            if c == -1 {
                return replace_with(op, OpCode::IntNeg, &[arg0.clone()]);
            }
            // mul_pow2_const: int_mul(x, C) where C > 0 && pow2
            if c > 0 && (c & c.wrapping_sub(1)) == 0 {
                let shift = c.trailing_zeros() as i64;
                let shift_ref = ctx.make_constant_int(shift);
                return replace_with(
                    op,
                    OpCode::IntLshift,
                    &[arg0.clone(), ctx.materialize_operand_at(shift_ref)],
                );
            }
        } else if let Some(arg1_lshift) = as_operation_b(&arg1, OpCode::IntLshift, ctx) {
            // mul_lshift: int_mul(x, int_lshift(1, y)) => int_lshift(x, y)
            let inner_0 = self.resolve_box(&arg1_lshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg1_lshift.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_0.is_constant()
                && b_inner_0.get_constant_int() == 1
                && b_inner_1.known_ge_const(0)
                && b_inner_1.known_le_const(64)
            {
                return replace_with(op, OpCode::IntLshift, &[arg0.clone(), inner_1.clone()]);
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:414-581 optimize_INT_AND — rules:
    /// and_known_result / and_x_c_in_range / and_x_x / and_idempotent /
    /// and_reassoc_consts / and_absorb / and_or.
    fn optimize_int_and(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // and_known_result: int_and(a, b) bound is constant => ConstInt(C)
        let bound = b0.and_bound(&b1);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        let bound = b1.and_bound(&b0);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        // and_x_c_in_range: int_and(C, x) => x  (when 0 <= x.lower &&
        //                                      x.upper <= C & ~(C+1))
        if b0.is_constant() {
            let c = b0.get_constant_int();
            let mask = !((c as u64).wrapping_add(1)) as i64;
            if b1.lower >= 0 && b1.upper <= c & mask {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg1);
                return OptimizationResult::Remove;
            }
        }
        // and_x_c_in_range: int_and(x, C) => x
        if b1.is_constant() {
            let c = b1.get_constant_int();
            let mask = !((c as u64).wrapping_add(1)) as i64;
            if b0.lower >= 0 && b0.upper <= c & mask {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0);
                return OptimizationResult::Remove;
            }
        }
        // and_x_x: int_and(a, a) => a
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // and_idempotent: int_and(x, y) => x
        // when b1.tvalue | ~(b0.tvalue | b0.tmask) == all-ones
        if b1.tvalue | !(b0.tvalue | b0.tmask) == u64::MAX {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // and_idempotent: int_and(y, x) => x
        if b0.tvalue | !(b1.tvalue | b1.tmask) == u64::MAX {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg1);
            return OptimizationResult::Remove;
        }
        if b0.is_constant() {
            let c_outer = b0.get_constant_int();
            if let Some(arg1_and) = as_operation_b(&arg1, OpCode::IntAnd, ctx) {
                let inner_0 = self.resolve_box(&arg1_and.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg1_and.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // and_reassoc_consts: int_and(C2, int_and(C1, x)) => int_and(x, C1&C2)
                if b_inner_0.is_constant() {
                    let folded = b_inner_0.get_constant_int() & c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
                // and_reassoc_consts: int_and(C2, int_and(x, C1)) => int_and(x, C1&C2)
                if b_inner_1.is_constant() {
                    let folded = b_inner_1.get_constant_int() & c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        } else if let Some(arg0_and) = as_operation_b(&arg0, OpCode::IntAnd, ctx) {
            let inner_0 = self.resolve_box(&arg0_and.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_and.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_0.is_constant() {
                if b1.is_constant() {
                    // and_reassoc_consts: int_and(int_and(C1, x), C2) => int_and(x, C1&C2)
                    let folded = b_inner_0.get_constant_int() & b1.get_constant_int();
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
            if b_inner_1.is_constant() {
                if b1.is_constant() {
                    // and_reassoc_consts: int_and(int_and(x, C1), C2) => int_and(x, C1&C2)
                    let folded = b_inner_1.get_constant_int() & b1.get_constant_int();
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
            // and_absorb: int_and(int_and(a, b), a) => int_and(a, b)
            if autogen_eq_b(&arg1, &b1, &inner_0, &b_inner_0) {
                return replace_with(op, OpCode::IntAnd, &[inner_0.clone(), inner_1.clone()]);
            }
            // and_absorb: int_and(int_and(b, a), a) => int_and(a, b)
            if autogen_eq_b(&arg1, &b1, &inner_1, &b_inner_1) {
                return replace_with(op, OpCode::IntAnd, &[inner_1.clone(), inner_0.clone()]);
            }
        } else if let Some(arg0_or) = as_operation_b(&arg0, OpCode::IntOr, ctx) {
            let inner_0 = self.resolve_box(&arg0_or.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_or.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // and_or: int_and(int_or(x, y), z) => int_and(x, z)
            if b_inner_1.and_bound(&b1).known_eq_const(0) {
                return replace_with(op, OpCode::IntAnd, &[inner_0.clone(), arg1.clone()]);
            }
            // and_or: int_and(int_or(y, x), z) => int_and(x, z)
            if b_inner_0.and_bound(&b1).known_eq_const(0) {
                return replace_with(op, OpCode::IntAnd, &[inner_1.clone(), arg1.clone()]);
            }
        }
        // Symmetric arm: producer on arg1.
        if let Some(arg1_and) = as_operation_b(&arg1, OpCode::IntAnd, ctx) {
            let inner_0 = self.resolve_box(&arg1_and.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg1_and.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // and_absorb: int_and(a, int_and(a, b)) => int_and(a, b)
            if autogen_eq_b(&inner_0, &b_inner_0, &arg0, &b0) {
                return replace_with(op, OpCode::IntAnd, &[arg0.clone(), inner_1.clone()]);
            }
            // and_absorb: int_and(a, int_and(b, a)) => int_and(a, b)
            if autogen_eq_b(&inner_1, &b_inner_1, &arg0, &b0) {
                return replace_with(op, OpCode::IntAnd, &[arg0.clone(), inner_0.clone()]);
            }
        } else if let Some(arg1_or) = as_operation_b(&arg1, OpCode::IntOr, ctx) {
            let inner_0 = self.resolve_box(&arg1_or.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg1_or.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // and_or: int_and(z, int_or(x, y)) => int_and(x, z)
            if b_inner_1.and_bound(&b0).known_eq_const(0) {
                return replace_with(op, OpCode::IntAnd, &[inner_0.clone(), arg0.clone()]);
            }
            // and_or: int_and(z, int_or(y, x)) => int_and(x, z)
            if b_inner_0.and_bound(&b0).known_eq_const(0) {
                return replace_with(op, OpCode::IntAnd, &[inner_1.clone(), arg0.clone()]);
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:585-787 optimize_INT_OR — rules:
    /// or_known_result / or_x_x / or_idempotent / or_reassoc_consts /
    /// or_and_two_parts / or_absorb.
    ///
    /// Note on RPython parity: the auto-generated source includes
    /// pairs of `or_and_two_parts` arms with identical `_eq` predicates
    /// (autogenintrules.py:661/668, 677/684, 701/708, 717/724); the
    /// second of each pair is dead because the first always returns
    /// when its predicate holds. Preserved here to mirror upstream's
    /// auto-generated output line for line.
    fn optimize_int_or(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // or_known_result: int_or(a, b) bound is constant => ConstInt(C)
        let bound = b0.or_bound(&b1);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        let bound = b1.or_bound(&b0);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        // or_x_x: int_or(a, a) => a
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // or_idempotent: int_or(x, y) => x
        // when b0.tvalue | ~(b1.tvalue | b1.tmask) == all-ones
        if b0.tvalue | !(b1.tvalue | b1.tmask) == u64::MAX {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        // or_idempotent: int_or(y, x) => x
        if b1.tvalue | !(b0.tvalue | b0.tmask) == u64::MAX {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg1);
            return OptimizationResult::Remove;
        }
        if b0.is_constant() {
            let c_outer = b0.get_constant_int();
            if let Some(arg1_or) = as_operation_b(&arg1, OpCode::IntOr, ctx) {
                let inner_0 = self.resolve_box(&arg1_or.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg1_or.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // or_reassoc_consts: int_or(C2, int_or(C1, x)) => int_or(x, C1|C2)
                if b_inner_0.is_constant() {
                    let folded = b_inner_0.get_constant_int() | c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntOr,
                        &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
                // or_reassoc_consts: int_or(C2, int_or(x, C1)) => int_or(x, C1|C2)
                if b_inner_1.is_constant() {
                    let folded = b_inner_1.get_constant_int() | c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntOr,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        } else if let Some(arg0_and) = as_operation_b(&arg0, OpCode::IntAnd, ctx) {
            let arg0_0 = self.resolve_box(&arg0_and.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_and.arg(1), ctx);
            let b_arg0_0 = self.getintbound_b(&arg0_0, ctx);
            let b_arg0_1 = self.getintbound_b(&arg0_1, ctx);
            // or_and_two_parts shapes when outer = int_and(C, x):
            if b_arg0_0.is_constant() {
                let c_arg0_0 = b_arg0_0.get_constant_int();
                if let Some(arg1_and) = as_operation_b(&arg1, OpCode::IntAnd, ctx) {
                    let arg1_0 = self.resolve_box(&arg1_and.arg(0), ctx);
                    let arg1_1 = self.resolve_box(&arg1_and.arg(1), ctx);
                    let b_arg1_0 = self.getintbound_b(&arg1_0, ctx);
                    let b_arg1_1 = self.getintbound_b(&arg1_1, ctx);
                    if b_arg1_0.is_constant() {
                        // int_or(int_and(C1, x), int_and(C2, x)) => int_and(x, C1|C2)
                        if autogen_eq_b(&arg1_1, &b_arg1_1, &arg0_1, &b_arg0_1) {
                            let folded = c_arg0_0 | b_arg1_0.get_constant_int();
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                        // dead twin per autogenintrules.py:668-673
                        if autogen_eq_b(&arg1_1, &b_arg1_1, &arg0_1, &b_arg0_1) {
                            let folded = b_arg1_0.get_constant_int() | c_arg0_0;
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                    if b_arg1_1.is_constant() {
                        // int_or(int_and(C, x), int_and(x, C1)) => int_and(x, C|C1)
                        if autogen_eq_b(&arg1_0, &b_arg1_0, &arg0_1, &b_arg0_1) {
                            let folded = b_arg1_1.get_constant_int() | c_arg0_0;
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                        // dead twin per autogenintrules.py:684-689
                        if autogen_eq_b(&arg1_0, &b_arg1_0, &arg0_1, &b_arg0_1) {
                            let folded = c_arg0_0 | b_arg1_1.get_constant_int();
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                }
            }
            if b_arg0_1.is_constant() {
                let c_arg0_1 = b_arg0_1.get_constant_int();
                if let Some(arg1_and) = as_operation_b(&arg1, OpCode::IntAnd, ctx) {
                    let arg1_0 = self.resolve_box(&arg1_and.arg(0), ctx);
                    let arg1_1 = self.resolve_box(&arg1_and.arg(1), ctx);
                    let b_arg1_0 = self.getintbound_b(&arg1_0, ctx);
                    let b_arg1_1 = self.getintbound_b(&arg1_1, ctx);
                    if b_arg1_0.is_constant() {
                        // int_or(int_and(x, C1), int_and(C2, x)) => int_and(x, C)
                        if autogen_eq_b(&arg1_1, &b_arg1_1, &arg0_0, &b_arg0_0) {
                            let folded = c_arg0_1 | b_arg1_0.get_constant_int();
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                        // dead twin per autogenintrules.py:708-713
                        if autogen_eq_b(&arg1_1, &b_arg1_1, &arg0_0, &b_arg0_0) {
                            let folded = b_arg1_0.get_constant_int() | c_arg0_1;
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                    if b_arg1_1.is_constant() {
                        // int_or(int_and(x, C1), int_and(x, C2)) => int_and(x, C)
                        if autogen_eq_b(&arg1_0, &b_arg1_0, &arg0_0, &b_arg0_0) {
                            let folded = c_arg0_1 | b_arg1_1.get_constant_int();
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                        // dead twin per autogenintrules.py:724-729
                        if autogen_eq_b(&arg1_0, &b_arg1_0, &arg0_0, &b_arg0_0) {
                            let folded = b_arg1_1.get_constant_int() | c_arg0_1;
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                }
            }
        } else if let Some(arg0_or) = as_operation_b(&arg0, OpCode::IntOr, ctx) {
            let arg0_0 = self.resolve_box(&arg0_or.arg(0), ctx);
            let arg0_1 = self.resolve_box(&arg0_or.arg(1), ctx);
            let b_arg0_0 = self.getintbound_b(&arg0_0, ctx);
            let b_arg0_1 = self.getintbound_b(&arg0_1, ctx);
            if b_arg0_0.is_constant() && b1.is_constant() {
                // or_reassoc_consts: int_or(int_or(C1, x), C2) => int_or(x, C1|C2)
                let folded = b_arg0_0.get_constant_int() | b1.get_constant_int();
                let const_ref = ctx.make_constant_int(folded);
                return replace_with(
                    op,
                    OpCode::IntOr,
                    &[arg0_1.clone(), ctx.materialize_operand_at(const_ref)],
                );
            }
            if b_arg0_1.is_constant() && b1.is_constant() {
                // or_reassoc_consts: int_or(int_or(x, C1), C2) => int_or(x, C1|C2)
                let folded = b_arg0_1.get_constant_int() | b1.get_constant_int();
                let const_ref = ctx.make_constant_int(folded);
                return replace_with(
                    op,
                    OpCode::IntOr,
                    &[arg0_0.clone(), ctx.materialize_operand_at(const_ref)],
                );
            }
            // or_absorb: int_or(int_or(a, b), a) => int_or(a, b)
            if autogen_eq_b(&arg1, &b1, &arg0_0, &b_arg0_0) {
                return replace_with(op, OpCode::IntOr, &[arg0_0.clone(), arg0_1.clone()]);
            }
            // or_absorb: int_or(int_or(b, a), a) => int_or(a, b)
            if autogen_eq_b(&arg1, &b1, &arg0_1, &b_arg0_1) {
                return replace_with(op, OpCode::IntOr, &[arg0_1.clone(), arg0_0.clone()]);
            }
        }
        // Symmetric arm: producer on arg1.
        if let Some(arg1_or) = as_operation_b(&arg1, OpCode::IntOr, ctx) {
            let arg1_0 = self.resolve_box(&arg1_or.arg(0), ctx);
            let arg1_1 = self.resolve_box(&arg1_or.arg(1), ctx);
            let b_arg1_0 = self.getintbound_b(&arg1_0, ctx);
            let b_arg1_1 = self.getintbound_b(&arg1_1, ctx);
            // or_absorb: int_or(a, int_or(a, b)) => int_or(a, b)
            if autogen_eq_b(&arg1_0, &b_arg1_0, &arg0, &b0) {
                return replace_with(op, OpCode::IntOr, &[arg0.clone(), arg1_1.clone()]);
            }
            // or_absorb: int_or(a, int_or(b, a)) => int_or(a, b)
            if autogen_eq_b(&arg1_1, &b_arg1_1, &arg0, &b0) {
                return replace_with(op, OpCode::IntOr, &[arg0.clone(), arg1_0.clone()]);
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:791-942 optimize_INT_XOR — rules:
    /// xor_x_x / xor_reassoc_consts / xor_absorb / xor_zero /
    /// xor_minus_1 / xor_known_result / xor_is_not.
    fn optimize_int_xor(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // xor_known_result: int_xor(a, b) bound is constant => ConstInt(C)
        let bound = b0.xor_bound(&b1);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        let bound = b1.xor_bound(&b0);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        // xor_x_x: int_xor(a, a) => 0
        if autogen_eq_b(&arg1, &b1, &arg0, &b0) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // xor_zero: int_xor(0, a) => a   (else: producer-xor absorbs)
        if b0.is_constant() {
            if b0.get_constant_int() == 0 {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg1);
                return OptimizationResult::Remove;
            }
        } else if let Some(arg0_xor) = as_operation_b(&arg0, OpCode::IntXor, ctx) {
            let inner_0 = self.resolve_box(&arg0_xor.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_xor.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // xor_absorb: int_xor(int_xor(a, b), b) => a
            if autogen_eq_b(&arg1, &b1, &inner_1, &b_inner_1) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &inner_0);
                return OptimizationResult::Remove;
            }
            // xor_absorb: int_xor(int_xor(b, a), b) => a
            if autogen_eq_b(&arg1, &b1, &inner_0, &b_inner_0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &inner_1);
                return OptimizationResult::Remove;
            }
        }
        // xor_zero: int_xor(a, 0) => a   (else: producer-xor absorbs)
        if b1.is_constant() {
            if b1.get_constant_int() == 0 {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &arg0);
                return OptimizationResult::Remove;
            }
        } else if let Some(arg1_xor) = as_operation_b(&arg1, OpCode::IntXor, ctx) {
            let inner_0 = self.resolve_box(&arg1_xor.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg1_xor.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // xor_absorb: int_xor(b, int_xor(a, b)) => a
            if autogen_eq_b(&inner_1, &b_inner_1, &arg0, &b0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &inner_0);
                return OptimizationResult::Remove;
            }
            // xor_absorb: int_xor(b, int_xor(b, a)) => a
            if autogen_eq_b(&inner_0, &b_inner_0, &arg0, &b0) {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &inner_1);
                return OptimizationResult::Remove;
            }
        }
        // Constant-on-left arm (b_arg_0 constant): reassoc_consts/minus_1/is_not
        if b0.is_constant() {
            let c_outer = b0.get_constant_int();
            if let Some(arg1_xor) = as_operation_b(&arg1, OpCode::IntXor, ctx) {
                let inner_0 = self.resolve_box(&arg1_xor.arg(0), ctx);
                let inner_1 = self.resolve_box(&arg1_xor.arg(1), ctx);
                let b_inner_0 = self.getintbound_b(&inner_0, ctx);
                let b_inner_1 = self.getintbound_b(&inner_1, ctx);
                // xor_reassoc_consts: int_xor(C2, int_xor(C1, x)) => int_xor(x, C1^C2)
                if b_inner_0.is_constant() {
                    let folded = b_inner_0.get_constant_int() ^ c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntXor,
                        &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
                // xor_reassoc_consts: int_xor(C2, int_xor(x, C1)) => int_xor(x, C1^C2)
                if b_inner_1.is_constant() {
                    let folded = b_inner_1.get_constant_int() ^ c_outer;
                    let const_ref = ctx.make_constant_int(folded);
                    return replace_with(
                        op,
                        OpCode::IntXor,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
            // xor_minus_1: int_xor(-1, x) => int_invert(x)
            if c_outer == -1 {
                return replace_with(op, OpCode::IntInvert, &[arg1.clone()]);
            }
            // xor_is_not: int_xor(1, x) => int_is_zero(x)  (when x is bool)
            if c_outer == 1 && b1.is_bool() {
                return replace_with(op, OpCode::IntIsZero, &[arg1.clone()]);
            }
        } else if let Some(arg0_xor) = as_operation_b(&arg0, OpCode::IntXor, ctx) {
            let inner_0 = self.resolve_box(&arg0_xor.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_xor.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_0.is_constant() && b1.is_constant() {
                // xor_reassoc_consts: int_xor(int_xor(C1, x), C2) => int_xor(x, C1^C2)
                let folded = b_inner_0.get_constant_int() ^ b1.get_constant_int();
                let const_ref = ctx.make_constant_int(folded);
                return replace_with(
                    op,
                    OpCode::IntXor,
                    &[inner_1.clone(), ctx.materialize_operand_at(const_ref)],
                );
            }
            if b_inner_1.is_constant() && b1.is_constant() {
                // xor_reassoc_consts: int_xor(int_xor(x, C1), C2) => int_xor(x, C1^C2)
                let folded = b_inner_1.get_constant_int() ^ b1.get_constant_int();
                let const_ref = ctx.make_constant_int(folded);
                return replace_with(
                    op,
                    OpCode::IntXor,
                    &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                );
            }
        }
        // Constant-on-right arm (b_arg_1 constant): minus_1/is_not
        if b1.is_constant() {
            let c = b1.get_constant_int();
            // xor_minus_1: int_xor(x, -1) => int_invert(x)
            if c == -1 {
                return replace_with(op, OpCode::IntInvert, &[arg0.clone()]);
            }
            // xor_is_not: int_xor(x, 1) => int_is_zero(x)  (when x is bool)
            if c == 1 && b0.is_bool() {
                return replace_with(op, OpCode::IntIsZero, &[arg0.clone()]);
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1432-1443 optimize_INT_INVERT — rules: invert_invert.
    fn optimize_int_invert(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        // invert_invert: int_invert(int_invert(x)) => x
        if let Some(inner) = as_operation_b(&arg0, OpCode::IntInvert, ctx) {
            let inner_0 = self.resolve_box(&inner.arg(0), ctx);
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &inner_0);
            return OptimizationResult::Remove;
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1447-1458 optimize_INT_NEG — rules: neg_neg.
    fn optimize_int_neg(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        // neg_neg: int_neg(int_neg(x)) => x
        if let Some(inner) = as_operation_b(&arg0, OpCode::IntNeg, ctx) {
            let inner_0 = self.resolve_box(&inner.arg(0), ctx);
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &inner_0);
            return OptimizationResult::Remove;
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:946-1109 optimize_INT_LSHIFT — rules:
    /// lshift_zero_x / lshift_x_zero / lshift_rshift_c_c / lshift_and_rshift /
    /// lshift_urshift_c_c / lshift_and_urshift / lshift_lshift_c_c.
    /// LONG_BIT inlined as 64 (pyre is 64-bit only).
    fn optimize_int_lshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // lshift_zero_x: int_lshift(0, x) => 0
        if b0.is_constant() && b0.get_constant_int() == 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // lshift_x_zero: int_lshift(x, 0) => x
        if b1.is_constant() && b1.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        if let Some(arg0_and) = as_operation_b(&arg0, OpCode::IntAnd, ctx) {
            let inner_0 = self.resolve_box(&arg0_and.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_and.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_0.is_constant() {
                let c_arg0_0 = b_inner_0.get_constant_int();
                if let Some(rshift) = as_operation_b(&inner_1, OpCode::IntRshift, ctx) {
                    let r0 = self.resolve_box(&rshift.arg(0), ctx);
                    let r1 = self.resolve_box(&rshift.arg(1), ctx);
                    let b_r1 = self.getintbound_b(&r1, ctx);
                    if b_r1.is_constant() && b1.is_constant() {
                        let c_r1 = b_r1.get_constant_int();
                        let c_arg1 = b1.get_constant_int();
                        // lshift_and_rshift: int_lshift(int_and(C2, int_rshift(x, C1)), C1) => int_and(x, C)
                        if c_arg1 == c_r1 && (0..64).contains(&c_r1) {
                            let folded = c_arg0_0.wrapping_shl(c_r1 as u32);
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[r0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                } else if let Some(urshift) = as_operation_b(&inner_1, OpCode::UintRshift, ctx) {
                    let r0 = self.resolve_box(&urshift.arg(0), ctx);
                    let r1 = self.resolve_box(&urshift.arg(1), ctx);
                    let b_r1 = self.getintbound_b(&r1, ctx);
                    if b_r1.is_constant() && b1.is_constant() {
                        let c_r1 = b_r1.get_constant_int();
                        let c_arg1 = b1.get_constant_int();
                        // lshift_and_urshift: int_lshift(int_and(C2, uint_rshift(x, C1)), C1) => int_and(x, C)
                        if c_arg1 == c_r1 && (0..64).contains(&c_r1) {
                            let folded = c_arg0_0.wrapping_shl(c_r1 as u32);
                            let const_ref = ctx.make_constant_int(folded);
                            return replace_with(
                                op,
                                OpCode::IntAnd,
                                &[r0.clone(), ctx.materialize_operand_at(const_ref)],
                            );
                        }
                    }
                }
            } else if let Some(rshift) = as_operation_b(&inner_0, OpCode::IntRshift, ctx) {
                let r0 = self.resolve_box(&rshift.arg(0), ctx);
                let r1 = self.resolve_box(&rshift.arg(1), ctx);
                let b_r1 = self.getintbound_b(&r1, ctx);
                if b_r1.is_constant() && b_inner_1.is_constant() && b1.is_constant() {
                    let c_r1 = b_r1.get_constant_int();
                    let c_arg0_1 = b_inner_1.get_constant_int();
                    let c_arg1 = b1.get_constant_int();
                    // lshift_and_rshift: int_lshift(int_and(int_rshift(x, C1), C2), C1) => int_and(x, C)
                    if c_arg1 == c_r1 && (0..64).contains(&c_r1) {
                        let folded = c_arg0_1.wrapping_shl(c_r1 as u32);
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntAnd,
                            &[r0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            } else if let Some(urshift) = as_operation_b(&inner_0, OpCode::UintRshift, ctx) {
                let r0 = self.resolve_box(&urshift.arg(0), ctx);
                let r1 = self.resolve_box(&urshift.arg(1), ctx);
                let b_r1 = self.getintbound_b(&r1, ctx);
                if b_r1.is_constant() && b_inner_1.is_constant() && b1.is_constant() {
                    let c_r1 = b_r1.get_constant_int();
                    let c_arg0_1 = b_inner_1.get_constant_int();
                    let c_arg1 = b1.get_constant_int();
                    // lshift_and_urshift: int_lshift(int_and(uint_rshift(x, C1), C2), C1) => int_and(x, C)
                    if c_arg1 == c_r1 && (0..64).contains(&c_r1) {
                        let folded = c_arg0_1.wrapping_shl(c_r1 as u32);
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntAnd,
                            &[r0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            }
        } else if let Some(arg0_lshift) = as_operation_b(&arg0, OpCode::IntLshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_lshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_lshift.arg(1), ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_1.is_constant() && b1.is_constant() {
                let c1 = b_inner_1.get_constant_int();
                let c2 = b1.get_constant_int();
                // lshift_lshift_c_c: int_lshift(int_lshift(x, C1), C2) => int_lshift(x, C)
                if (0..64).contains(&c1) && (0..64).contains(&c2) {
                    let folded = c1.wrapping_add(c2);
                    if folded < 64 {
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntLshift,
                            &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            }
        } else if let Some(arg0_rshift) = as_operation_b(&arg0, OpCode::IntRshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_rshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_rshift.arg(1), ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_1.is_constant() && b1.is_constant() {
                let c1 = b_inner_1.get_constant_int();
                let c2 = b1.get_constant_int();
                // lshift_rshift_c_c: int_lshift(int_rshift(x, C1), C1) => int_and(x, -1 << C1)
                if c2 == c1 && (0..64).contains(&c1) {
                    let mask = (-1i64).wrapping_shl(c1 as u32);
                    let const_ref = ctx.make_constant_int(mask);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        } else if let Some(arg0_urshift) = as_operation_b(&arg0, OpCode::UintRshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_urshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_urshift.arg(1), ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_1.is_constant() && b1.is_constant() {
                let c1 = b_inner_1.get_constant_int();
                let c2 = b1.get_constant_int();
                // lshift_urshift_c_c: int_lshift(uint_rshift(x, C1), C1) => int_and(x, -1 << C1)
                if c2 == c1 && (0..64).contains(&c1) {
                    let mask = (-1i64).wrapping_shl(c1 as u32);
                    let const_ref = ctx.make_constant_int(mask);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1113-1169 optimize_INT_RSHIFT — rules:
    /// rshift_zero_x / rshift_x_zero / rshift_known_result / rshift_lshift /
    /// rshift_rshift_c_c. LONG_BIT inlined as 64.
    fn optimize_int_rshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // rshift_zero_x: int_rshift(0, x) => 0
        if b0.is_constant() && b0.get_constant_int() == 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // rshift_known_result: int_rshift(a, b) bound is constant => ConstInt(C)
        let bound = b0.rshift_bound(&b1);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        if let Some(arg0_lshift) = as_operation_b(&arg0, OpCode::IntLshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_lshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_lshift.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // rshift_lshift: int_rshift(int_lshift(x, y), y) => x
            if autogen_eq_b(&arg1, &b1, &inner_1, &b_inner_1)
                && b_inner_0.lshift_bound_cannot_overflow(&b_inner_1)
            {
                let b_old = Operand::from_bound_op(op_rc);
                ctx.make_equal_to(&b_old, &inner_0);
                return OptimizationResult::Remove;
            }
        }
        // rshift_x_zero: int_rshift(x, 0) => x
        if b1.is_constant() && b1.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        if let Some(arg0_rshift) = as_operation_b(&arg0, OpCode::IntRshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_rshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_rshift.arg(1), ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_1.is_constant() && b1.is_constant() {
                let c1 = b_inner_1.get_constant_int();
                let c2 = b1.get_constant_int();
                // rshift_rshift_c_c: int_rshift(int_rshift(x, C1), C2) => int_rshift(x, min(C1+C2, 63))
                if (0..64).contains(&c1) && (0..64).contains(&c2) {
                    let folded = c1.wrapping_add(c2).min(63);
                    if (0..64).contains(&folded) {
                        let const_ref = ctx.make_constant_int(folded);
                        return replace_with(
                            op,
                            OpCode::IntRshift,
                            &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                        );
                    }
                }
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1364-1399 optimize_INT_IS_TRUE — rules:
    /// is_true_bool / is_true_true / is_true_and_minint.
    fn optimize_int_is_true(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        // is_true_true: int_is_true(x) => 1
        // when bound excludes 0: lower > 0, or upper < 0, or any tvalue bit set.
        if b0.lower > 0 || b0.upper < 0 || b0.tvalue != 0 {
            self.make_constant_int(op, 1, ctx);
            return OptimizationResult::Remove;
        }
        // is_true_bool: int_is_true(x) => x  (when x is bool)
        if b0.is_bool() {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        if let Some(arg0_and) = as_operation_b(&arg0, OpCode::IntAnd, ctx) {
            let inner_0 = self.resolve_box(&arg0_and.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_and.arg(1), ctx);
            let b_inner_0 = self.getintbound_b(&inner_0, ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            // is_true_and_minint: int_is_true(int_and(MININT, x)) => int_lt(x, 0)
            if b_inner_0.is_constant() && b_inner_0.get_constant_int() == i64::MIN {
                let zero_ref = ctx.make_constant_int(0);
                return replace_with(
                    op,
                    OpCode::IntLt,
                    &[inner_1.clone(), ctx.materialize_operand_at(zero_ref)],
                );
            }
            // is_true_and_minint: int_is_true(int_and(x, MININT)) => int_lt(x, 0)
            if b_inner_1.is_constant() && b_inner_1.get_constant_int() == i64::MIN {
                let zero_ref = ctx.make_constant_int(0);
                return replace_with(
                    op,
                    OpCode::IntLt,
                    &[inner_0.clone(), ctx.materialize_operand_at(zero_ref)],
                );
            }
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1403-1411 optimize_INT_IS_ZERO — rules: is_zero_true.
    fn optimize_int_is_zero(&mut self, op: &Op, ctx: &mut OptContext) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let b0 = ctx.getintbound_handle(&arg0).borrow().clone();
        // is_zero_true: int_is_zero(x) => 0
        // when bound excludes 0: lower > 0, or upper < 0, or any tvalue bit set.
        if b0.lower > 0 || b0.upper < 0 || b0.tvalue != 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1415-1428 optimize_INT_FORCE_GE_ZERO — rules:
    /// force_ge_zero_pos / force_ge_zero_neg.
    fn optimize_int_force_ge_zero(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let b0 = ctx.getintbound_handle(&arg0).borrow().clone();
        // force_ge_zero_neg: int_force_ge_zero(x) => 0  (when x < 0)
        if b0.known_lt_const(0) {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // force_ge_zero_pos: int_force_ge_zero(x) => x  (when x >= 0)
        if b0.known_nonnegative() {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        OptimizationResult::PassOn
    }

    /// autogenintrules.py:1173-1216 optimize_UINT_RSHIFT — rules:
    /// urshift_zero_x / urshift_x_zero / urshift_known_result /
    /// urshift_lshift_x_c_c.
    fn optimize_uint_rshift(
        &mut self,
        op: &Op,
        op_rc: &majit_ir::OpRc,
        ctx: &mut OptContext,
    ) -> OptimizationResult {
        let arg0 = self.resolve_box(&op.arg(0), ctx);
        let arg1 = self.resolve_box(&op.arg(1), ctx);
        let b0 = self.getintbound_b(&arg0, ctx);
        let b1 = self.getintbound_b(&arg1, ctx);
        // urshift_zero_x: uint_rshift(0, x) => 0
        if b0.is_constant() && b0.get_constant_int() == 0 {
            self.make_constant_int(op, 0, ctx);
            return OptimizationResult::Remove;
        }
        // urshift_known_result: uint_rshift(a, b) bound is constant => ConstInt(C)
        let bound = b0.urshift_bound(&b1);
        if bound.is_constant() {
            self.make_constant_int(op, bound.get_constant_int(), ctx);
            return OptimizationResult::Remove;
        }
        // urshift_x_zero: uint_rshift(x, 0) => x
        if b1.is_constant() && b1.get_constant_int() == 0 {
            let b_old = Operand::from_bound_op(op_rc);
            ctx.make_equal_to(&b_old, &arg0);
            return OptimizationResult::Remove;
        }
        if let Some(arg0_lshift) = as_operation_b(&arg0, OpCode::IntLshift, ctx) {
            let inner_0 = self.resolve_box(&arg0_lshift.arg(0), ctx);
            let inner_1 = self.resolve_box(&arg0_lshift.arg(1), ctx);
            let b_inner_1 = self.getintbound_b(&inner_1, ctx);
            if b_inner_1.is_constant() && b1.is_constant() {
                let c1 = b_inner_1.get_constant_int();
                let c2 = b1.get_constant_int();
                // urshift_lshift_x_c_c: uint_rshift(int_lshift(x, C), C) => int_and(x, mask)
                // mask = intmask(r_uint(-1 << C) >> r_uint(C))
                if c2 == c1 && (0..64).contains(&c1) {
                    let mask = ((((-1i64) as u64) << c1) >> c1) as i64;
                    let const_ref = ctx.make_constant_int(mask);
                    return replace_with(
                        op,
                        OpCode::IntAnd,
                        &[inner_0.clone(), ctx.materialize_operand_at(const_ref)],
                    );
                }
            }
        }
        OptimizationResult::PassOn
    }
}
