//! RPython parity module for `rpython/jit/metainterp/optimizeopt/autogenintrules.py`.
//!
//! The generated integer rewrite rules are ported directly into
//! `intbounds::OptIntBounds`, matching PyPy's mixin import into `OptIntBounds`.

pub use super::intbounds::OptIntBounds as OptIntAutoGenerated;
