use majit_ir::Type;
use majit_metainterp::virtualizable::VirtualizableInfo;
use pyre_interpreter::pyframe::PyFrame;

/// Byte offset of `vable_token` in `PyFrame`.
pub const PYFRAME_VABLE_TOKEN_OFFSET: usize = std::mem::offset_of!(PyFrame, vable_token);

/// Byte offset of `last_instr` in `PyFrame`.
pub const PYFRAME_LAST_INSTR_OFFSET: usize = std::mem::offset_of!(PyFrame, last_instr);

/// Byte offset of `valuestackdepth` in `PyFrame`.
pub const PYFRAME_VALUESTACKDEPTH_OFFSET: usize = std::mem::offset_of!(PyFrame, valuestackdepth);

/// Byte offset of `locals_cells_stack_w` in `PyFrame`.
pub const PYFRAME_LOCALS_CELLS_STACK_OFFSET: usize =
    std::mem::offset_of!(PyFrame, locals_cells_stack_w);

/// Byte offset of `w_globals` in `PyFrame`.
pub const PYFRAME_W_GLOBALS_OFFSET: usize = std::mem::offset_of!(PyFrame, w_globals);

/// Byte offset of `pycode` in `PyFrame`.
pub const PYFRAME_PYCODE_OFFSET: usize = std::mem::offset_of!(PyFrame, pycode);

/// Byte offset of `debugdata` in `PyFrame`.
pub const PYFRAME_DEBUGDATA_OFFSET: usize = std::mem::offset_of!(PyFrame, debugdata);

/// Byte offset of `lastblock` in `PyFrame`.
pub const PYFRAME_LASTBLOCK_OFFSET: usize = std::mem::offset_of!(PyFrame, lastblock);

// Backward-compat aliases used by JIT descriptor helpers.
pub const PYFRAME_STACK_DEPTH_OFFSET: usize = PYFRAME_VALUESTACKDEPTH_OFFSET;
pub const PYFRAME_LOCALS_OFFSET: usize = PYFRAME_LOCALS_CELLS_STACK_OFFSET;

// Compile-time consistency check: frame_layout and pyframe offsets must match.
const _: () = {
    assert!(PYFRAME_VABLE_TOKEN_OFFSET == pyre_interpreter::pyframe::PYFRAME_VABLE_TOKEN_OFFSET);
    assert!(PYFRAME_LAST_INSTR_OFFSET == pyre_interpreter::pyframe::PYFRAME_LAST_INSTR_OFFSET);
    assert!(PYFRAME_PYCODE_OFFSET == pyre_interpreter::pyframe::PYFRAME_PYCODE_OFFSET);
    assert!(
        PYFRAME_VALUESTACKDEPTH_OFFSET == pyre_interpreter::pyframe::PYFRAME_VALUESTACKDEPTH_OFFSET
    );
    assert!(
        PYFRAME_LOCALS_CELLS_STACK_OFFSET
            == pyre_interpreter::pyframe::PYFRAME_LOCALS_CELLS_STACK_OFFSET
    );
    assert!(PYFRAME_DEBUGDATA_OFFSET == pyre_interpreter::pyframe::PYFRAME_DEBUGDATA_OFFSET);
    assert!(PYFRAME_LASTBLOCK_OFFSET == pyre_interpreter::pyframe::PYFRAME_LASTBLOCK_OFFSET);
    assert!(PYFRAME_W_GLOBALS_OFFSET == pyre_interpreter::pyframe::PYFRAME_W_GLOBALS_OFFSET);
};

/// Build the virtualizable layout description for `PyFrame`.
///
/// Delegates to `virtualizable_gen::build_virtualizable_info()` which is
/// auto-generated by the `virtualizable!` macro from the canonical field
/// declaration, and immediately attaches the host `PyFrame` SizeDescr
/// via `set_parent_descr` so every field descriptor produced by the
/// `VirtualizableInfo` carries `descr.py FieldDescr.parent_descr` —
/// required by `OptContext::ensure_ptr_info_arg0` (`optimizer.py:478`)
/// to dispatch GETFIELD/SETFIELD to `InstancePtrInfo` / `StructPtrInfo`.
/// virtualizable.py:45-46: clear_vable_ptr — C-ABI helper that writes
/// TOKEN_NONE (0) to the vable_token field of a PyFrame.
unsafe extern "C" fn pyre_clear_vable_token(obj_ptr: i64) {
    unsafe {
        let ptr = obj_ptr as *mut u8;
        if !ptr.is_null() {
            let token_ptr = ptr.add(PYFRAME_VABLE_TOKEN_OFFSET) as *mut u64;
            *token_ptr = 0;
        }
    }
}

pub fn build_pyframe_virtualizable_info() -> std::sync::Arc<VirtualizableInfo> {
    let mut info = crate::virtualizable_gen::build_virtualizable_info();
    // rpython/jit/metainterp/virtualizable.py:293-301 `clear_vable_ptr`
    // + `clear_vable_descr`. The descr must carry
    // EffectInfo.MOST_GENERAL + OopSpecIndex.JitForceVirtualizable
    // and mark the call CANNOT_RAISE — `VirtualizableInfo::make_clear
    // _vable_descr` is the single-source-of-truth factory that
    // constructs exactly that descriptor. Using
    // `make_call_descr(.., EffectInfo::default())` here would drop
    // the CANNOT_RAISE / OS_JIT_FORCE_VIRTUALIZABLE flags and cause
    // the optimizer to treat the call as a raising general call.
    //
    // Populate clear_vable BEFORE `finalize_arc`: finalize consumes self
    // and rebuilds descriptors inside `Arc::new_cyclic`, so any fields
    // set here survive into the returned Arc. After the Arc is formed
    // the vinfo is immutable through the shared handle.
    info.clear_vable_ptr = Some(pyre_clear_vable_token as *const () as usize);
    info.clear_vable_descr = Some(VirtualizableInfo::make_clear_vable_descr());
    info.finalize_arc(crate::state::pyframe_size_descr())
}

#[cfg(test)]
mod tests {
    use super::build_pyframe_virtualizable_info;

    #[test]
    fn pyframe_token_descr_parent_survives_vinfo_drop() {
        let info = build_pyframe_virtualizable_info();
        let token_descr = info.token_field_descr();
        drop(info);

        let parent = token_descr
            .as_field_descr()
            .and_then(|fd| fd.get_parent_descr());
        assert!(
            parent.is_some(),
            "PyFrame token field descr must keep a live parent SizeDescr \
             like GcCache.get_size_descr()"
        );
    }
}
