//! Auto-generated virtualizable infrastructure for `PyFrame`.
//!
//! Generated by `majit_macros::virtualizable!` from the canonical field
//! declaration. Provides layout-based JitState helpers, VirtualizableInfo
//! builder, field/array spec constants, and virtualizable hook helpers.

use crate::frame_layout::{
    PYFRAME_DEBUGDATA_OFFSET, PYFRAME_LAST_INSTR_OFFSET, PYFRAME_LASTBLOCK_OFFSET,
    PYFRAME_LOCALS_CELLS_STACK_OFFSET, PYFRAME_PYCODE_OFFSET, PYFRAME_VABLE_TOKEN_OFFSET,
    PYFRAME_VALUESTACKDEPTH_OFFSET, PYFRAME_W_GLOBALS_OFFSET,
};
use crate::state::PyreJitState;
use pyre_object::{FIXED_ARRAY_ITEMS_OFFSET, FIXED_ARRAY_LEN_OFFSET};

majit_macros::virtualizable! {
    state = PyreJitState,
    name = "frame",
    heap_ptr = |s: &PyreJitState| if s.frame != 0 { s.frame as *mut u8 } else { std::ptr::null_mut() },
    token_offset = PYFRAME_VABLE_TOKEN_OFFSET,

    // Frame pointer field in PyreJitState
    frame_field = frame,

    // Scalar inputarg fields: included in extract_live / jump_args.
    // Must match `fields` order — RPython includes ALL static fields
    // in unroll_static_fields (virtualizable.py:90-93 read_boxes).
    // Layout: [frame:Ref, last_instr:Int, pycode:Ref, valuestackdepth:Int,
    //          debugdata:Ref, lastblock:Ref, w_globals:Ref, array...]
    //
    // NOTE on `extra_reds`: the macro now also accepts an `extra_reds`
    // block for non-vable JitDriver reds (`interp_jit.py:67 reds =
    // ['frame', 'ec']`). Wiring `ec` here is deferred — adding ec to
    // the canonical scalar block shifts `SYM_ARRAY_BASE` /
    // `NUM_SCALAR_INPUTARGS` and requires a coordinated audit of every
    // call site that hardcodes `NUM_SCALAR_INPUTARGS + idx` (~30 sites
    // in `state.rs` / `trace_opcode.rs` / `eval.rs`) so the array_base
    // arithmetic stays correct. Macro support,
    // `PYFRAME_EXECUTION_CONTEXT_OFFSET`, and
    // `PyreJitState::{ec_as_usize, set_ec}` already landed; this comment
    // marks where `extra_reds = { ec: Ref }` will go once the cascading
    // layout fix lands as a separate slice.
    inputargs = {
        last_instr: Int,
        pycode: Ref,
        valuestackdepth: Int,
        debugdata: Ref,
        lastblock: Ref,
        w_globals: Ref,
    },

    // Array items are PyObjectRef (Ref)
    array_item_type = Ref,

    // VirtualizableInfo field layout (byte offsets)
    // interp_jit.py:25-31 order (excluding array field)
    fields = {
        last_instr: int @ PYFRAME_LAST_INSTR_OFFSET,
        pycode: ref @ PYFRAME_PYCODE_OFFSET,
        valuestackdepth: int @ PYFRAME_VALUESTACKDEPTH_OFFSET,
        debugdata: ref @ PYFRAME_DEBUGDATA_OFFSET,
        lastblock: ref @ PYFRAME_LASTBLOCK_OFFSET,
        w_globals: ref @ PYFRAME_W_GLOBALS_OFFSET,
    },

    // RPython virtualizable.py:28 parity: the array field holds a pointer
    // to a `Ptr(GcArray(PyObjectRef))` whose header is `[len][items...]`.
    // So GETFIELD_GC_R(frame, locals_cells_stack) + GETARRAYITEM_GC_R(p, i)
    // with `base_size = FIXED_ARRAY_ITEMS_OFFSET` reads items[i] directly,
    // no container indirection.
    arrays = {
        locals_cells_stack_w: ref @ PYFRAME_LOCALS_CELLS_STACK_OFFSET {
            length_offset: FIXED_ARRAY_LEN_OFFSET,
            items_offset: FIXED_ARRAY_ITEMS_OFFSET,
        },
    },
}
