//! Auto-generated virtualizable infrastructure for `PyFrame`.
//!
//! Generated by `majit_macros::virtualizable!` from the canonical field
//! declaration. Provides `build_virtualizable_info()`, field/array spec
//! constants, and JitState hook helpers.

use crate::frame_layout::{
    PYFRAME_CODE_OFFSET, PYFRAME_LOCALS_CELLS_STACK_OFFSET, PYFRAME_NAMESPACE_OFFSET,
    PYFRAME_NEXT_INSTR_OFFSET, PYFRAME_VABLE_TOKEN_OFFSET, PYFRAME_VALUESTACKDEPTH_OFFSET,
};
use crate::state::PyreJitState;
use pyre_object::{PYOBJECT_ARRAY_LEN_OFFSET, PYOBJECT_ARRAY_PTR_OFFSET};

majit_macros::virtualizable! {
    state = PyreJitState,
    name = "frame",
    heap_ptr = |s: &PyreJitState| if s.frame != 0 { s.frame as *mut u8 } else { std::ptr::null_mut() },
    token_offset = PYFRAME_VABLE_TOKEN_OFFSET,

    fields = {
        next_instr: int @ PYFRAME_NEXT_INSTR_OFFSET,
        code: ref @ PYFRAME_CODE_OFFSET,
        valuestackdepth: int @ PYFRAME_VALUESTACKDEPTH_OFFSET,
        namespace: ref @ PYFRAME_NAMESPACE_OFFSET,
    },

    arrays = {
        locals_cells_stack_w: ref @ PYFRAME_LOCALS_CELLS_STACK_OFFSET {
            embedded,
            ptr_offset: PYOBJECT_ARRAY_PTR_OFFSET,
            length_offset: PYOBJECT_ARRAY_LEN_OFFSET,
            items_offset: 0,
        },
    },
}
