//! Auto-generated virtualizable infrastructure for `PyFrame`.
//!
//! Generated by `majit_macros::virtualizable!` from the canonical field
//! declaration. Provides layout-based JitState helpers, VirtualizableInfo
//! builder, field/array spec constants, and virtualizable hook helpers.

use crate::frame_layout::{
    PYFRAME_CODE_OFFSET, PYFRAME_LOCALS_CELLS_STACK_OFFSET, PYFRAME_NAMESPACE_OFFSET,
    PYFRAME_NEXT_INSTR_OFFSET, PYFRAME_VABLE_TOKEN_OFFSET, PYFRAME_VALUESTACKDEPTH_OFFSET,
};
use crate::state::PyreJitState;
use pyre_object::{PYOBJECT_ARRAY_LEN_OFFSET, PYOBJECT_ARRAY_PTR_OFFSET};

majit_macros::virtualizable! {
    state = PyreJitState,
    name = "frame",
    heap_ptr = |s: &PyreJitState| if s.frame != 0 { s.frame as *mut u8 } else { std::ptr::null_mut() },
    token_offset = PYFRAME_VABLE_TOKEN_OFFSET,

    // Frame pointer field in PyreJitState
    frame_field = frame,

    // Scalar inputarg fields: included in extract_live / jump_args.
    // Must match `fields` order — RPython includes ALL static fields
    // in unroll_static_fields (virtualizable.py:90-93 read_boxes).
    // Layout: [frame:Ref, next_instr:Int, code:Ref, valuestackdepth:Int,
    //          namespace:Ref, array[0..len(lst)]:Ref]
    inputargs = {
        next_instr: Int,
        code: Ref,
        valuestackdepth: Int,
        namespace: Ref,
    },

    // Array items are PyObjectRef (Ref)
    array_item_type = Ref,

    // VirtualizableInfo field layout (byte offsets)
    fields = {
        next_instr: int @ PYFRAME_NEXT_INSTR_OFFSET,
        code: ref @ PYFRAME_CODE_OFFSET,
        valuestackdepth: int @ PYFRAME_VALUESTACKDEPTH_OFFSET,
        namespace: ref @ PYFRAME_NAMESPACE_OFFSET,
    },

    arrays = {
        locals_cells_stack_w: ref @ PYFRAME_LOCALS_CELLS_STACK_OFFSET {
            embedded,
            ptr_offset: PYOBJECT_ARRAY_PTR_OFFSET,
            length_offset: PYOBJECT_ARRAY_LEN_OFFSET,
            items_offset: 0,
        },
    },
}
