//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by the interpreter's build.rs via include!().

use crate::AnalysisResult;

/// Generate tracing Rust source code from analysis results.
pub fn generate(result: &AnalysisResult) -> String {
    let mut output = String::new();
    output.push_str("// Auto-generated by majit-analyze — do not edit manually.\n");
    output.push_str("// This file implements tracing for each opcode.\n\n");

    // Generate summary comment
    output.push_str(&format!(
        "// Analysis: {} opcodes, {} helpers, {} types, {} trait impls\n\n",
        result.opcodes.len(),
        result.helpers.len(),
        result.type_layouts.len(),
        result.trait_impls.len(),
    ));

    // Generate opcode trace table
    output.push_str("/// Opcode analysis results.\n");
    output.push_str("pub const OPCODE_COUNT: usize = ");
    output.push_str(&result.opcodes.len().to_string());
    output.push_str(";\n\n");

    // Generate per-opcode info as comments (for now)
    for (i, arm) in result.opcodes.iter().enumerate() {
        output.push_str(&format!(
            "// Opcode {}: pattern={}, calls={:?}, trace={:?}\n",
            i,
            arm.pattern,
            arm.handler_calls,
            arm.trace_pattern,
        ));
    }

    // Generate type layout info
    output.push_str("\n// Type layouts:\n");
    for layout in &result.type_layouts {
        output.push_str(&format!("// struct {} {{\n", layout.name));
        for field in &layout.fields {
            output.push_str(&format!("//   {}: {}\n", field.name, field.ty));
        }
        output.push_str("// }\n");
    }

    // Generate trait impl info
    output.push_str("\n// Trait implementations:\n");
    for impl_info in &result.trait_impls {
        output.push_str(&format!(
            "// impl {} for {} — {} methods\n",
            impl_info.trait_name,
            impl_info.for_type,
            impl_info.methods.len(),
        ));
    }

    output
}
