//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by pyre-mjit's build.rs via include!().
//!
//! Each recognized TracePattern produces a tracing function that emits
//! the equivalent IR ops. Unrecognized patterns fall back to residual calls.

use crate::patterns::TracePattern;
use crate::AnalysisResult;

/// Generate tracing Rust source code from analysis results.
pub fn generate(result: &AnalysisResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-analyze — do not edit manually.\n");
    out.push_str(&format!(
        "// Analysis: {} opcodes, {} classified\n\n",
        result.opcodes.len(),
        result
            .opcodes
            .iter()
            .filter(|a| a.trace_pattern.is_some())
            .count(),
    ));

    // Generate the dispatch table as a const array
    out.push_str("/// Trace pattern classification for each opcode.\n");
    out.push_str("pub const TRACE_PATTERNS: &[(&str, &str)] = &[\n");
    for arm in &result.opcodes {
        let pattern_str = match &arm.trace_pattern {
            Some(p) => format!("{:?}", p),
            None => "Unclassified".to_string(),
        };
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            arm.pattern.replace('"', "\\\""),
            pattern_str.replace('"', "\\\""),
        ));
    }
    out.push_str("];\n\n");

    // Generate helper function summaries
    out.push_str("/// Helper function classifications.\n");
    out.push_str("pub const HELPER_COUNT: usize = ");
    out.push_str(&result.helpers.len().to_string());
    out.push_str(";\n\n");

    // Generate trait impl summary
    out.push_str("// Trait implementations found:\n");
    for impl_info in &result.trait_impls {
        out.push_str(&format!(
            "// impl {} for {} — {} methods\n",
            impl_info.trait_name,
            impl_info.for_type,
            impl_info.methods.len(),
        ));
    }
    out.push('\n');

    // Summary stats
    let classified = result
        .opcodes
        .iter()
        .filter(|a| a.trace_pattern.is_some())
        .count();
    out.push_str(&format!(
        "// Analysis summary: {}/{} opcodes classified, {} helpers, {} trait impls\n",
        classified,
        result.opcodes.len(),
        result.helpers.len(),
        result.trait_impls.len(),
    ));

    out
}
