//! Narrow semantic graph scaffold for the future graph-based translator.
//!
//! This is intentionally much smaller than a full Rust compiler IR.  It exists
//! to model only the semantics needed by majit's translation/codewriter layer.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BasicBlockId(pub usize);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ValueId(pub usize);

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValueType {
    Int,
    Ref,
    Float,
    Void,
    State,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum OpKind {
    Input {
        name: String,
        ty: ValueType,
    },
    ConstInt(i64),
    FieldRead {
        base: ValueId,
        field: String,
        ty: ValueType,
    },
    FieldWrite {
        base: ValueId,
        field: String,
        value: ValueId,
        ty: ValueType,
    },
    ArrayRead {
        base: ValueId,
        index: ValueId,
        item_ty: ValueType,
    },
    ArrayWrite {
        base: ValueId,
        index: ValueId,
        value: ValueId,
        item_ty: ValueType,
    },
    Call {
        target: String,
        args: Vec<ValueId>,
        result_ty: ValueType,
    },
    GuardTrue {
        cond: ValueId,
    },
    GuardFalse {
        cond: ValueId,
    },

    // ── JIT-specific ops (generated by jtransform pass) ──────────
    //
    // RPython equivalent: jtransform.py rewrites generic FieldRead/ArrayRead
    // on virtualizable objects to these specialized ops.

    /// Virtualizable field read → reads from boxes, no heap op.
    /// RPython: `getfield_vable_i/r/f`
    VableFieldRead {
        field_index: usize,
        ty: ValueType,
    },
    /// Virtualizable field write → writes to boxes, no heap op.
    /// RPython: `setfield_vable_i/r/f`
    VableFieldWrite {
        field_index: usize,
        value: ValueId,
        ty: ValueType,
    },
    /// Virtualizable array read → reads from boxes.
    /// RPython: `getarrayitem_vable_i/r/f`
    VableArrayRead {
        array_index: usize,
        elem_index: ValueId,
        item_ty: ValueType,
    },
    /// Virtualizable array write → writes to boxes.
    /// RPython: `setarrayitem_vable_i/r/f`
    VableArrayWrite {
        array_index: usize,
        elem_index: ValueId,
        value: ValueId,
        item_ty: ValueType,
    },
    /// Force virtualizable: flush boxes to heap.
    /// RPython: `hint_force_virtualizable`
    VableForce,

    // ── Call effect classification (generated by jtransform) ────

    /// Elidable (pure) call — no side effects, result depends only on args.
    /// RPython: `call_elidable` / `EF_ELIDABLE`
    CallElidable {
        target: String,
        args: Vec<ValueId>,
        result_ty: ValueType,
    },
    /// Residual call — has side effects, must be preserved.
    /// RPython: `residual_call` / default effect
    CallResidual {
        target: String,
        args: Vec<ValueId>,
        result_ty: ValueType,
    },
    /// May-force call — can trigger GC or force virtualizables.
    /// RPython: `call_may_force` / `EF_FORCES_VIRTUAL_OR_VIRTUALIZABLE`
    CallMayForce {
        target: String,
        args: Vec<ValueId>,
        result_ty: ValueType,
    },

    Unknown {
        summary: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Op {
    pub result: Option<ValueId>,
    pub kind: OpKind,
}

/// How control flow leaves a basic block.
///
/// RPython equivalent: `Block.exitswitch` + `Block.exits` (Links).
/// Each variant that targets another block carries `args` which map
/// to the target block's `inputargs` (RPython `Link.args`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Terminator {
    /// Unconditional jump. `args` → target.inputargs.
    Goto { target: BasicBlockId, args: Vec<ValueId> },
    /// Conditional branch. Each arm carries its own args.
    Branch {
        cond: ValueId,
        if_true: BasicBlockId,
        true_args: Vec<ValueId>,
        if_false: BasicBlockId,
        false_args: Vec<ValueId>,
    },
    Return(Option<ValueId>),
    Abort {
        reason: String,
    },
    Unreachable,
}

/// A basic block in the control flow graph.
///
/// RPython equivalent: `flowspace/model.py Block`.
/// - `inputargs`: Phi-node inputs from predecessor Links (RPython Block.inputargs)
/// - `ops`: sequential operations within this block
/// - `terminator`: how control leaves this block
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BasicBlock {
    pub id: BasicBlockId,
    /// Phi-node inputs: values provided by incoming Links.
    /// RPython: `Block.inputargs` — each predecessor Link carries
    /// values that map 1:1 to these inputargs.
    pub inputargs: Vec<ValueId>,
    pub ops: Vec<Op>,
    pub terminator: Terminator,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MajitGraph {
    pub name: String,
    pub entry: BasicBlockId,
    pub blocks: Vec<BasicBlock>,
    #[serde(default)]
    pub notes: Vec<String>,
    next_value: usize,
    /// Variable names for debugging (RPython Variable._name).
    #[serde(default)]
    pub value_names: std::collections::HashMap<ValueId, String>,
}

impl MajitGraph {
    pub fn new(name: impl Into<String>) -> Self {
        let entry = BasicBlockId(0);
        Self {
            name: name.into(),
            entry,
            blocks: vec![BasicBlock {
                id: entry,
                inputargs: Vec::new(),
                ops: Vec::new(),
                terminator: Terminator::Unreachable,
            }],
            notes: Vec::new(),
            next_value: 0,
            value_names: std::collections::HashMap::new(),
        }
    }

    pub fn create_block(&mut self) -> BasicBlockId {
        let id = BasicBlockId(self.blocks.len());
        self.blocks.push(BasicBlock {
            id,
            inputargs: Vec::new(),
            ops: Vec::new(),
            terminator: Terminator::Unreachable,
        });
        id
    }

    /// Create a block with explicit inputargs (Phi nodes).
    pub fn create_block_with_args(&mut self, num_args: usize) -> (BasicBlockId, Vec<ValueId>) {
        let id = BasicBlockId(self.blocks.len());
        let args: Vec<ValueId> = (0..num_args).map(|_| self.alloc_value()).collect();
        self.blocks.push(BasicBlock {
            id,
            inputargs: args.clone(),
            ops: Vec::new(),
            terminator: Terminator::Unreachable,
        });
        (id, args)
    }

    pub fn alloc_value(&mut self) -> ValueId {
        let id = ValueId(self.next_value);
        self.next_value += 1;
        id
    }

    pub fn push_op(
        &mut self,
        block: BasicBlockId,
        kind: OpKind,
        has_result: bool,
    ) -> Option<ValueId> {
        let result = has_result.then(|| self.alloc_value());
        self.blocks[block.0].ops.push(Op { result, kind });
        result
    }

    pub fn set_terminator(&mut self, block: BasicBlockId, terminator: Terminator) {
        self.blocks[block.0].terminator = terminator;
    }

    pub fn block(&self, block: BasicBlockId) -> &BasicBlock {
        &self.blocks[block.0]
    }

    /// Name a value (RPython Variable._name).
    pub fn name_value(&mut self, id: ValueId, name: impl Into<String>) {
        self.value_names.insert(id, name.into());
    }

    /// Get the name of a value, if any.
    pub fn value_name(&self, id: ValueId) -> Option<&str> {
        self.value_names.get(&id).map(|s| s.as_str())
    }

    pub fn block_mut(&mut self, block: BasicBlockId) -> &mut BasicBlock {
        &mut self.blocks[block.0]
    }

    // ── RPython FunctionGraph iteration methods ──────────────────

    /// Iterate all blocks. RPython: `graph.iterblocks()`.
    pub fn iter_blocks(&self) -> impl Iterator<Item = &BasicBlock> {
        self.blocks.iter()
    }

    /// Iterate all (block, op) pairs. RPython: `graph.iterblockops()`.
    pub fn iter_block_ops(&self) -> impl Iterator<Item = (&BasicBlock, &Op)> {
        self.blocks.iter().flat_map(|b| b.ops.iter().map(move |op| (b, op)))
    }

    /// Get successor block IDs for a block.
    pub fn successors(&self, block: BasicBlockId) -> Vec<BasicBlockId> {
        match &self.block(block).terminator {
            Terminator::Goto { target, .. } => vec![*target],
            Terminator::Branch { if_true, if_false, .. } => vec![*if_true, *if_false],
            _ => vec![],
        }
    }

    /// Get predecessor block IDs for a block.
    pub fn predecessors(&self, target: BasicBlockId) -> Vec<BasicBlockId> {
        self.blocks
            .iter()
            .filter(|b| self.successors(b.id).contains(&target))
            .map(|b| b.id)
            .collect()
    }

    /// Count total operations across all blocks.
    pub fn num_ops(&self) -> usize {
        self.blocks.iter().map(|b| b.ops.len()).sum()
    }

    /// Check if a block is a loop header (has a back-edge predecessor).
    pub fn is_loop_header(&self, block: BasicBlockId) -> bool {
        self.predecessors(block).iter().any(|&pred| pred.0 >= block.0)
    }

    /// Pretty-print the graph (RPython `graph.show()`).
    pub fn dump(&self) -> String {
        let mut out = format!("=== {} ({} blocks, {} ops) ===\n", self.name, self.blocks.len(), self.num_ops());
        for block in &self.blocks {
            let args: Vec<String> = block.inputargs.iter().map(|v| self.fmt_value(*v)).collect();
            if args.is_empty() {
                out.push_str(&format!("  Block {}:\n", block.id.0));
            } else {
                out.push_str(&format!("  Block {}({}):\n", block.id.0, args.join(", ")));
            }
            for op in &block.ops {
                let result = op.result.map(|v| format!("{} = ", self.fmt_value(v))).unwrap_or_default();
                out.push_str(&format!("    {}{:?}\n", result, op.kind));
            }
            out.push_str(&format!("    → {:?}\n", block.terminator));
        }
        out
    }

    fn fmt_value(&self, id: ValueId) -> String {
        if let Some(name) = self.value_name(id) {
            format!("v{}:{}", id.0, name)
        } else {
            format!("v{}", id.0)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn graph_allocates_values_and_blocks() {
        let mut graph = MajitGraph::new("demo");
        let entry = graph.entry;
        let cond = graph
            .push_op(
                entry,
                OpKind::Input {
                    name: "x".into(),
                    ty: ValueType::Int,
                },
                true,
            )
            .unwrap();
        let next = graph.create_block();
        graph.set_terminator(
            entry,
            Terminator::Branch {
                cond,
                if_true: next,
                true_args: vec![],
                if_false: next,
                false_args: vec![],
            },
        );
        assert_eq!(graph.blocks.len(), 2);
        assert_eq!(graph.block(entry).ops.len(), 1);
    }
}
