//! JIT mainloop code generation from interpreter opcode match arms.
//!
//! Transforms an interpreter's opcode dispatch match expression into a
//! JIT-annotated mainloop module. Used by build.rs scripts in consumer
//! crates (e.g., aheui-mjit) to auto-generate JIT-enabled interpreters
//! from their pure interpreter source.

use crate::ast_transform::{rewrite_storage_refs, transform_branch_arm};
use crate::interp_extract::BinopMapping;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Generate a complete JIT mainloop module from an opcode match and binop mappings.
///
/// The generated code includes:
/// - Use declarations for the interpreter crate
/// - I/O shim wrappers for JIT-compiled code
/// - `AheuiState` struct wrapping storage and selector
/// - `#[jit_interp(...)]` annotated mainloop function
/// - Framework helper functions (`run_jit_back_edge`, `find_used_storages`,
///   `restore_jit_guard_state`)
///
/// Match arms are transformed:
/// - Regular arms: `storage`/`selected` references rewritten to `state.storage`/`state.selected`
/// - Branch arms (containing `get_label` + `continue`): rewritten to include JIT back-edge logic
pub fn generate_jit_mainloop(
    opcode_match: &syn::ExprMatch,
    binops: &[BinopMapping],
) -> TokenStream {
    let binop_entries: Vec<TokenStream> = binops
        .iter()
        .map(|b| {
            let method = format_ident!("{}", b.method);
            let opcode = format_ident!("{}", b.opcode);
            quote! { #method => #opcode }
        })
        .collect();

    // Transform the match arms:
    // - Replace `storage` with `state.storage`, `selected` with `state.selected`
    // - Transform the jump block to include run_jit_back_edge
    let match_scrutinee = &opcode_match.expr;
    let transformed_arms: Vec<TokenStream> = opcode_match
        .arms
        .iter()
        .map(|arm| {
            let pat = &arm.pat;
            let body = &arm.body;
            let body_str = quote!(#body).to_string();

            // Check if this is the branch arm (contains get_label + continue)
            if body_str.contains("get_label") && body_str.contains("continue") {
                // This is the jump/branch arm — generate the JIT version
                transform_branch_arm(pat, body)
            } else {
                // Regular arm — just rewrite storage/selected references
                let new_body = rewrite_storage_refs(quote!(#body));
                quote! { #pat => #new_body, }
            }
        })
        .collect();

    quote! {
        // AUTO-GENERATED by aheui-mjit/build.rs from aheui-interp/src/interp.rs
        // Do not edit — changes to interp.rs are automatically reflected.

        use aheui_interp::ahsembler::Program;
        use aheui_interp::aheui::*;
        use aheui_interp::io as aheui_io;
        use aheui_interp::storage::StoragePool;
        use aheui_interp::value::*;

        use majit_meta::JitDriver;
        use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

        const DEFAULT_THRESHOLD: u32 = 0;
        static JUST_COMPILED_KEY: AtomicU64 = AtomicU64::new(0);
        static JUST_COMPILED_PENDING: AtomicBool = AtomicBool::new(false);

        extern "C" fn jit_write_number(value: i64) {
            majit_meta::jit_write_number_i64(value);
        }

        extern "C" fn jit_write_utf8(value: i64) {
            majit_meta::jit_write_utf8_codepoint(value);
        }

        struct AheuiState { storage: StoragePool, selected: usize }

        #[majit_macros::jit_interp(
            state = AheuiState, env = Program,
            greens = [state.selected],
            storage = {
                pool: state.storage, pool_type: StoragePool,
                selector: state.selected,
                untraceable: [VAL_QUEUE, VAL_PORT],
                scan: find_used_storages,
                can_trace_guard: all_jit_compatible,
            },
            binops = { #(#binop_entries),* },
            io_shims = {
                aheui_io::output_write_number => jit_write_number,
                aheui_io::output_write_utf8 => jit_write_utf8,
            },
        )]
        pub fn mainloop(program: &Program, threshold: u32) -> Val {
            let mut driver: JitDriver<AheuiState> = JitDriver::new(threshold);
            driver.meta_interp_mut().set_bridge_threshold(0);
            driver.meta_interp_mut().set_on_compile_loop(|green_key, _, _| {
                JUST_COMPILED_KEY.store(green_key, Ordering::Relaxed);
                JUST_COMPILED_PENDING.store(true, Ordering::Relaxed);
            });

            let mut pc: usize = 0;
            let mut stacksize: i32 = 0;
            let mut state = AheuiState { storage: StoragePool::new(), selected: 0 };
            let mut input = aheui_io::InputBuffer::new();

            while pc < program.size {
                jit_merge_point!();
                let stackok = program.get_req_size(pc) as i32 <= stacksize;
                let op = program.get_op(pc);
                stacksize += -OP_STACKDEL[op as usize] + OP_STACKADD[op as usize];

                match #match_scrutinee {
                    #(#transformed_arms)*
                }
                pc += 1;
            }

            aheui_io::output_flush();

            if !state.storage.get(state.selected).is_empty() {
                state.storage.get_mut(state.selected).pop()
            } else {
                val_from_i32(0)
            }
        }

        pub const NO_JIT: u32 = u32::MAX;
        pub const JIT_THRESHOLD: u32 = DEFAULT_THRESHOLD;

        // ── Framework code ──

        #[inline]
        fn run_jit_back_edge(
            driver: &mut JitDriver<AheuiState>, target_pc: usize,
            state: &mut AheuiState, program: &Program, pre_run: impl FnOnce(),
        ) -> Option<usize> {
            // Skip first execution after compilation to avoid re-entering
            // the loop we just compiled in the same iteration.
            let green_values = [target_pc as i64, state.selected as i64];
            let key_hash = majit_meta::green_key_hash(&green_values);
            if JUST_COMPILED_PENDING.load(Ordering::Relaxed)
                && JUST_COMPILED_KEY.load(Ordering::Relaxed) == key_hash
            {
                JUST_COMPILED_PENDING.store(false, Ordering::Relaxed);
                return None;
            }

            let program_size = program.size;
            driver.run_back_edge_generic(
                &green_values, target_pc, state, program, pre_run,
                |state, meta, values| restore_jit_guard_state(state, meta, values, program_size),
            )
        }

        fn find_used_storages(program: &Program, header_pc: usize, initial: usize) -> Vec<usize> {
            let mut storages = vec![initial];
            let mut seen = std::collections::HashSet::new();
            seen.insert(initial);
            for pc in header_pc..program.size {
                let op = program.get_op(pc);
                let val = match op { OP_SEL | OP_MOV => program.get_operand(pc) as usize, _ => continue };
                // Skip untraceable storages (queue, port) — they have FIFO/last_push
                // semantics that the JIT's symbolic stack cannot model.
                if val == VAL_QUEUE || val == VAL_PORT { continue; }
                if seen.insert(val) { storages.push(val); }
            }
            storages
        }

        fn restore_jit_guard_state(state: &mut AheuiState, meta: &__JitMeta, values: &[i64], program_size: usize) -> Option<usize> {
            let storage_count = meta.storage_layout.len();
            let lengths_start = values.len().checked_sub(storage_count + 2)?;
            let lengths = &values[lengths_start..values.len() - 2];
            let selected = usize::try_from(values[values.len() - 2]).ok()?;
            let resume_pc = usize::try_from(values[values.len() - 1]).ok()?;
            if selected >= aheui_interp::aheui::STORAGE_COUNT || resume_pc > program_size { return None; }
            let flat_values = &values[..lengths_start];
            let mut total_values = 0usize;
            let mut decoded_lengths = Vec::with_capacity(lengths.len());
            for &len in lengths { let len = usize::try_from(len).ok()?; total_values += len; decoded_lengths.push(len); }
            if total_values != flat_values.len() || decoded_lengths.len() != meta.storage_layout.len() { return None; }
            let mut offset = 0usize;
            for ((storage_idx, _), &len) in meta.storage_layout.iter().zip(decoded_lengths.iter()) {
                let end = offset + len;
                let store = state.storage.get_mut(*storage_idx);
                store.clear();
                for &value in &flat_values[offset..end] { store.push(value); }
                offset = end;
            }
            state.selected = selected;
            Some(resume_pc)
        }
    }
}
