//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by pyre-mjit's build.rs via include!().
//!
//! Each recognized TracePattern produces a tracing function that emits
//! the equivalent IR ops. Unrecognized patterns fall back to residual calls.

/// Generate tracing code from graph pipeline results.
///
/// Test-only summary emitter for raw graph pipeline output. Active consumers
/// should use `generate_from_pipeline()`, which is the canonical translator
/// entry point.
#[cfg(test)]
pub fn generate_from_graph(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter graph pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));

    // Function summary
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");

    out
}

/// Generate tracing code directly from the canonical pipeline result.
///
/// This is the RPython-leaning entry point: graph/pipeline output is the only
/// source-of-truth used for emission.
pub fn generate_from_pipeline(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter canonical pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Canonical graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));
    out.push('\n');

    generate_graph_function_summary(&mut out, result);
    generate_canonical_dispatch_table(&mut out, result);
    generate_dispatch_tables(&mut out);
    generate_concrete_computation(&mut out);
    generate_concrete_object_helpers(&mut out);
    generate_trace_functions(&mut out);
    generate_typed_trace_methods(&mut out);

    let flattened_count = result
        .opcode_dispatch
        .iter()
        .filter(|a| a.flattened.is_some())
        .count();
    out.push_str(&format!(
        "// Canonical analysis summary: {}/{} flattened\n",
        flattened_count,
        result.opcode_dispatch.len(),
    ));

    out
}

/// Recognition report for pipeline analysis diagnostic.
///
/// Quantifies how much of the input source the pipeline recognizes,
/// surfacing Unknown ops and unresolved calls per opcode arm.
#[derive(Debug, Clone)]
pub struct RecognitionReport {
    pub total_opcodes: usize,
    pub flattened: usize,
    pub total_flat_ops: usize,
    pub unknown_ops: usize,
    pub unresolved_calls: usize,
    pub per_opcode: Vec<OpcodeRecognition>,
}

#[derive(Debug, Clone)]
pub struct OpcodeRecognition {
    pub selector: String,
    pub flat_ops: usize,
    pub unknowns: usize,
    pub unresolved: usize,
}

/// Analyze pipeline results to produce a recognition report.
pub fn recognition_report(result: &crate::passes::ProgramPipelineResult) -> RecognitionReport {
    use crate::model::OpKind;
    use crate::passes::flatten::FlatOp;

    let mut report = RecognitionReport {
        total_opcodes: result.opcode_dispatch.len(),
        flattened: 0,
        total_flat_ops: 0,
        unknown_ops: 0,
        unresolved_calls: 0,
        per_opcode: Vec::new(),
    };

    for arm in &result.opcode_dispatch {
        let selector = arm.selector.canonical_key();
        let Some(ssa) = &arm.flattened else {
            report.per_opcode.push(OpcodeRecognition {
                selector,
                flat_ops: 0,
                unknowns: 0,
                unresolved: 0,
            });
            continue;
        };

        report.flattened += 1;
        let mut unknowns = 0;
        let mut unresolved = 0;
        let mut flat_ops = 0;

        for insn in &ssa.insns {
            if let FlatOp::Op(op) = insn {
                flat_ops += 1;
                match &op.kind {
                    OpKind::Unknown { .. } => unknowns += 1,
                    OpKind::Call { target, .. } => {
                        if matches!(target, crate::model::CallTarget::UnsupportedExpr) {
                            unresolved += 1;
                        }
                    }
                    _ => {}
                }
            }
        }

        report.total_flat_ops += flat_ops;
        report.unknown_ops += unknowns;
        report.unresolved_calls += unresolved;
        report.per_opcode.push(OpcodeRecognition {
            selector,
            flat_ops,
            unknowns,
            unresolved,
        });
    }

    report
}

fn generate_graph_function_summary(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");
}

fn generate_canonical_dispatch_table(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Canonical analysis summary: opcode → flattened op count.\n");
    out.push_str("pub const CANONICAL_TRACE_PATTERNS: &[(&str, &str)] = &[\n");
    for arm in &result.opcode_dispatch {
        let status = match &arm.flattened {
            Some(f) => format!("Flattened({}ops)", f.insns.len()),
            None => "Unflattened".to_string(),
        };
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            arm.selector.canonical_key().replace('"', "\\\""),
            status.replace('"', "\\\""),
        ));
    }
    out.push_str("];\n\n");
}

fn generate_dispatch_tables(out: &mut String) {
    // ── Operator → OpCode dispatch tables ──
    // Generated from BinaryOperator/ComparisonOperator → majit_ir::OpCode mapping.
    // Consumed by trace_opcode.rs to replace manual match arms.

    // Int binary: BinaryOperator → (OpCode, has_overflow, needs_concrete_check)
    //
    // needs_concrete_check: FloorDiv/Mod need non-negative operands,
    // Lshift/Rshift need shift-in-range validation at concrete level.
    out.push_str(r#"
/// Int binary operator dispatch: `(base_op, inplace_op, opcode, has_overflow, needs_concrete_check)`.
pub const INT_BINOP_TABLE: &[(
    BinaryOperator, BinaryOperator, majit_ir::OpCode, bool, bool,
)] = &[
    (BinaryOperator::Add, BinaryOperator::InplaceAdd, majit_ir::OpCode::IntAddOvf, true, false),
    (BinaryOperator::Subtract, BinaryOperator::InplaceSubtract, majit_ir::OpCode::IntSubOvf, true, false),
    (BinaryOperator::Multiply, BinaryOperator::InplaceMultiply, majit_ir::OpCode::IntMulOvf, true, false),
    (BinaryOperator::FloorDivide, BinaryOperator::InplaceFloorDivide, majit_ir::OpCode::IntFloorDiv, false, true),
    (BinaryOperator::Remainder, BinaryOperator::InplaceRemainder, majit_ir::OpCode::IntMod, false, true),
    (BinaryOperator::And, BinaryOperator::InplaceAnd, majit_ir::OpCode::IntAnd, false, false),
    (BinaryOperator::Or, BinaryOperator::InplaceOr, majit_ir::OpCode::IntOr, false, false),
    (BinaryOperator::Xor, BinaryOperator::InplaceXor, majit_ir::OpCode::IntXor, false, false),
    (BinaryOperator::Lshift, BinaryOperator::InplaceLshift, majit_ir::OpCode::IntLshift, false, true),
    (BinaryOperator::Rshift, BinaryOperator::InplaceRshift, majit_ir::OpCode::IntRshift, false, true),
];

/// Look up int binary operator dispatch entry.
pub fn int_binop_lookup(op: BinaryOperator) -> Option<(majit_ir::OpCode, bool, bool)> {
    INT_BINOP_TABLE
        .iter()
        .find(|(base, inplace, _, _, _)| *base == op || *inplace == op)
        .map(|(_, _, opcode, ovf, concrete)| (*opcode, *ovf, *concrete))
}

/// Float binary operator dispatch: `(base_op, inplace_op, opcode)`.
///
/// resoperation.py:959-962: only FLOAT_ADD, FLOAT_SUB, FLOAT_MUL, FLOAT_TRUEDIV.
/// lloperation.py:260-261: no float_floordiv, no float_mod, no float_pow.
/// FloorDivide → _divmod_w() residual call (floatobject.py:508).
/// Remainder → math_fmod residual call (floatobject.py:520).
/// Power → ll_math_pow residual call (ll_math.py:260).
pub const FLOAT_BINOP_TABLE: &[(
    BinaryOperator, BinaryOperator, majit_ir::OpCode,
)] = &[
    (BinaryOperator::Add, BinaryOperator::InplaceAdd, majit_ir::OpCode::FloatAdd),
    (BinaryOperator::Subtract, BinaryOperator::InplaceSubtract, majit_ir::OpCode::FloatSub),
    (BinaryOperator::Multiply, BinaryOperator::InplaceMultiply, majit_ir::OpCode::FloatMul),
    (BinaryOperator::TrueDivide, BinaryOperator::InplaceTrueDivide, majit_ir::OpCode::FloatTrueDiv),
];

/// Look up float binary operator dispatch entry.
/// Returns None for FloorDivide, Remainder, Power and unsupported ops.
pub fn float_binop_lookup(op: BinaryOperator) -> Option<majit_ir::OpCode> {
    FLOAT_BINOP_TABLE
        .iter()
        .find(|(base, inplace, _)| *base == op || *inplace == op)
        .map(|(_, _, opcode)| *opcode)
}

/// Comparison operator dispatch: `(comp_op, int_opcode, float_opcode)`.
pub const COMPARE_TABLE: &[(
    ComparisonOperator, majit_ir::OpCode, majit_ir::OpCode,
)] = &[
    (ComparisonOperator::Less, majit_ir::OpCode::IntLt, majit_ir::OpCode::FloatLt),
    (ComparisonOperator::LessOrEqual, majit_ir::OpCode::IntLe, majit_ir::OpCode::FloatLe),
    (ComparisonOperator::Greater, majit_ir::OpCode::IntGt, majit_ir::OpCode::FloatGt),
    (ComparisonOperator::GreaterOrEqual, majit_ir::OpCode::IntGe, majit_ir::OpCode::FloatGe),
    (ComparisonOperator::Equal, majit_ir::OpCode::IntEq, majit_ir::OpCode::FloatEq),
    (ComparisonOperator::NotEqual, majit_ir::OpCode::IntNe, majit_ir::OpCode::FloatNe),
];

/// Look up comparison operator dispatch for int operands.
pub fn int_compare_lookup(op: ComparisonOperator) -> majit_ir::OpCode {
    COMPARE_TABLE
        .iter()
        .find(|(cmp, _, _)| *cmp == op)
        .map(|(_, int_op, _)| *int_op)
        .expect("all ComparisonOperator variants are covered")
}

/// Look up comparison operator dispatch for float operands.
pub fn float_compare_lookup(op: ComparisonOperator) -> majit_ir::OpCode {
    COMPARE_TABLE
        .iter()
        .find(|(cmp, _, _)| *cmp == op)
        .map(|(_, _, float_op)| *float_op)
        .expect("all ComparisonOperator variants are covered")
}
"#);
}

fn generate_concrete_computation(out: &mut String) {
    // ── Concrete computation helpers ──
    // Used by binary_value() to compute the concrete Python result during tracing.
    // Extracted from trace_opcode.rs match arms.

    out.push_str(
        r#"
/// Compute concrete float binary operation result.
/// Returns None for unsupported ops or division by zero.
///
/// floatobject.py: descr_add/sub/mul/truediv/floordiv/mod/pow
pub fn concrete_float_binop(op: BinaryOperator, lhs: f64, rhs: f64) -> Option<f64> {
    match op {
        BinaryOperator::Add | BinaryOperator::InplaceAdd => Some(lhs + rhs),
        BinaryOperator::Subtract | BinaryOperator::InplaceSubtract => Some(lhs - rhs),
        BinaryOperator::Multiply | BinaryOperator::InplaceMultiply => Some(lhs * rhs),
        BinaryOperator::TrueDivide | BinaryOperator::InplaceTrueDivide if rhs != 0.0 => {
            Some(lhs / rhs)
        }
        // floatobject.py:508: descr_floordiv → _divmod_w()[0]
        BinaryOperator::FloorDivide | BinaryOperator::InplaceFloorDivide if rhs != 0.0 => {
            Some(float_divmod_w(lhs, rhs).0)
        }
        // floatobject.py:520-540: descr_mod → fmod + sign correction + copysign
        BinaryOperator::Remainder | BinaryOperator::InplaceRemainder if rhs != 0.0 => {
            Some(float_mod(lhs, rhs))
        }
        // floatobject.py:561 descr_pow → _pow()
        BinaryOperator::Power | BinaryOperator::InplacePower => float_pow(lhs, rhs),
        _ => None,
    }
}

/// floatobject.py:520-540: float modulo with sign correction.
/// Uses fmod + denominator sign correction + copysign for zero remainder.
fn float_mod(x: f64, y: f64) -> f64 {
    let mut m = x % y; // C fmod semantics (same as Rust %)
    if m != 0.0 {
        // ensure the remainder has the same sign as the denominator
        if (y < 0.0) != (m < 0.0) {
            m += y;
        }
    } else {
        // the remainder is zero: ensure it has the same sign as the denominator
        m = f64::copysign(0.0, y);
    }
    m
}

/// floatobject.py:758-793: _divmod_w — returns (floordiv, mod).
fn float_divmod_w(x: f64, y: f64) -> (f64, f64) {
    let mut m = x % y; // fmod
    let mut div = (x - m) / y;
    if m != 0.0 {
        if (y < 0.0) != (m < 0.0) {
            m += y;
            div -= 1.0;
        }
    } else {
        m = m * m; // hide from optimizer
        if y < 0.0 { m = -m; }
    }
    // snap quotient to nearest integral value
    let floordiv = if div != 0.0 {
        let f = div.floor();
        if div - f > 0.5 { f + 1.0 } else { f }
    } else {
        let d = div * div; // hide from optimizer
        d * x / y
    };
    (floordiv, m)
}

/// floatobject.py:799-881: _pow with special-case handling.
/// Returns None for domain errors (negative base with fractional exponent).
fn float_pow(x: f64, y: f64) -> Option<f64> {
    if y == 2.0 {
        return Some(x * x);
    }
    if y == 0.0 {
        return Some(1.0);
    }
    if x.is_nan() {
        return Some(x);
    }
    if y.is_nan() {
        return Some(if x == 1.0 { 1.0 } else { y });
    }
    if y.is_infinite() {
        let ax = x.abs();
        if ax == 1.0 {
            return Some(1.0);
        } else if (y > 0.0) == (ax > 1.0) {
            return Some(f64::INFINITY);
        } else {
            return Some(0.0);
        }
    }
    if x.is_infinite() {
        let y_is_odd = y.abs() % 2.0 == 1.0;
        if y > 0.0 {
            return Some(if y_is_odd { x } else { x.abs() });
        } else {
            return Some(if y_is_odd { f64::copysign(0.0, x) } else { 0.0 });
        }
    }
    if x == 0.0 && y < 0.0 {
        return None; // ZeroDivisionError
    }
    let mut negate_result = false;
    let mut bx = x;
    if bx < 0.0 {
        if y.floor() != y {
            return None; // PowDomainError → ValueError
        }
        bx = -bx;
        negate_result = y.abs() % 2.0 == 1.0;
    }
    if bx == 1.0 {
        return Some(if negate_result { -1.0 } else { 1.0 });
    }
    let z = bx.powf(y);
    if z.is_infinite() || z.is_nan() {
        return None;
    }
    Some(if negate_result { -z } else { z })
}

/// Compute concrete int binary operation result.
/// Returns None for overflow, division by zero, or unsupported ops.
pub fn concrete_int_binop(op: BinaryOperator, lhs: i64, rhs: i64) -> Option<i64> {
    match op {
        BinaryOperator::Add | BinaryOperator::InplaceAdd => lhs.checked_add(rhs),
        BinaryOperator::Subtract | BinaryOperator::InplaceSubtract => lhs.checked_sub(rhs),
        BinaryOperator::Multiply | BinaryOperator::InplaceMultiply => lhs.checked_mul(rhs),
        BinaryOperator::Remainder | BinaryOperator::InplaceRemainder if rhs != 0 => {
            Some(((lhs % rhs) + rhs) % rhs)
        }
        BinaryOperator::FloorDivide | BinaryOperator::InplaceFloorDivide if rhs != 0 => {
            lhs.checked_div(rhs).map(|d| {
                if (lhs ^ rhs) < 0 && d * rhs != lhs { d - 1 } else { d }
            })
        }
        BinaryOperator::And | BinaryOperator::InplaceAnd => Some(lhs & rhs),
        BinaryOperator::Or | BinaryOperator::InplaceOr => Some(lhs | rhs),
        BinaryOperator::Xor | BinaryOperator::InplaceXor => Some(lhs ^ rhs),
        BinaryOperator::Lshift | BinaryOperator::InplaceLshift => {
            // intobject.py:205: negative shift → ValueError
            if rhs < 0 { return None; }
            let shift = rhs as u32;
            if shift >= 64 { return None; }
            let r = lhs.wrapping_shl(shift);
            if r.wrapping_shr(shift) != lhs { None } else { Some(r) }
        }
        BinaryOperator::Rshift | BinaryOperator::InplaceRshift => {
            // intobject.py:224: negative shift → ValueError("negative shift count")
            if rhs < 0 { return None; }
            let shift = rhs as u32;
            if shift >= 64 {
                Some(if lhs < 0 { -1 } else { 0 })
            } else {
                Some(lhs >> shift)
            }
        }
        _ => None,
    }
}
"#,
    );
}

fn generate_concrete_object_helpers(out: &mut String) {
    // ── Concrete object-level computation ──
    // Delegates to the actual interpreter dispatch functions.
    // baseobjspace.rs add/sub/mul/etc and compare() handle all type
    // combinations (int, long, float, str, list, tuple, dunder) so we
    // call them directly instead of reimplementing the dispatch.

    out.push_str(
        r#"
/// Concrete binary computation on Python objects.
///
/// Delegates to baseobjspace dispatch which handles:
///   is_int × is_int → int_add (checked, overflow → long)
///   is_int_or_long × is_int_or_long → long_add (BigInt)
///   is_float_pair → float_add (as_float coercion: int|float|long → f64)
///   str, list, tuple, bytearray, dunder dispatch
pub fn concrete_binary_value(
    op: BinaryOperator,
    lhs_obj: pyre_object::PyObjectRef,
    rhs_obj: pyre_object::PyObjectRef,
) -> crate::state::ConcreteValue {
    use crate::state::ConcreteValue;
    if lhs_obj.is_null() || rhs_obj.is_null() {
        return ConcreteValue::Null;
    }
    // Delegate to the interpreter's baseobjspace dispatch.
    // This handles all type combinations correctly including long,
    // overflow promotion, str/list/tuple concat, dunder methods.
    let result = pyre_interpreter::opcode_ops::binary_value(lhs_obj, rhs_obj, op);
    match result {
        Ok(r) => ConcreteValue::from_pyobj(r),
        Err(_) => ConcreteValue::Null,
    }
}

/// Concrete comparison computation on Python objects.
///
/// Delegates to baseobjspace::compare which handles:
///   is_int × is_int → int comparison
///   is_int_or_long × is_int_or_long → BigInt comparison
///   is_float_pair → float comparison (as_float coercion)
///   str comparison, dunder dispatch
pub fn concrete_compare_value(
    op: ComparisonOperator,
    lhs_obj: pyre_object::PyObjectRef,
    rhs_obj: pyre_object::PyObjectRef,
) -> crate::state::ConcreteValue {
    use crate::state::ConcreteValue;
    if lhs_obj.is_null() || rhs_obj.is_null() {
        return ConcreteValue::Null;
    }
    let result = pyre_interpreter::opcode_ops::compare_value(lhs_obj, rhs_obj, op);
    match result {
        Ok(r) => ConcreteValue::from_pyobj(r),
        Err(_) => ConcreteValue::Null,
    }
}
"#,
    );
}

fn generate_trace_functions(out: &mut String) {
    // ── Unbox/Box helpers ──
    // These are the core building blocks for tracing Python operations.
    // They mirror PyPy's RPython-generated unbox/box sequences.

    out.push_str(r#"
/// Unbox a Python int object: emit GuardClass + GetfieldGc(I|PureI).
///
/// Auto-generated equivalent of PyPy's int_unbox annotation.
/// Returns the raw i64 OpRef, with heapcache integration.
fn getfield_gc_i_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // heapcache: check if this field was already read/written in this trace
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureI
    } else {
        OpCode::GetfieldGcI
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_int(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // GUARD_CLASS(box, cls): guard takes object box directly,
    // backend loads typeptr at offset 0 (llgraph/runner.py:1245).
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(int_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(int_type_addr as usize));
    }
    getfield_gc_i_pureornot(ctx, obj, intval_descr)
}

/// Box a raw i64 into a Python int object.
///
/// Auto-generated equivalent of PyPy's int_box annotation.
/// The helper route preserves pyre's small-int cache instead of always
/// materializing a fresh heap object in the trace.
pub fn trace_box_int(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    _ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    _int_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;

    // Inline W_Int allocation so OptVirtualize can see the object shape
    // and fold later GetfieldRawI(intval) reads back to `value`.
    // RPython parity: NEW_WITH_VTABLE (not NEW) for classes with vtable.
    // jtransform.py:908-911 parity: typeptr setfield filtered in trace.
    // rewrite.py:479-484 GC rewriter emits vtable via fielddescr_vtable.
    let obj = ctx.record_op_with_descr(OpCode::NewWithVtable, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let intval_idx = intval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], intval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, intval_idx, value);
    obj
}

/// Emit an overflow-checked binary int operation.
///
/// Auto-generated: unbox a, unbox b, emit ovf op, guard no overflow, box result.
pub fn trace_int_binop_ovf(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    ctx.record_guard_typed_with_fail_args(
        OpCode::GuardNoOverflow, &[],
        vec![majit_ir::Type::Ref; fail_args.len()], fail_args,
    );
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a non-overflow binary int operation (bitwise ops, shifts).
pub fn trace_int_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a comparison between two Python ints.
pub fn trace_int_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}

/// Unbox a Python float object: emit GuardClass + GetfieldGc(F|PureF).
///
/// Returns the raw f64 OpRef.
fn getfield_gc_f_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureF
    } else {
        OpCode::GetfieldGcF
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_float(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(float_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(float_type_addr as usize));
    }
    getfield_gc_f_pureornot(ctx, obj, floatval_descr)
}

/// Box a raw f64 into a Python float object: emit New + SetfieldGc.
pub fn trace_box_float(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    _ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    _float_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // RPython parity: NEW_WITH_VTABLE + jtransform.py typeptr filter +
    // rewrite.py GC rewriter fielddescr_vtable emission.
    let obj = ctx.record_op_with_descr(OpCode::NewWithVtable, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let floatval_idx = floatval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], floatval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, floatval_idx, value);
    obj
}

/// Emit a binary float operation: unbox a, unbox b, emit float op, box result.
pub fn trace_float_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_float(ctx, result, size_descr, ob_type_descr, floatval_descr, float_type_addr)
}

/// Emit a comparison between two Python floats.
pub fn trace_float_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}
"#);
}

fn generate_typed_trace_methods(out: &mut String) {
    // ── High-level typed trace methods ──
    //
    // RPython jitcode equivalents:
    //   int binary:  guard_class(a) → getfield_gc_i(a) → guard_class(b)
    //                → getfield_gc_i(b) → int_add_ovf(a_raw, b_raw)
    //                → guard_no_overflow → new_with_vtable → setfield_gc
    //   float binary: guard_class(a) → getfield_gc_f/cast_int_to_float(a)
    //                 → guard_class(b) → getfield_gc_f/cast_int_to_float(b)
    //                 → float_add(a_raw, b_raw) → new_with_vtable → setfield_gc
    //   int compare:  guard_class(a) → getfield_gc_i(a) → guard_class(b)
    //                 → getfield_gc_i(b) → int_lt(a_raw, b_raw)
    //
    // These compose the primitive trace_unbox/trace_box functions
    // into complete typed operation sequences.
    // Generated code is include!()'d into pyre-jit-trace at crate root,
    // so it has access to crate::state, crate::helpers, crate::descr.

    out.push_str(r#"

/// Trace a binary int operation: unbox → op → guard_ovf → box.
///
/// RPython jitcode parity: guard_class + getfield_gc_i (per operand),
/// then int_OP_ovf + guard_no_overflow (or int_OP), then
/// new_with_vtable + setfield_gc for boxing.
///
/// Returns None if the operation is not handled as an int operation
/// (unsupported op or concrete validation fails → caller should
/// fall back to residual trace_binary_value).
#[inline]
pub fn generated_binary_int_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    op: BinaryOperator,
    concrete_lhs: pyre_object::PyObjectRef,
    concrete_rhs: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    // Table lookup: BinaryOperator → (OpCode, has_overflow, needs_concrete_check)
    let (op_code, has_overflow, needs_concrete_check) = int_binop_lookup(op)?;

    // Concrete value extraction for range validation.
    let concrete = unsafe {
        if concrete_lhs.is_null()
            || concrete_rhs.is_null()
            || !pyre_object::is_int(concrete_lhs)
            || !pyre_object::is_int(concrete_rhs)
        {
            None
        } else {
            Some((
                pyre_object::w_int_get_value(concrete_lhs),
                pyre_object::w_int_get_value(concrete_rhs),
            ))
        }
    };

    // intobject.py range validation for FloorDiv/Mod/Shift.
    // RPython generates these as branches in jitcode; pyre validates
    // concretely and falls back to residual for out-of-range cases.
    if needs_concrete_check {
        match op_code {
            OpCode::IntFloorDiv | OpCode::IntMod => {
                let (lhs, rhs) = concrete?;
                if lhs < 0 || rhs <= 0 {
                    return None;
                }
            }
            OpCode::IntLshift => {
                let (lhs, rhs) = concrete?;
                let shift = u32::try_from(rhs).ok()?;
                if shift >= i64::BITS {
                    return None;
                }
                // intobject.py:207 ovfcheck(a << b)
                let result = lhs.wrapping_shl(shift);
                if result.wrapping_shr(shift) != lhs {
                    return None;
                }
            }
            OpCode::IntRshift => {
                let (lhs, rhs) = concrete?;
                let shift = u32::try_from(rhs).ok()?;
                if shift >= i64::BITS {
                    // intobject.py:229-231: large shift → 0 or -1
                    let result = if lhs < 0 { -1i64 } else { 0i64 };
                    let raw = ctx.const_int(result);
                    let boxed = crate::state::wrapint(ctx, raw);
                    frame.remember_value_type(boxed, majit_ir::Type::Ref);
                    return Some(boxed);
                }
            }
            _ => {}
        }
    }

    // RPython jitcode: guard_class + getfield_gc_i per operand.
    // Skip unbox if value is already raw int (Type::Int).
    let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
    let lhs_raw = if frame.value_type(a) == majit_ir::Type::Int {
        a
    } else {
        crate::state::trace_unbox_int_with_resume(frame, ctx, a, int_type_addr)
    };
    let rhs_raw = if frame.value_type(b) == majit_ir::Type::Int {
        b
    } else {
        crate::state::trace_unbox_int_with_resume(frame, ctx, b, int_type_addr)
    };

    // RPython jitcode: int_OP_ovf(a_raw, b_raw) → guard_no_overflow
    let raw_result = ctx.record_op(op_code, &[lhs_raw, rhs_raw]);
    if has_overflow {
        frame.generate_guard(ctx, OpCode::GuardNoOverflow, &[]);
    }

    // RPython jitcode: wrapint → new_with_vtable + setfield_gc
    let boxed = crate::state::wrapint(ctx, raw_result);
    frame.remember_value_type(boxed, majit_ir::Type::Ref);
    Some(boxed)
}

/// Trace a binary float operation: unbox/cast → op → box.
///
/// RPython jitcode parity: guard_class + getfield_gc_f (or
/// getfield_gc_i + cast_int_to_float for int operands), then
/// float_OP, then new_with_vtable + setfield_gc.
///
/// Returns None if the operation is not handled as a float operation
/// → caller should fall back to residual trace_binary_value.
#[inline]
pub fn generated_binary_float_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    op: BinaryOperator,
    concrete_lhs: pyre_object::PyObjectRef,
    concrete_rhs: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    let is_power = matches!(op, BinaryOperator::Power | BinaryOperator::InplacePower);
    let op_code = float_binop_lookup(op);

    // resoperation.py: no FLOAT_POW / FLOAT_FLOORDIV / FLOAT_MOD opcodes.
    // FloorDivide/Remainder → residual.
    // Power → call_may_force (ll_math_pow, EF_CAN_RAISE).
    if op_code.is_none() && !is_power {
        return None;
    }

    // Determine which operands are int (need int→float cast) vs float.
    // RPython: float_add etc. call space.float_w() which dispatches on
    // type — int objects go through int2float (CastIntToFloat).
    let lhs_is_int = (!concrete_lhs.is_null() && unsafe { pyre_object::is_int(concrete_lhs) })
        || frame.value_type(a) == majit_ir::Type::Int;
    let rhs_is_int = (!concrete_rhs.is_null() && unsafe { pyre_object::is_int(concrete_rhs) })
        || frame.value_type(b) == majit_ir::Type::Int;

    // floatobject.py _to_float: accepts int, float, long.
    // Long → residual fallback (long→float can lose precision).
    let lhs_is_long =
        !concrete_lhs.is_null() && unsafe { pyre_object::is_long(concrete_lhs) } && !lhs_is_int;
    let rhs_is_long =
        !concrete_rhs.is_null() && unsafe { pyre_object::is_long(concrete_rhs) } && !rhs_is_int;
    if lhs_is_long || rhs_is_long {
        return None;
    }

    let float_type_addr =
        &pyre_object::pyobject::FLOAT_TYPE as *const _ as i64;
    let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;

    // Unbox a float object to raw f64.
    let unbox_float =
        |frame: &mut crate::state::MIFrame, ctx: &mut majit_metainterp::TraceCtx, obj: majit_ir::OpRef| -> majit_ir::OpRef {
            if !ctx.heap_cache().is_class_known(obj) {
                let type_const = ctx.const_int(float_type_addr);
                frame.generate_guard(ctx, OpCode::GuardClass, &[obj, type_const]);
                ctx.heap_cache_mut()
                    .class_now_known(obj, majit_ir::GcRef(float_type_addr as usize));
            }
            {
                let ff_descr = crate::descr::float_floatval_descr();
                let ff_idx = ff_descr.index();
                if let Some(cached) = ctx.heap_cache().getfield_cached(obj, ff_idx) {
                    cached
                } else {
                    let r = ctx.record_op_with_descr(OpCode::GetfieldGcPureF, &[obj], ff_descr);
                    ctx.heap_cache_mut().getfield_now_known(obj, ff_idx, r);
                    r
                }
            }
        };

    // Unbox an int object to raw i64, then CastIntToFloat → f64.
    // RPython: space.float_w(w_int) → float(w_int.intval)
    let unbox_int_to_float =
        |frame: &mut crate::state::MIFrame, ctx: &mut majit_metainterp::TraceCtx, obj: majit_ir::OpRef| -> majit_ir::OpRef {
            let raw_int = if frame.value_type(obj) == majit_ir::Type::Int {
                obj
            } else {
                crate::state::trace_unbox_int_with_resume(frame, ctx, obj, int_type_addr)
            };
            ctx.record_op(OpCode::CastIntToFloat, &[raw_int])
        };

    let lhs_raw = if frame.value_type(a) == majit_ir::Type::Float {
        a
    } else if lhs_is_int {
        unbox_int_to_float(frame, ctx, a)
    } else {
        unbox_float(frame, ctx, a)
    };
    let rhs_raw = if frame.value_type(b) == majit_ir::Type::Float {
        b
    } else if rhs_is_int {
        unbox_int_to_float(frame, ctx, b)
    } else {
        unbox_float(frame, ctx, b)
    };

    let result = if is_power {
        // floatobject.py:561 descr_pow → _pow(space, x, y) parity.
        // ll_math_pow (ll_math.py:260) is EF_CAN_RAISE, NOT force_virtual.
        // pyjitpl.py:2084-2121 execute_varargs(rop.CALL_F, ..., exc=True, pure=False)
        // → records CALL_F and then handle_possible_exception → GUARD_NO_EXCEPTION.
        let call_result = ctx.call_float_typed(
            crate::trace_opcode::float_pow_jit as *const (),
            &[lhs_raw, rhs_raw],
            &[majit_ir::Type::Float, majit_ir::Type::Float],
        );
        // pyjitpl.py:3395 GUARD_NO_EXCEPTION from handle_possible_exception.
        frame.generate_guard(ctx, OpCode::GuardNoException, &[]);
        call_result
    } else {
        ctx.record_op(op_code.unwrap(), &[lhs_raw, rhs_raw])
    };
    frame.remember_value_type(result, majit_ir::Type::Float);

    // RPython: wrapfloat → new_with_vtable + setfield_gc
    let boxed = crate::state::wrapfloat(ctx, result);
    frame.remember_value_type(boxed, majit_ir::Type::Ref);
    Some(boxed)
}

/// Trace a comparison between two Python objects.
///
/// RPython jitcode parity (int path):
///   guard_class(a) → getfield_gc_i(a) → guard_class(b) → getfield_gc_i(b)
///   → int_lt(a_raw, b_raw)
/// RPython jitcode parity (float path):
///   guard_class(a) → getfield_gc_f(a) → guard_class(b) → getfield_gc_f(b)
///   → float_lt(a_raw, b_raw)
///
/// Returns None if neither int nor float path applies → caller
/// falls back to trace_compare_value (residual).
#[inline]
pub fn generated_compare_value_direct(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    op: ComparisonOperator,
    concrete_lhs: pyre_object::PyObjectRef,
    concrete_rhs: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    if concrete_lhs.is_null() || concrete_rhs.is_null() {
        return None;
    }

    unsafe {
        if pyre_object::is_int(concrete_lhs) && pyre_object::is_int(concrete_rhs) {
            let cmp = int_compare_lookup(op);
            let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
            let lhs_raw = if frame.value_type(a) == majit_ir::Type::Int {
                a
            } else if let Some(raw) = crate::state::try_trace_const_boxed_int(ctx, a, concrete_lhs) {
                raw
            } else {
                crate::state::trace_unbox_int_with_resume(frame, ctx, a, int_type_addr)
            };
            let rhs_raw = if frame.value_type(b) == majit_ir::Type::Int {
                b
            } else if let Some(raw) = crate::state::try_trace_const_boxed_int(ctx, b, concrete_rhs) {
                raw
            } else {
                crate::state::trace_unbox_int_with_resume(frame, ctx, b, int_type_addr)
            };
            let truth = ctx.record_op(cmp, &[lhs_raw, rhs_raw]);
            frame.remember_value_type(truth, majit_ir::Type::Int);
            // RPython goto_if_not fusion: cache truth for
            // the next POP_JUMP_IF to consume directly.
            frame.sym_mut().last_comparison_truth = Some(truth);
            frame.sym_mut().last_comparison_concrete_truth =
                Some(crate::state::objspace_compare_ints(concrete_lhs, concrete_rhs, op));
            return if frame.next_instruction_consumes_comparison_truth() {
                Some(truth)
            } else {
                Some(crate::helpers::emit_trace_bool_value_from_truth(ctx, truth, false))
            };
        }
        // baseobjspace::compare step 2: is_int_or_long × is_int_or_long
        // Long comparison needs BigInt which can't be inlined → residual (None).
        if pyre_object::is_int_or_long(concrete_lhs) && pyre_object::is_int_or_long(concrete_rhs) {
            return None;
        }
        // baseobjspace::compare step 3: is_float_pair
        // Handles float×float, float×int, int×float.
        // Long in float_pair → residual (can't inline long→f64).
        let lhs_is_float = pyre_object::is_float(concrete_lhs);
        let rhs_is_float = pyre_object::is_float(concrete_rhs);
        let lhs_is_int = pyre_object::is_int(concrete_lhs);
        let rhs_is_int = pyre_object::is_int(concrete_rhs);
        let lhs_numeric = lhs_is_float || lhs_is_int;
        let rhs_numeric = rhs_is_float || rhs_is_int;
        let is_trace_float_pair = lhs_numeric && rhs_numeric && (lhs_is_float || rhs_is_float);
        if is_trace_float_pair {
            let cmp = float_compare_lookup(op);
            let float_type_addr =
                &pyre_object::pyobject::FLOAT_TYPE as *const _ as i64;
            let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
            // Unbox lhs: float direct, int via CastIntToFloat
            let lhs_raw = if frame.value_type(a) == majit_ir::Type::Float {
                a
            } else if lhs_is_int || frame.value_type(a) == majit_ir::Type::Int {
                let raw_int = if frame.value_type(a) == majit_ir::Type::Int {
                    a
                } else {
                    crate::state::trace_unbox_int_with_resume(frame, ctx, a, int_type_addr)
                };
                ctx.record_op(majit_ir::OpCode::CastIntToFloat, &[raw_int])
            } else {
                crate::state::trace_unbox_float_with_resume(frame, ctx, a, float_type_addr)
            };
            // Unbox rhs: same pattern
            let rhs_raw = if frame.value_type(b) == majit_ir::Type::Float {
                b
            } else if rhs_is_int || frame.value_type(b) == majit_ir::Type::Int {
                let raw_int = if frame.value_type(b) == majit_ir::Type::Int {
                    b
                } else {
                    crate::state::trace_unbox_int_with_resume(frame, ctx, b, int_type_addr)
                };
                ctx.record_op(majit_ir::OpCode::CastIntToFloat, &[raw_int])
            } else {
                crate::state::trace_unbox_float_with_resume(frame, ctx, b, float_type_addr)
            };
            let truth = ctx.record_op(cmp, &[lhs_raw, rhs_raw]);
            frame.remember_value_type(truth, majit_ir::Type::Int);
            frame.sym_mut().last_comparison_truth = Some(truth);
            frame.sym_mut().last_comparison_concrete_truth =
                Some(crate::state::objspace_compare_floats(concrete_lhs, concrete_rhs, op));
            return if frame.next_instruction_consumes_comparison_truth() {
                Some(truth)
            } else {
                Some(crate::helpers::emit_trace_bool_value_from_truth(ctx, truth, false))
            };
        }
    }

    None
}

/// Trace a unary int operation: unbox → op → (no re-box, returns raw int).
///
/// RPython jitcode parity: guard_class + getfield_gc_i + INT_NEG/INT_INVERT.
/// For IntNeg, also emits guard_false(value == INT_MIN) to prevent overflow.
///
/// Returns None if the operand is not an int → caller should fall back
/// to residual trace_unary_negative/invert_value.
#[inline]
pub fn generated_unary_int_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    concrete_value: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    let is_int_operand = !concrete_value.is_null() && unsafe { pyre_object::is_int(concrete_value) };
    if !is_int_operand {
        return None;
    }

    // RPython jitcode: guard_class + getfield_gc_i
    let payload = if frame.value_type(value) == majit_ir::Type::Int {
        value
    } else {
        let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
        crate::state::trace_unbox_int_with_resume(frame, ctx, value, int_type_addr)
    };
    // intobject.py int_neg: guard against INT_MIN (overflow to long).
    if matches!(opcode, OpCode::IntNeg) {
        let min_val = ctx.const_int(i64::MIN);
        let is_min = ctx.record_op(OpCode::IntEq, &[payload, min_val]);
        frame.generate_guard(ctx, OpCode::GuardFalse, &[is_min]);
    }
    let result = ctx.record_op(opcode, &[payload]);
    frame.remember_value_type(result, majit_ir::Type::Int);
    Some(result)
}

/// Trace list[int_key] setitem: guard_class → guard_strategy → arraylen →
/// index computation → items_ptr → raw array setitem.
///
/// Corresponds to PyPy list strategy model (pypy/objspace/std/listobject.py)
/// as compiled through the codewriter. In RPython, the jtransform expands
/// list storage access into guard_class + getfield(items) + check_neg_index
/// + setarrayitem_gc sequences; pyjitpl.py:814 opimpl_getlistitem_gc_* itself
/// is just the final getfield+getarrayitem step. This function covers the
/// full expanded sequence including strategy guard and index normalization.
///
/// strategy_id: 0 = object, 1 = int, 2 = float.
/// For int/float strategies, the value is unboxed before writing.
#[inline]
pub fn generated_list_setitem_by_strategy(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    key: majit_ir::OpRef,
    value: majit_ir::OpRef,
    concrete_key: i64,
    strategy_id: i64,
) {
    frame.guard_class(ctx, obj, &pyre_object::pyobject::LIST_TYPE as *const _ as *const pyre_object::PyType);
    frame.guard_list_strategy(ctx, obj, strategy_id);
    let (len_descr, ptr_descr) = match strategy_id {
        0 => (crate::descr::list_items_len_descr(), crate::descr::list_items_ptr_descr()),
        1 => (crate::descr::list_int_items_len_descr(), crate::descr::list_int_items_ptr_descr()),
        2 => (crate::descr::list_float_items_len_descr(), crate::descr::list_float_items_ptr_descr()),
        _ => unreachable!(),
    };
    let len = crate::state::trace_arraylen_gc(ctx, obj, len_descr);
    let index = frame.trace_dynamic_list_index(ctx, key, len, concrete_key);
    let items_ptr = crate::state::opimpl_getfield_gc_i(ctx, obj, ptr_descr);
    match strategy_id {
        0 => crate::state::trace_raw_array_setitem_value(ctx, items_ptr, index, value),
        1 => {
            let raw = if frame.value_type(value) == majit_ir::Type::Int {
                value
            } else {
                let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
                crate::state::trace_unbox_int_with_resume(frame, ctx, value, int_type_addr)
            };
            crate::state::trace_raw_int_array_setitem_value(ctx, items_ptr, index, raw);
        }
        2 => {
            let raw = if frame.value_type(value) == majit_ir::Type::Float {
                value
            } else {
                let float_type_addr = &pyre_object::pyobject::FLOAT_TYPE as *const _ as i64;
                crate::state::trace_unbox_float_with_resume(frame, ctx, value, float_type_addr)
            };
            crate::state::trace_raw_float_array_setitem_value(ctx, items_ptr, index, raw);
        }
        _ => unreachable!(),
    }
}

/// Trace truth value (is_true) for a Python object.
///
/// RPython jitcode parity: the codewriter generates type-specialized
/// truth tests from space.is_true(w_obj):
///   bool: guard_class + getfield_gc_i(boolval) → int_ne(val, 0)
///   int:  guard_class + getfield_gc_i(intval) → int_ne(val, 0)
///   float: guard_class + getfield_gc_f(floatval) → float_ne(val, 0.0)
///   None: guard_class → const_int(0)
///   str:  guard_class + getfield_raw_i(len) → int_ne(len, 0)
///   dict: guard_class + getfield_raw_i(len) → int_ne(len, 0)
///   list: guard_class + getfield_raw_i(items_len) → int_ne(len, 0)
///   tuple: guard_class + getfield_raw_i(items_len) → int_ne(len, 0)
///
/// Returns None if the concrete type is not handled → caller falls
/// back to residual trace_truth_value.
#[inline]
pub fn generated_truth_value_direct(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    concrete_val: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    // RPython goto_if_not fusion: if the previous op was a comparison,
    // use the cached raw truth (0/1) directly.
    if let Some(truth) = frame.sym_mut().last_comparison_truth.take() {
        return Some(truth);
    }

    if !concrete_val.is_null() {
        let cached_concrete_truth = pyre_interpreter::truth_value(concrete_val);
        frame.sym_mut().last_comparison_concrete_truth = Some(cached_concrete_truth);
    }

    // Already-unboxed values (Type::Int or Type::Float from earlier operations).
    if frame.value_type(value) == majit_ir::Type::Int {
        let zero = ctx.const_int(0);
        return Some(ctx.record_op(OpCode::IntNe, &[value, zero]));
    }
    if frame.value_type(value) == majit_ir::Type::Float {
        let zero = ctx.const_int(0);
        let zero_float = ctx.record_op(OpCode::CastIntToFloat, &[zero]);
        return Some(ctx.record_op(OpCode::FloatNe, &[value, zero_float]));
    }

    if concrete_val.is_null() {
        return None;
    }

    unsafe {
        // intobject.py: int_is_true → guard_class + getfield(intval) → int_ne(0)
        if pyre_object::is_int(concrete_val) {
            let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
            let int_value = if let Some(raw) =
                crate::state::try_trace_const_boxed_int(ctx, value, concrete_val)
            {
                raw
            } else {
                crate::state::trace_unbox_int_with_resume(frame, ctx, value, int_type_addr)
            };
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[int_value, zero]));
        }
        // boolobject.py: bool_is_true → guard_class + getfield(boolval) → int_ne(0)
        if pyre_object::is_bool(concrete_val) {
            let bool_type_addr = &pyre_object::pyobject::BOOL_TYPE as *const _ as i64;
            let bool_value = if let Some(raw) =
                crate::state::try_trace_const_boxed_int(ctx, value, concrete_val)
            {
                raw
            } else {
                crate::state::trace_unbox_int_with_resume_descr(
                    frame, ctx, value, bool_type_addr,
                    crate::descr::bool_boolval_descr(),
                )
            };
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[bool_value, zero]));
        }
        // noneobject.py: None is always false
        if pyre_object::is_none(concrete_val) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::NONE_TYPE as *const _ as *const pyre_object::PyType);
            return Some(ctx.const_int(0));
        }
        // floatobject.py: float_is_true → guard_class + getfield(floatval) → float_ne(0.0)
        if pyre_object::is_float(concrete_val) {
            let float_type_addr = &pyre_object::pyobject::FLOAT_TYPE as *const _ as i64;
            let float_value = crate::state::trace_unbox_float_with_resume(
                frame, ctx, value, float_type_addr,
            );
            let zero = ctx.const_int(0);
            let zero_float = ctx.record_op(OpCode::CastIntToFloat, &[zero]);
            return Some(ctx.record_op(OpCode::FloatNe, &[float_value, zero_float]));
        }
        // strobject.py: str truth → guard_class + getfield_raw(len) → int_ne(0)
        if pyre_object::is_str(concrete_val) {
            frame.guard_class(ctx, value, &pyre_object::STR_TYPE as *const _ as *const pyre_object::PyType);
            let len = ctx.record_op_with_descr(OpCode::GetfieldRawI, &[value], crate::descr::str_len_descr());
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[len, zero]));
        }
        // dictobject.py: dict truth → guard_class + getfield_raw(len) → int_ne(0)
        if pyre_object::is_dict(concrete_val) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::DICT_TYPE as *const _ as *const pyre_object::PyType);
            let len = ctx.record_op_with_descr(OpCode::GetfieldRawI, &[value], crate::descr::dict_len_descr());
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[len, zero]));
        }
        // listobject.py:423 W_ListObject.length() → strategy.length()
        // All list strategies determine truth by length, same as len() fast path.
        if pyre_object::is_list(concrete_val) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::LIST_TYPE as *const _ as *const pyre_object::PyType);
            let len_descr = if pyre_object::w_list_uses_object_storage(concrete_val) {
                frame.guard_list_strategy(ctx, value, 0);
                crate::descr::list_items_len_descr()
            } else if pyre_object::w_list_uses_int_storage(concrete_val) {
                frame.guard_list_strategy(ctx, value, 1);
                crate::descr::list_int_items_len_descr()
            } else if pyre_object::w_list_uses_float_storage(concrete_val) {
                frame.guard_list_strategy(ctx, value, 2);
                crate::descr::list_float_items_len_descr()
            } else {
                return None; // unknown strategy → residual
            };
            let len = ctx.record_op_with_descr(OpCode::GetfieldRawI, &[value], len_descr);
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[len, zero]));
        }
        // tupleobject.py: tuple truth → guard_class + getfield_raw(items_len) → int_ne(0)
        if pyre_object::is_tuple(concrete_val) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::TUPLE_TYPE as *const _ as *const pyre_object::PyType);
            let len = ctx.record_op_with_descr(OpCode::GetfieldRawI, &[value], crate::descr::tuple_items_len_descr());
            let zero = ctx.const_int(0);
            return Some(ctx.record_op(OpCode::IntNe, &[len, zero]));
        }
    }

    None
}
/// Trace list.append: guard_class → guard_strategy → capacity check →
/// unbox value (if typed strategy) → store at end → update len.
///
/// RPython jtransform list.append oopspec:
///   do_resizable_list_append → getfield(items) → check len vs capacity
///   → setarrayitem_gc → setfield(length, len+1)
///
/// strategy_id: 0=object, 1=int, 2=float.
/// is_inline: whether list uses inline storage (heap_cap == 0).
#[inline]
pub fn generated_list_append_by_strategy(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    list: majit_ir::OpRef,
    value: majit_ir::OpRef,
    concrete_len: usize,
    strategy_id: i64,
    is_inline: bool,
) {
    use majit_ir::OpCode;

    frame.guard_class(ctx, list, &pyre_object::pyobject::LIST_TYPE as *const _ as *const pyre_object::PyType);
    frame.guard_list_strategy(ctx, list, strategy_id);

    let (len_descr, ptr_descr, heap_cap_descr) = match strategy_id {
        0 => (crate::descr::list_items_len_descr(), crate::descr::list_items_ptr_descr(), crate::descr::list_items_heap_cap_descr()),
        1 => (crate::descr::list_int_items_len_descr(), crate::descr::list_int_items_ptr_descr(), crate::descr::list_int_items_heap_cap_descr()),
        2 => (crate::descr::list_float_items_len_descr(), crate::descr::list_float_items_ptr_descr(), crate::descr::list_float_items_heap_cap_descr()),
        _ => unreachable!(),
    };

    // Capacity guard: inline storage → guard heap_cap==0, else guard len==concrete_len.
    if is_inline {
        let heap_cap = ctx.record_op_with_descr(OpCode::GetfieldGcI, &[list], heap_cap_descr);
        frame.implement_guard_value(ctx, heap_cap, 0);
    } else {
        let len = crate::state::trace_arraylen_gc(ctx, list, len_descr.clone());
        frame.implement_guard_value(ctx, len, concrete_len as i64);
    }

    let items_ptr = crate::state::opimpl_getfield_gc_i(ctx, list, ptr_descr);
    let index = ctx.const_int(concrete_len as i64);

    // Write value: object strategy stores directly, int/float unbox first.
    match strategy_id {
        0 => crate::state::trace_raw_array_setitem_value(ctx, items_ptr, index, value),
        1 => {
            let raw = if frame.value_type(value) == majit_ir::Type::Int {
                value
            } else {
                let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
                crate::state::trace_unbox_int_with_resume(frame, ctx, value, int_type_addr)
            };
            crate::state::trace_raw_int_array_setitem_value(ctx, items_ptr, index, raw);
        }
        2 => {
            let raw = if frame.value_type(value) == majit_ir::Type::Float {
                value
            } else {
                let float_type_addr = &pyre_object::pyobject::FLOAT_TYPE as *const _ as i64;
                crate::state::trace_unbox_float_with_resume(frame, ctx, value, float_type_addr)
            };
            crate::state::trace_raw_float_array_setitem_value(ctx, items_ptr, index, raw);
        }
        _ => unreachable!(),
    }

    // Update length: setfield_gc(list, len+1, len_descr).
    let new_len = ctx.const_int((concrete_len + 1) as i64);
    let len_descr_idx = len_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[list, new_len], len_descr);
    ctx.heap_cache_mut().setfield_cached(list, len_descr_idx, new_len);
}

/// Trace len() for known container types.
///
/// RPython jitcode parity: guard_class → getfield(length/len) for each type.
/// Returns None if type not handled → caller falls back to residual call.
#[inline]
pub fn generated_direct_len_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    concrete_value: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    if concrete_value.is_null() {
        return None;
    }

    unsafe {
        if pyre_object::is_str(concrete_value) {
            frame.guard_class(ctx, value, &pyre_object::STR_TYPE as *const _ as *const pyre_object::PyType);
            let len = crate::state::trace_arraylen_gc(ctx, value, crate::descr::str_len_descr());
            frame.remember_value_type(len, majit_ir::Type::Int);
            return Some(len);
        }
        if pyre_object::is_dict(concrete_value) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::DICT_TYPE as *const _ as *const pyre_object::PyType);
            let len = crate::state::trace_arraylen_gc(ctx, value, crate::descr::dict_len_descr());
            frame.remember_value_type(len, majit_ir::Type::Int);
            return Some(len);
        }
        if pyre_object::is_list(concrete_value) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::LIST_TYPE as *const _ as *const pyre_object::PyType);
            let len_descr = if pyre_object::w_list_uses_object_storage(concrete_value) {
                frame.guard_list_strategy(ctx, value, 0);
                crate::descr::list_items_len_descr()
            } else if pyre_object::w_list_uses_int_storage(concrete_value) {
                frame.guard_list_strategy(ctx, value, 1);
                crate::descr::list_int_items_len_descr()
            } else if pyre_object::w_list_uses_float_storage(concrete_value) {
                frame.guard_list_strategy(ctx, value, 2);
                crate::descr::list_float_items_len_descr()
            } else {
                return None; // unknown list strategy → residual
            };
            let len = crate::state::trace_arraylen_gc(ctx, value, len_descr);
            frame.remember_value_type(len, majit_ir::Type::Int);
            return Some(len);
        }
        if pyre_object::is_tuple(concrete_value) {
            frame.guard_class(ctx, value, &pyre_object::pyobject::TUPLE_TYPE as *const _ as *const pyre_object::PyType);
            let len = crate::state::trace_arraylen_gc(ctx, value, crate::descr::tuple_items_len_descr());
            frame.remember_value_type(len, majit_ir::Type::Int);
            return Some(len);
        }
    }

    None
}
/// Trace abs() for int values: guard_class + getfield → guard(!=MIN) → branchless abs.
///
/// RPython jitcode: guard_class + getfield_gc_i(intval) → int_abs sequence.
/// Returns None if not handled → caller falls back to residual call.
#[inline]
pub fn generated_direct_abs_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    concrete_value: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    if concrete_value.is_null() {
        return None;
    }

    unsafe {
        if pyre_object::is_int(concrete_value) {
            let concrete_int = pyre_object::w_int_get_value(concrete_value);
            if concrete_int == i64::MIN {
                return None; // overflow → residual
            }
            let int_value = frame.trace_guarded_int_payload(ctx, value);
            let min_value = ctx.const_int(i64::MIN);
            let is_min = ctx.record_op(OpCode::IntEq, &[int_value, min_value]);
            frame.generate_guard(ctx, OpCode::GuardFalse, &[is_min]);
            // branchless abs: (x ^ sign) - sign
            let shift = ctx.const_int((i64::BITS - 1) as i64);
            let sign = ctx.record_op(OpCode::IntRshift, &[int_value, shift]);
            let xor = ctx.record_op(OpCode::IntXor, &[int_value, sign]);
            let abs_value = ctx.record_op(OpCode::IntSub, &[xor, sign]);
            return Some(crate::state::wrapint(ctx, abs_value));
        }
    }

    None
}

/// Trace type() for known object: guard_class → const_ptr(type_object).
///
/// RPython parity: pypy/objspace/std/objspace.py:400
///   def type(self, w_obj):
///       jit.promote(w_obj.__class__)
///       return w_obj.getclass(self)
///
/// RPython objspace.py:400: jit.promote(w_obj.__class__) evaluates
/// __class__ (via getfield chain in mapdict) then GUARD_VALUE on the CLASS.
///
/// pyre's ob_type is NOT unique per Python class (INSTANCE_TYPE is
/// shared by all user instances, TYPE_TYPE by all type objects).
/// Guard strategy matching RPython's promote(__class__):
///   - builtin: guard_class(ob_type) — ob_type IS unique for builtins
///   - instance (no override): guard_class(INSTANCE_TYPE) + getfield(w_type) + guard_value
///   - instance (__class__ override): guard_class(INSTANCE_TYPE)
///     + CallLoopinvariantR(jit_read_class) + guard_value on CLASS
///   - type (custom metaclass): guard_class(TYPE_TYPE)
///     + CallLoopinvariantR(jit_read_class) + guard_value on METACLASS
///   - builtin (__class__ override): guard_class(ob_type)
///     + CallLoopinvariantR(jit_read_class) + guard_value on CLASS
///
/// Returns None if not handled → caller falls back to residual call.
#[inline]
pub fn generated_direct_type_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    concrete_value: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    if concrete_value.is_null() {
        return None;
    }

    let concrete_type_obj = pyre_interpreter::typedef::r#type(concrete_value)?;

    unsafe {
        if pyre_object::is_instance(concrete_value) {
            // User instance: ob_type is shared INSTANCE_TYPE.
            // Check if __class__ override exists (e.g. obj.__class__ = Other).
            let w_type = pyre_object::w_instance_get_type(concrete_value);
            if std::ptr::eq(w_type, concrete_type_obj) {
                // No __class__ override: read .w_type field + guard_value.
                // RPython: jit.promote(w_obj.__class__)
                frame.guard_class(
                    ctx,
                    value,
                    &pyre_object::pyobject::INSTANCE_TYPE as *const _ as *const pyre_object::PyType,
                );
                let w_type_descr = crate::descr::instance_w_type_descr();
                let w_type_opref = ctx.record_op_with_descr(
                    majit_ir::OpCode::GetfieldGcR,
                    &[value],
                    w_type_descr,
                );
                frame.implement_guard_value(ctx, w_type_opref, concrete_type_obj as i64);
            } else {
                // __class__ override: .w_type differs from typedef::type().
                // RPython: jit.promote(w_obj.__class__) = getfield(ob_type) + GUARD_VALUE.
                // pyre: ATTR_TABLE is not getfield-accessible; use
                // elidable call (closest to getfield semantics) + GUARD_VALUE.
                frame.guard_class(
                    ctx,
                    value,
                    &pyre_object::pyobject::INSTANCE_TYPE as *const _ as *const pyre_object::PyType,
                );
                let class_opref = ctx.call_elidable_ref_typed(
                    crate::state::jit_read_class as *const (),
                    &[value],
                    &[majit_ir::Type::Ref],
                );
                frame.implement_guard_value(ctx, class_opref, concrete_type_obj as i64);
            }
            return Some(ctx.const_ref(concrete_type_obj as i64));
        }

        if pyre_object::typeobject::is_type(concrete_value) {
            // RPython objspace.py:401: jit.promote(w_obj.__class__)
            // For type objects, __class__ is the metaclass.
            // guard_class(TYPE_TYPE) + promote metaclass via CallLoopinvariantR.
            frame.guard_class(
                ctx,
                value,
                &pyre_object::pyobject::TYPE_TYPE as *const _ as *const pyre_object::PyType,
            );
            let default_metaclass = pyre_interpreter::typedef::gettypefor(
                &pyre_object::pyobject::TYPE_TYPE as *const _ as *const pyre_object::PyType,
            );
            let has_custom_metaclass = default_metaclass
                .map_or(true, |dm| !std::ptr::eq(dm, concrete_type_obj));
            if has_custom_metaclass {
                // Custom metaclass: elidable read + GUARD_VALUE on the CLASS.
                // RPython: getfield(metaclass) + promote. pyre: elidable call.
                let class_opref = ctx.call_elidable_ref_typed(
                    crate::state::jit_read_class as *const (),
                    &[value],
                    &[majit_ir::Type::Ref],
                );
                frame.implement_guard_value(ctx, class_opref, concrete_type_obj as i64);
            }
            // Default metaclass (type): guard_class(TYPE_TYPE) is sufficient.
            return Some(ctx.const_ref(concrete_type_obj as i64));
        }

        // Builtin types: ob_type IS normally unique per Python class.
        // __class__ override via ATTR_TABLE (e.g. int subclass) can differ.
        let concrete_obj_type = (*concrete_value).ob_type;
        let default_type = pyre_interpreter::typedef::gettypefor(concrete_obj_type);
        if default_type.map_or(true, |dt| !std::ptr::eq(dt, concrete_type_obj)) {
            // __class__ override: guard_class(ob_type) + elidable read + GUARD_VALUE.
            // RPython: getfield(ob_type) + promote. pyre: elidable call.
            frame.guard_class(ctx, value, concrete_obj_type);
            let class_opref = ctx.call_elidable_ref_typed(
                crate::state::jit_read_class as *const (),
                &[value],
                &[majit_ir::Type::Ref],
            );
            frame.implement_guard_value(ctx, class_opref, concrete_type_obj as i64);
        } else {
            frame.guard_class(ctx, value, concrete_obj_type);
        }
        Some(ctx.const_ref(concrete_type_obj as i64))
    }
}

/// Trace isinstance(obj, cls): guard obj class + implement_guard_value(cls) → const bool.
///
/// RPython parity: isinstance uses space.type(w_obj) internally, which
/// calls jit.promote(w_obj.__class__). Same guard strategy as type():
///   - builtin: guard_class (ob_type is unique)
///   - instance: guard_class(INSTANCE_TYPE) + getfield(w_type) + guard_value
///   - __class__ override: guard_class + elidable read + guard_value
/// cls is always promoted via implement_guard_value.
///
/// Returns None if not handled → caller falls back to residual call.
#[inline]
pub fn generated_direct_isinstance_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    cls: majit_ir::OpRef,
    concrete_obj: pyre_object::PyObjectRef,
    concrete_cls: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    if concrete_obj.is_null() || concrete_cls.is_null() {
        return None;
    }

    let concrete_result = pyre_interpreter::builtins::call_isinstance(concrete_obj, concrete_cls)?;

    unsafe {
        if pyre_object::is_instance(concrete_obj) {
            let w_type = pyre_object::w_instance_get_type(concrete_obj);
            let actual_type = pyre_interpreter::typedef::r#type(concrete_obj);
            frame.guard_class(
                ctx,
                obj,
                &pyre_object::pyobject::INSTANCE_TYPE as *const _ as *const pyre_object::PyType,
            );
            if actual_type.map_or(true, |at| std::ptr::eq(at, w_type)) {
                // No __class__ override: getfield(w_type) + guard_value.
                let w_type_descr = crate::descr::instance_w_type_descr();
                let w_type_opref = ctx.record_op_with_descr(
                    majit_ir::OpCode::GetfieldGcR,
                    &[obj],
                    w_type_descr,
                );
                frame.implement_guard_value(ctx, w_type_opref, w_type as i64);
            } else {
                // __class__ override: elidable read + GUARD_VALUE on CLASS.
                let class_opref = ctx.call_elidable_ref_typed(
                    crate::state::jit_read_class as *const (),
                    &[obj],
                    &[majit_ir::Type::Ref],
                );
                frame.implement_guard_value(
                    ctx,
                    class_opref,
                    actual_type.unwrap() as i64,
                );
            }
        } else if pyre_object::typeobject::is_type(concrete_obj) {
            frame.guard_class(
                ctx,
                obj,
                &pyre_object::pyobject::TYPE_TYPE as *const _ as *const pyre_object::PyType,
            );
            let default_metaclass = pyre_interpreter::typedef::gettypefor(
                &pyre_object::pyobject::TYPE_TYPE as *const _ as *const pyre_object::PyType,
            );
            let actual_type = pyre_interpreter::typedef::r#type(concrete_obj);
            let has_custom_metaclass = actual_type.map_or(true, |at| {
                default_metaclass.map_or(true, |dm| !std::ptr::eq(dm, at))
            });
            if has_custom_metaclass {
                // Custom metaclass: elidable read + GUARD_VALUE on CLASS.
                let class_opref = ctx.call_elidable_ref_typed(
                    crate::state::jit_read_class as *const (),
                    &[obj],
                    &[majit_ir::Type::Ref],
                );
                frame.implement_guard_value(
                    ctx,
                    class_opref,
                    actual_type.unwrap() as i64,
                );
            }
        } else {
            let concrete_obj_type = (*concrete_obj).ob_type;
            let default_type = pyre_interpreter::typedef::gettypefor(concrete_obj_type);
            let actual_type = pyre_interpreter::typedef::r#type(concrete_obj);
            let has_class_override = actual_type.map_or(false, |at| {
                default_type.map_or(true, |dt| !std::ptr::eq(dt, at))
            });
            frame.guard_class(ctx, obj, concrete_obj_type);
            if has_class_override {
                // __class__ override: elidable read + GUARD_VALUE on CLASS.
                let class_opref = ctx.call_elidable_ref_typed(
                    crate::state::jit_read_class as *const (),
                    &[obj],
                    &[majit_ir::Type::Ref],
                );
                frame.implement_guard_value(
                    ctx,
                    class_opref,
                    actual_type.unwrap() as i64,
                );
            }
        }

        frame.implement_guard_value(ctx, cls, concrete_cls as i64);
        Some(ctx.const_ref(pyre_object::w_bool_from(concrete_result) as i64))
    }
}

/// Trace min()/max() for two ints: branchless int selection.
///
/// RPython jitcode: guard_class × 2 + getfield_gc_i × 2 + int_lt + branchless select + box.
/// Returns None if not handled → caller falls back to residual call.
#[inline]
pub fn generated_direct_minmax_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    choose_max: bool,
    concrete_a: pyre_object::PyObjectRef,
    concrete_b: pyre_object::PyObjectRef,
) -> Option<majit_ir::OpRef> {
    use majit_ir::OpCode;

    if concrete_a.is_null() || concrete_b.is_null() {
        return None;
    }

    unsafe {
        if pyre_object::is_int(concrete_a) && pyre_object::is_int(concrete_b) {
            let lhs_val = pyre_object::w_int_get_value(concrete_a);
            let rhs_val = pyre_object::w_int_get_value(concrete_b);
            let concrete_result = if choose_max { lhs_val.max(rhs_val) } else { lhs_val.min(rhs_val) };
            let concrete_obj = if choose_max {
                if lhs_val >= rhs_val { concrete_a } else { concrete_b }
            } else if lhs_val <= rhs_val {
                concrete_a
            } else {
                concrete_b
            };
            if pyre_object::w_int_new(concrete_result) != concrete_obj {
                return None; // identity mismatch → residual
            }
            let lhs = frame.trace_guarded_int_payload(ctx, a);
            let rhs = frame.trace_guarded_int_payload(ctx, b);
            // branchless min/max: mask = 0 - (lhs < rhs)
            let cmp = ctx.record_op(OpCode::IntLt, &[lhs, rhs]);
            let zero = ctx.const_int(0);
            let mask = ctx.record_op(OpCode::IntSub, &[zero, cmp]);
            let xor = ctx.record_op(OpCode::IntXor, &[lhs, rhs]);
            let select_bits = ctx.record_op(OpCode::IntAnd, &[xor, mask]);
            let selected = if choose_max {
                ctx.record_op(OpCode::IntXor, &[lhs, select_bits])
            } else {
                ctx.record_op(OpCode::IntXor, &[rhs, select_bits])
            };
            return Some(crate::state::wrapint(ctx, selected));
        }
    }

    None
}
/// Trace tuple[int_key] getitem: guard_class → guard_index → arraylen →
/// guard_len → items_ptr → raw array getitem.
///
/// RPython jtransform do_fixed_list_getitem parity:
///   guard_class + check_neg_index + getarrayitem_gc_r.
///
/// Handles both positive and negative concrete_key.
/// Returns None if not a recognized tuple getitem.
#[inline]
pub fn generated_tuple_getitem(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    key: majit_ir::OpRef,
    concrete_key: i64,
    concrete_len: usize,
) -> majit_ir::OpRef {
    let expected_type = &pyre_object::pyobject::TUPLE_TYPE as *const _ as *const pyre_object::PyType;
    let items_ptr_descr = crate::descr::tuple_items_ptr_descr();
    let items_len_descr = crate::descr::tuple_items_len_descr();

    frame.guard_class(ctx, obj, expected_type);
    frame.guard_int_like_value(ctx, key, concrete_key);
    let len = crate::state::trace_arraylen_gc(ctx, obj, items_len_descr);

    let index = if concrete_key >= 0 {
        frame.guard_len_gt_index(ctx, len, concrete_key as usize);
        ctx.const_int(concrete_key)
    } else {
        frame.guard_len_eq(ctx, len, concrete_len);
        let normalized = (concrete_len as i64 + concrete_key) as usize;
        ctx.const_int(normalized as i64)
    };

    let items_ptr = crate::state::opimpl_getfield_gc_i(ctx, obj, items_ptr_descr);
    crate::state::trace_raw_array_getitem_value(ctx, items_ptr, index)
}

/// Trace list/tuple index normalization: unbox key → bounds check guards.
///
/// RPython pyjitpl.py:841 opimpl_check_resizable_neg_index:
///   INT_LT(index, 0) → implement_guard_value → if negative: getfield(length) + INT_ADD.
///
/// Returns the final index OpRef (positive, bounds-checked).
#[inline]
pub fn generated_dynamic_list_index(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    key: majit_ir::OpRef,
    len: majit_ir::OpRef,
    concrete_key: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;

    let int_type_addr = &pyre_object::pyobject::INT_TYPE as *const _ as i64;
    let raw_index = if frame.value_type(key) == majit_ir::Type::Int {
        key
    } else {
        crate::state::trace_unbox_int_with_resume(frame, ctx, key, int_type_addr)
    };
    let zero = ctx.const_int(0);
    if concrete_key >= 0 {
        let nonnegative = ctx.record_op(OpCode::IntGe, &[raw_index, zero]);
        frame.generate_guard(ctx, OpCode::GuardTrue, &[nonnegative]);
        let in_bounds = ctx.record_op(OpCode::IntLt, &[raw_index, len]);
        frame.generate_guard(ctx, OpCode::GuardTrue, &[in_bounds]);
        raw_index
    } else {
        let negative = ctx.record_op(OpCode::IntLt, &[raw_index, zero]);
        frame.generate_guard(ctx, OpCode::GuardTrue, &[negative]);
        let normalized = ctx.record_op(OpCode::IntAddOvf, &[len, raw_index]);
        frame.generate_guard(ctx, OpCode::GuardNoOverflow, &[]);
        let in_bounds = ctx.record_op(OpCode::IntGe, &[normalized, zero]);
        frame.generate_guard(ctx, OpCode::GuardTrue, &[in_bounds]);
        normalized
    }
}

/// Trace range iterator next: read fields → step sign guard → continues guard
/// → advance current → setfield.
///
/// RPython jitcode for range.__next__:
///   getfield(current) → getfield(stop) → getfield(step) → int_gt(step,0) →
///   guard_true/false → int_lt/gt(current,stop) → guard_true/false →
///   int_add_ovf(current,step) → guard_no_overflow → setfield(current, next)
///
/// Returns (current_opref, concrete_current) or None if should fall back.
#[inline]
pub fn generated_iter_next_value(
    frame: &mut crate::state::MIFrame,
    ctx: &mut majit_metainterp::TraceCtx,
    iter: majit_ir::OpRef,
    concrete_continues: bool,
    concrete_step: i64,
    concrete_current: i64,
) -> Option<(majit_ir::OpRef, i64)> {
    use majit_ir::OpCode;

    let concrete_step_positive = concrete_step > 0;

    // Overflow check: if current + step overflows, fall back.
    if concrete_continues && concrete_current.checked_add(concrete_step).is_none() {
        return None;
    }

    frame.guard_range_iter(ctx, iter);

    let current = crate::state::opimpl_getfield_gc_i(ctx, iter, crate::descr::range_iter_current_descr());
    let stop = crate::state::opimpl_getfield_gc_i(ctx, iter, crate::descr::range_iter_stop_descr());
    let step = crate::state::opimpl_getfield_gc_i(ctx, iter, crate::descr::range_iter_step_descr());
    let zero = ctx.const_int(0);

    // pyjitpl.py:1877 opimpl_goto_if_not: boolean guards.
    let step_positive = ctx.record_op(OpCode::IntGt, &[step, zero]);
    if concrete_step_positive {
        frame.generate_guard(ctx, OpCode::GuardTrue, &[step_positive]);
    } else {
        frame.generate_guard(ctx, OpCode::GuardFalse, &[step_positive]);
    }

    let continues = if concrete_step_positive {
        ctx.record_op(OpCode::IntLt, &[current, stop])
    } else {
        ctx.record_op(OpCode::IntGt, &[current, stop])
    };
    if concrete_continues {
        frame.generate_guard(ctx, OpCode::GuardTrue, &[continues]);
    } else {
        frame.generate_guard(ctx, OpCode::GuardFalse, &[continues]);
    }

    if !concrete_continues {
        frame.remember_value_type(zero, majit_ir::Type::Int);
        return Some((zero, 0));
    }

    let next_current = ctx.record_op(OpCode::IntAddOvf, &[current, step]);
    frame.generate_guard(ctx, OpCode::GuardNoOverflow, &[]);
    let ri_descr = crate::descr::range_iter_current_descr();
    let ri_descr_idx = ri_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[iter, next_current], ri_descr);
    ctx.heap_cache_mut().setfield_cached(iter, ri_descr_idx, next_current);
    frame.remember_value_type(current, majit_ir::Type::Int);
    Some((current, concrete_current))
}
"#);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_from_graph_produces_function_table() {
        let parsed = crate::parse::parse_source(
            r#"
            fn add(a: i64, b: i64) -> i64 { a + b }
            fn sub(a: i64, b: i64) -> i64 { a - b }
        "#,
        );
        let program = crate::front::build_semantic_program(&parsed);
        let pipeline =
            crate::passes::analyze_program(&program, &crate::passes::PipelineConfig::default());
        let code = generate_from_graph(&pipeline);

        assert!(
            code.contains("GRAPH_FUNCTIONS"),
            "should contain GRAPH_FUNCTIONS table"
        );
        assert!(code.contains("add"), "should list 'add' function");
        assert!(code.contains("sub"), "should list 'sub' function");
        assert!(
            code.contains("graph pipeline"),
            "should have graph pipeline header"
        );
    }

    #[test]
    fn generate_from_pipeline_emits_canonical_header() {
        let mut pipeline = crate::passes::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: vec![crate::passes::PipelineOpcodeArm {
                selector: crate::OpcodeDispatchSelector::Path(crate::CallPath::from_segments([
                    "Instruction",
                    "Add",
                ])),
                flattened: None,
            }],
            jitcodes: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        pipeline.functions.push(crate::passes::PipelineResult {
            name: "add".into(),
            original_blocks: 1,
            annotations_count: 0,
            concrete_types_count: 0,
            vable_rewrites: 0,
            calls_classified: 0,
            transform_notes: Vec::new(),
            flattened: crate::passes::SSARepr {
                name: "add".into(),
                insns: Vec::new(),
                num_values: 0,
                num_blocks: 0,
                value_kinds: std::collections::HashMap::new(),
            },
        });
        let code = generate_from_pipeline(&pipeline);
        assert!(code.contains("canonical pipeline"));
        assert!(code.contains("GRAPH_FUNCTIONS"));
        assert!(code.contains("CANONICAL_TRACE_PATTERNS"));
    }

    #[test]
    fn generate_dispatch_tables_emits_all_tables() {
        let pipeline = crate::passes::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: Vec::new(),
            jitcodes: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        let code = generate_from_pipeline(&pipeline);
        // Int binary dispatch table
        assert!(
            code.contains("INT_BINOP_TABLE"),
            "should emit INT_BINOP_TABLE"
        );
        assert!(
            code.contains("int_binop_lookup"),
            "should emit int_binop_lookup"
        );
        // Float binary dispatch table
        assert!(
            code.contains("FLOAT_BINOP_TABLE"),
            "should emit FLOAT_BINOP_TABLE"
        );
        assert!(
            code.contains("float_binop_lookup"),
            "should emit float_binop_lookup"
        );
        // Comparison dispatch table
        assert!(code.contains("COMPARE_TABLE"), "should emit COMPARE_TABLE");
        assert!(
            code.contains("int_compare_lookup"),
            "should emit int_compare_lookup"
        );
        assert!(
            code.contains("float_compare_lookup"),
            "should emit float_compare_lookup"
        );
        // Concrete computation helpers
        assert!(
            code.contains("concrete_float_binop"),
            "should emit concrete_float_binop"
        );
        assert!(
            code.contains("concrete_int_binop"),
            "should emit concrete_int_binop"
        );
    }
}
