//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by pyre-mjit's build.rs via include!().
//!
//! Each recognized TracePattern produces a tracing function that emits
//! the equivalent IR ops. Unrecognized patterns fall back to residual calls.

/// Generate tracing code from graph pipeline results.
///
/// Test-only summary emitter for raw graph pipeline output. Active consumers
/// should use `generate_from_pipeline()`, which is the canonical translator
/// entry point.
#[cfg(test)]
pub fn generate_from_graph(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter graph pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));

    // Function summary
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");

    out
}

/// Generate tracing code directly from the canonical pipeline result.
///
/// This is the RPython-leaning entry point: graph/pipeline output is the only
/// source-of-truth used for emission.
pub fn generate_from_pipeline(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter canonical pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Canonical graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));
    out.push('\n');

    generate_graph_function_summary(&mut out, result);
    generate_canonical_dispatch_table(&mut out, result);
    generate_dispatch_tables(&mut out);
    generate_concrete_computation(&mut out);
    generate_trace_functions(&mut out);

    let flattened_count = result
        .opcode_dispatch
        .iter()
        .filter(|a| a.flattened.is_some())
        .count();
    out.push_str(&format!(
        "// Canonical analysis summary: {}/{} flattened\n",
        flattened_count,
        result.opcode_dispatch.len(),
    ));

    out
}

/// Recognition report for pipeline analysis diagnostic.
///
/// Quantifies how much of the input source the pipeline recognizes,
/// surfacing Unknown ops and unresolved calls per opcode arm.
#[derive(Debug, Clone)]
pub struct RecognitionReport {
    pub total_opcodes: usize,
    pub flattened: usize,
    pub total_flat_ops: usize,
    pub unknown_ops: usize,
    pub unresolved_calls: usize,
    pub per_opcode: Vec<OpcodeRecognition>,
}

#[derive(Debug, Clone)]
pub struct OpcodeRecognition {
    pub selector: String,
    pub flat_ops: usize,
    pub unknowns: usize,
    pub unresolved: usize,
}

/// Analyze pipeline results to produce a recognition report.
pub fn recognition_report(result: &crate::passes::ProgramPipelineResult) -> RecognitionReport {
    use crate::model::OpKind;
    use crate::passes::flatten::FlatOp;

    let mut report = RecognitionReport {
        total_opcodes: result.opcode_dispatch.len(),
        flattened: 0,
        total_flat_ops: 0,
        unknown_ops: 0,
        unresolved_calls: 0,
        per_opcode: Vec::new(),
    };

    for arm in &result.opcode_dispatch {
        let selector = arm.selector.canonical_key();
        let Some(ssa) = &arm.flattened else {
            report.per_opcode.push(OpcodeRecognition {
                selector,
                flat_ops: 0,
                unknowns: 0,
                unresolved: 0,
            });
            continue;
        };

        report.flattened += 1;
        let mut unknowns = 0;
        let mut unresolved = 0;
        let mut flat_ops = 0;

        for insn in &ssa.insns {
            if let FlatOp::Op(op) = insn {
                flat_ops += 1;
                match &op.kind {
                    OpKind::Unknown { .. } => unknowns += 1,
                    OpKind::Call { target, .. } => {
                        if matches!(target, crate::model::CallTarget::UnsupportedExpr) {
                            unresolved += 1;
                        }
                    }
                    _ => {}
                }
            }
        }

        report.total_flat_ops += flat_ops;
        report.unknown_ops += unknowns;
        report.unresolved_calls += unresolved;
        report.per_opcode.push(OpcodeRecognition {
            selector,
            flat_ops,
            unknowns,
            unresolved,
        });
    }

    report
}

fn generate_graph_function_summary(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");
}

fn generate_canonical_dispatch_table(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Canonical analysis summary: opcode → flattened op count.\n");
    out.push_str("pub const CANONICAL_TRACE_PATTERNS: &[(&str, &str)] = &[\n");
    for arm in &result.opcode_dispatch {
        let status = match &arm.flattened {
            Some(f) => format!("Flattened({}ops)", f.insns.len()),
            None => "Unflattened".to_string(),
        };
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            arm.selector.canonical_key().replace('"', "\\\""),
            status.replace('"', "\\\""),
        ));
    }
    out.push_str("];\n\n");
}

fn generate_dispatch_tables(out: &mut String) {
    // ── Operator → OpCode dispatch tables ──
    // Generated from BinaryOperator/ComparisonOperator → majit_ir::OpCode mapping.
    // Consumed by trace_opcode.rs to replace manual match arms.

    // Int binary: BinaryOperator → (OpCode, has_overflow, needs_concrete_check)
    //
    // needs_concrete_check: FloorDiv/Mod need non-negative operands,
    // Lshift/Rshift need shift-in-range validation at concrete level.
    out.push_str(r#"
/// Int binary operator dispatch: `(base_op, inplace_op, opcode, has_overflow, needs_concrete_check)`.
pub const INT_BINOP_TABLE: &[(
    BinaryOperator, BinaryOperator, majit_ir::OpCode, bool, bool,
)] = &[
    (BinaryOperator::Add, BinaryOperator::InplaceAdd, majit_ir::OpCode::IntAddOvf, true, false),
    (BinaryOperator::Subtract, BinaryOperator::InplaceSubtract, majit_ir::OpCode::IntSubOvf, true, false),
    (BinaryOperator::Multiply, BinaryOperator::InplaceMultiply, majit_ir::OpCode::IntMulOvf, true, false),
    (BinaryOperator::FloorDivide, BinaryOperator::InplaceFloorDivide, majit_ir::OpCode::IntFloorDiv, false, true),
    (BinaryOperator::Remainder, BinaryOperator::InplaceRemainder, majit_ir::OpCode::IntMod, false, true),
    (BinaryOperator::And, BinaryOperator::InplaceAnd, majit_ir::OpCode::IntAnd, false, false),
    (BinaryOperator::Or, BinaryOperator::InplaceOr, majit_ir::OpCode::IntOr, false, false),
    (BinaryOperator::Xor, BinaryOperator::InplaceXor, majit_ir::OpCode::IntXor, false, false),
    (BinaryOperator::Lshift, BinaryOperator::InplaceLshift, majit_ir::OpCode::IntLshift, false, true),
    (BinaryOperator::Rshift, BinaryOperator::InplaceRshift, majit_ir::OpCode::IntRshift, false, true),
];

/// Look up int binary operator dispatch entry.
pub fn int_binop_lookup(op: BinaryOperator) -> Option<(majit_ir::OpCode, bool, bool)> {
    INT_BINOP_TABLE
        .iter()
        .find(|(base, inplace, _, _, _)| *base == op || *inplace == op)
        .map(|(_, _, opcode, ovf, concrete)| (*opcode, *ovf, *concrete))
}

/// Float binary operator dispatch: `(base_op, inplace_op, opcode)`.
///
/// resoperation.py:959-962: only FLOAT_ADD, FLOAT_SUB, FLOAT_MUL, FLOAT_TRUEDIV.
/// lloperation.py:260-261: no float_floordiv, no float_mod, no float_pow.
/// FloorDivide → _divmod_w() residual call (floatobject.py:508).
/// Remainder → math_fmod residual call (floatobject.py:520).
/// Power → ll_math_pow residual call (ll_math.py:260).
pub const FLOAT_BINOP_TABLE: &[(
    BinaryOperator, BinaryOperator, majit_ir::OpCode,
)] = &[
    (BinaryOperator::Add, BinaryOperator::InplaceAdd, majit_ir::OpCode::FloatAdd),
    (BinaryOperator::Subtract, BinaryOperator::InplaceSubtract, majit_ir::OpCode::FloatSub),
    (BinaryOperator::Multiply, BinaryOperator::InplaceMultiply, majit_ir::OpCode::FloatMul),
    (BinaryOperator::TrueDivide, BinaryOperator::InplaceTrueDivide, majit_ir::OpCode::FloatTrueDiv),
];

/// Look up float binary operator dispatch entry.
/// Returns None for FloorDivide, Remainder, Power and unsupported ops.
pub fn float_binop_lookup(op: BinaryOperator) -> Option<majit_ir::OpCode> {
    FLOAT_BINOP_TABLE
        .iter()
        .find(|(base, inplace, _)| *base == op || *inplace == op)
        .map(|(_, _, opcode)| *opcode)
}

/// Comparison operator dispatch: `(comp_op, int_opcode, float_opcode)`.
pub const COMPARE_TABLE: &[(
    ComparisonOperator, majit_ir::OpCode, majit_ir::OpCode,
)] = &[
    (ComparisonOperator::Less, majit_ir::OpCode::IntLt, majit_ir::OpCode::FloatLt),
    (ComparisonOperator::LessOrEqual, majit_ir::OpCode::IntLe, majit_ir::OpCode::FloatLe),
    (ComparisonOperator::Greater, majit_ir::OpCode::IntGt, majit_ir::OpCode::FloatGt),
    (ComparisonOperator::GreaterOrEqual, majit_ir::OpCode::IntGe, majit_ir::OpCode::FloatGe),
    (ComparisonOperator::Equal, majit_ir::OpCode::IntEq, majit_ir::OpCode::FloatEq),
    (ComparisonOperator::NotEqual, majit_ir::OpCode::IntNe, majit_ir::OpCode::FloatNe),
];

/// Look up comparison operator dispatch for int operands.
pub fn int_compare_lookup(op: ComparisonOperator) -> majit_ir::OpCode {
    COMPARE_TABLE
        .iter()
        .find(|(cmp, _, _)| *cmp == op)
        .map(|(_, int_op, _)| *int_op)
        .expect("all ComparisonOperator variants are covered")
}

/// Look up comparison operator dispatch for float operands.
pub fn float_compare_lookup(op: ComparisonOperator) -> majit_ir::OpCode {
    COMPARE_TABLE
        .iter()
        .find(|(cmp, _, _)| *cmp == op)
        .map(|(_, _, float_op)| *float_op)
        .expect("all ComparisonOperator variants are covered")
}
"#);
}

fn generate_concrete_computation(out: &mut String) {
    // ── Concrete computation helpers ──
    // Used by binary_value() to compute the concrete Python result during tracing.
    // Extracted from trace_opcode.rs match arms.

    out.push_str(
        r#"
/// Compute concrete float binary operation result.
/// Returns None for unsupported ops or division by zero.
///
/// floatobject.py: descr_add/sub/mul/truediv/floordiv/mod/pow
pub fn concrete_float_binop(op: BinaryOperator, lhs: f64, rhs: f64) -> Option<f64> {
    match op {
        BinaryOperator::Add | BinaryOperator::InplaceAdd => Some(lhs + rhs),
        BinaryOperator::Subtract | BinaryOperator::InplaceSubtract => Some(lhs - rhs),
        BinaryOperator::Multiply | BinaryOperator::InplaceMultiply => Some(lhs * rhs),
        BinaryOperator::TrueDivide | BinaryOperator::InplaceTrueDivide if rhs != 0.0 => {
            Some(lhs / rhs)
        }
        // floatobject.py:508: descr_floordiv → _divmod_w()[0]
        BinaryOperator::FloorDivide | BinaryOperator::InplaceFloorDivide if rhs != 0.0 => {
            Some(float_divmod_w(lhs, rhs).0)
        }
        // floatobject.py:520-540: descr_mod → fmod + sign correction + copysign
        BinaryOperator::Remainder | BinaryOperator::InplaceRemainder if rhs != 0.0 => {
            Some(float_mod(lhs, rhs))
        }
        // floatobject.py:561 descr_pow → _pow()
        BinaryOperator::Power | BinaryOperator::InplacePower => float_pow(lhs, rhs),
        _ => None,
    }
}

/// floatobject.py:520-540: float modulo with sign correction.
/// Uses fmod + denominator sign correction + copysign for zero remainder.
fn float_mod(x: f64, y: f64) -> f64 {
    let mut m = x % y; // C fmod semantics (same as Rust %)
    if m != 0.0 {
        // ensure the remainder has the same sign as the denominator
        if (y < 0.0) != (m < 0.0) {
            m += y;
        }
    } else {
        // the remainder is zero: ensure it has the same sign as the denominator
        m = f64::copysign(0.0, y);
    }
    m
}

/// floatobject.py:758-793: _divmod_w — returns (floordiv, mod).
fn float_divmod_w(x: f64, y: f64) -> (f64, f64) {
    let mut m = x % y; // fmod
    let mut div = (x - m) / y;
    if m != 0.0 {
        if (y < 0.0) != (m < 0.0) {
            m += y;
            div -= 1.0;
        }
    } else {
        m = m * m; // hide from optimizer
        if y < 0.0 { m = -m; }
    }
    // snap quotient to nearest integral value
    let floordiv = if div != 0.0 {
        let f = div.floor();
        if div - f > 0.5 { f + 1.0 } else { f }
    } else {
        let d = div * div; // hide from optimizer
        d * x / y
    };
    (floordiv, m)
}

/// floatobject.py:799-881: _pow with special-case handling.
/// Returns None for domain errors (negative base with fractional exponent).
fn float_pow(x: f64, y: f64) -> Option<f64> {
    if y == 2.0 {
        return Some(x * x);
    }
    if y == 0.0 {
        return Some(1.0);
    }
    if x.is_nan() {
        return Some(x);
    }
    if y.is_nan() {
        return Some(if x == 1.0 { 1.0 } else { y });
    }
    if y.is_infinite() {
        let ax = x.abs();
        if ax == 1.0 {
            return Some(1.0);
        } else if (y > 0.0) == (ax > 1.0) {
            return Some(f64::INFINITY);
        } else {
            return Some(0.0);
        }
    }
    if x.is_infinite() {
        let y_is_odd = y.abs() % 2.0 == 1.0;
        if y > 0.0 {
            return Some(if y_is_odd { x } else { x.abs() });
        } else {
            return Some(if y_is_odd { f64::copysign(0.0, x) } else { 0.0 });
        }
    }
    if x == 0.0 && y < 0.0 {
        return None; // ZeroDivisionError
    }
    let mut negate_result = false;
    let mut bx = x;
    if bx < 0.0 {
        if y.floor() != y {
            return None; // PowDomainError → ValueError
        }
        bx = -bx;
        negate_result = y.abs() % 2.0 == 1.0;
    }
    if bx == 1.0 {
        return Some(if negate_result { -1.0 } else { 1.0 });
    }
    let z = bx.powf(y);
    if z.is_infinite() || z.is_nan() {
        return None;
    }
    Some(if negate_result { -z } else { z })
}

/// Compute concrete int binary operation result.
/// Returns None for overflow, division by zero, or unsupported ops.
pub fn concrete_int_binop(op: BinaryOperator, lhs: i64, rhs: i64) -> Option<i64> {
    match op {
        BinaryOperator::Add | BinaryOperator::InplaceAdd => lhs.checked_add(rhs),
        BinaryOperator::Subtract | BinaryOperator::InplaceSubtract => lhs.checked_sub(rhs),
        BinaryOperator::Multiply | BinaryOperator::InplaceMultiply => lhs.checked_mul(rhs),
        BinaryOperator::Remainder | BinaryOperator::InplaceRemainder if rhs != 0 => {
            Some(((lhs % rhs) + rhs) % rhs)
        }
        BinaryOperator::FloorDivide | BinaryOperator::InplaceFloorDivide if rhs != 0 => {
            lhs.checked_div(rhs).map(|d| {
                if (lhs ^ rhs) < 0 && d * rhs != lhs { d - 1 } else { d }
            })
        }
        BinaryOperator::And | BinaryOperator::InplaceAnd => Some(lhs & rhs),
        BinaryOperator::Or | BinaryOperator::InplaceOr => Some(lhs | rhs),
        BinaryOperator::Xor | BinaryOperator::InplaceXor => Some(lhs ^ rhs),
        BinaryOperator::Lshift | BinaryOperator::InplaceLshift => {
            // intobject.py:205: negative shift → ValueError
            if rhs < 0 { return None; }
            let shift = rhs as u32;
            if shift >= 64 { return None; }
            let r = lhs.wrapping_shl(shift);
            if r.wrapping_shr(shift) != lhs { None } else { Some(r) }
        }
        BinaryOperator::Rshift | BinaryOperator::InplaceRshift => {
            // intobject.py:224: negative shift → ValueError("negative shift count")
            if rhs < 0 { return None; }
            let shift = rhs as u32;
            if shift >= 64 {
                Some(if lhs < 0 { -1 } else { 0 })
            } else {
                Some(lhs >> shift)
            }
        }
        _ => None,
    }
}
"#,
    );
}

fn generate_trace_functions(out: &mut String) {
    // ── Unbox/Box helpers ──
    // These are the core building blocks for tracing Python operations.
    // They mirror PyPy's RPython-generated unbox/box sequences.

    out.push_str(r#"
/// Unbox a Python int object: emit GuardClass + GetfieldGc(I|PureI).
///
/// Auto-generated equivalent of PyPy's int_unbox annotation.
/// Returns the raw i64 OpRef, with heapcache integration.
fn trace_getfield_gc_int_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // heapcache: check if this field was already read/written in this trace
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureI
    } else {
        OpCode::GetfieldGcI
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_int(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // GUARD_CLASS(box, cls): guard takes object box directly,
    // backend loads typeptr at offset 0 (llgraph/runner.py:1245).
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(int_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(int_type_addr as usize));
    }
    trace_getfield_gc_int_pureornot(ctx, obj, intval_descr)
}

/// Box a raw i64 into a Python int object.
///
/// Auto-generated equivalent of PyPy's int_box annotation.
/// The helper route preserves pyre's small-int cache instead of always
/// materializing a fresh heap object in the trace.
pub fn trace_box_int(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    _ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    _int_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;

    // Inline W_Int allocation so OptVirtualize can see the object shape
    // and fold later GetfieldRawI(intval) reads back to `value`.
    // RPython parity: NEW_WITH_VTABLE (not NEW) for classes with vtable.
    // jtransform.py:908-911 parity: typeptr setfield filtered in trace.
    // rewrite.py:479-484 GC rewriter emits vtable via fielddescr_vtable.
    let obj = ctx.record_op_with_descr(OpCode::NewWithVtable, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let intval_idx = intval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], intval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, intval_idx, value);
    obj
}

/// Emit an overflow-checked binary int operation.
///
/// Auto-generated: unbox a, unbox b, emit ovf op, guard no overflow, box result.
pub fn trace_int_binop_ovf(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    ctx.record_guard_typed_with_fail_args(
        OpCode::GuardNoOverflow, &[],
        vec![majit_ir::Type::Ref; fail_args.len()], fail_args,
    );
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a non-overflow binary int operation (bitwise ops, shifts).
pub fn trace_int_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a comparison between two Python ints.
pub fn trace_int_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}

/// Unbox a Python float object: emit GuardClass + GetfieldGc(F|PureF).
///
/// Returns the raw f64 OpRef.
fn trace_getfield_gc_float_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureF
    } else {
        OpCode::GetfieldGcF
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_float(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(float_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(float_type_addr as usize));
    }
    trace_getfield_gc_float_pureornot(ctx, obj, floatval_descr)
}

/// Box a raw f64 into a Python float object: emit New + SetfieldGc.
pub fn trace_box_float(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    _ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    _float_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // RPython parity: NEW_WITH_VTABLE + jtransform.py typeptr filter +
    // rewrite.py GC rewriter fielddescr_vtable emission.
    let obj = ctx.record_op_with_descr(OpCode::NewWithVtable, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let floatval_idx = floatval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], floatval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, floatval_idx, value);
    obj
}

/// Emit a binary float operation: unbox a, unbox b, emit float op, box result.
pub fn trace_float_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_float(ctx, result, size_descr, ob_type_descr, floatval_descr, float_type_addr)
}

/// Emit a comparison between two Python floats.
pub fn trace_float_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}
"#);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_from_graph_produces_function_table() {
        let parsed = crate::parse::parse_source(
            r#"
            fn add(a: i64, b: i64) -> i64 { a + b }
            fn sub(a: i64, b: i64) -> i64 { a - b }
        "#,
        );
        let program = crate::front::build_semantic_program(&parsed);
        let pipeline =
            crate::passes::analyze_program(&program, &crate::passes::PipelineConfig::default());
        let code = generate_from_graph(&pipeline);

        assert!(
            code.contains("GRAPH_FUNCTIONS"),
            "should contain GRAPH_FUNCTIONS table"
        );
        assert!(code.contains("add"), "should list 'add' function");
        assert!(code.contains("sub"), "should list 'sub' function");
        assert!(
            code.contains("graph pipeline"),
            "should have graph pipeline header"
        );
    }

    #[test]
    fn generate_from_pipeline_emits_canonical_header() {
        let mut pipeline = crate::passes::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: vec![crate::passes::PipelineOpcodeArm {
                selector: crate::OpcodeDispatchSelector::Path(crate::CallPath::from_segments([
                    "Instruction",
                    "Add",
                ])),
                flattened: None,
            }],
            jitcodes: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        pipeline.functions.push(crate::passes::PipelineResult {
            name: "add".into(),
            original_blocks: 1,
            annotations_count: 0,
            concrete_types_count: 0,
            vable_rewrites: 0,
            calls_classified: 0,
            transform_notes: Vec::new(),
            flattened: crate::passes::SSARepr {
                name: "add".into(),
                insns: Vec::new(),
                num_values: 0,
                num_blocks: 0,
                value_kinds: std::collections::HashMap::new(),
            },
        });
        let code = generate_from_pipeline(&pipeline);
        assert!(code.contains("canonical pipeline"));
        assert!(code.contains("GRAPH_FUNCTIONS"));
        assert!(code.contains("CANONICAL_TRACE_PATTERNS"));
    }

    #[test]
    fn generate_dispatch_tables_emits_all_tables() {
        let pipeline = crate::passes::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: Vec::new(),
            jitcodes: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        let code = generate_from_pipeline(&pipeline);
        // Int binary dispatch table
        assert!(
            code.contains("INT_BINOP_TABLE"),
            "should emit INT_BINOP_TABLE"
        );
        assert!(
            code.contains("int_binop_lookup"),
            "should emit int_binop_lookup"
        );
        // Float binary dispatch table
        assert!(
            code.contains("FLOAT_BINOP_TABLE"),
            "should emit FLOAT_BINOP_TABLE"
        );
        assert!(
            code.contains("float_binop_lookup"),
            "should emit float_binop_lookup"
        );
        // Comparison dispatch table
        assert!(code.contains("COMPARE_TABLE"), "should emit COMPARE_TABLE");
        assert!(
            code.contains("int_compare_lookup"),
            "should emit int_compare_lookup"
        );
        assert!(
            code.contains("float_compare_lookup"),
            "should emit float_compare_lookup"
        );
        // Concrete computation helpers
        assert!(
            code.contains("concrete_float_binop"),
            "should emit concrete_float_binop"
        );
        assert!(
            code.contains("concrete_int_binop"),
            "should emit concrete_int_binop"
        );
    }
}
