//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by pyre-mjit's build.rs via include!().
//!
//! Each recognized TracePattern produces a tracing function that emits
//! the equivalent IR ops. Unrecognized patterns fall back to residual calls.

/// Generate tracing code from graph pipeline results.
///
/// Test-only summary emitter for raw graph pipeline output. Active consumers
/// should use `generate_from_pipeline()`, which is the canonical translator
/// entry point.
#[cfg(test)]
pub fn generate_from_graph(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter graph pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));

    // Function summary
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");

    out
}

/// Generate tracing code directly from the canonical pipeline result.
///
/// This is the RPython-leaning entry point: graph/pipeline output is the only
/// source-of-truth used for emission.
pub fn generate_from_pipeline(result: &crate::passes::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-codewriter canonical pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Canonical graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));
    out.push('\n');

    generate_graph_function_summary(&mut out, result);
    generate_canonical_dispatch_table(&mut out, result);
    generate_trace_functions(&mut out);

    let flattened_count = result
        .opcode_dispatch
        .iter()
        .filter(|a| a.flattened.is_some())
        .count();
    out.push_str(&format!(
        "// Canonical analysis summary: {}/{} flattened\n",
        flattened_count,
        result.opcode_dispatch.len(),
    ));

    out
}

fn generate_graph_function_summary(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");
}

fn generate_canonical_dispatch_table(
    out: &mut String,
    result: &crate::passes::ProgramPipelineResult,
) {
    out.push_str("/// Canonical analysis summary: opcode → flattened op count.\n");
    out.push_str("pub const CANONICAL_TRACE_PATTERNS: &[(&str, &str)] = &[\n");
    for arm in &result.opcode_dispatch {
        let status = match &arm.flattened {
            Some(f) => format!("Flattened({}ops)", f.insns.len()),
            None => "Unflattened".to_string(),
        };
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            arm.selector.canonical_key().replace('"', "\\\""),
            status.replace('"', "\\\""),
        ));
    }
    out.push_str("];\n\n");
}

fn generate_trace_functions(out: &mut String) {
    // ── Unbox/Box helpers ──
    // These are the core building blocks for tracing Python operations.
    // They mirror PyPy's RPython-generated unbox/box sequences.

    out.push_str(r#"
/// Unbox a Python int object: emit GuardClass + GetfieldGc(I|PureI).
///
/// Auto-generated equivalent of PyPy's int_unbox annotation.
/// Returns the raw i64 OpRef, with heapcache integration.
fn trace_getfield_gc_int_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // heapcache: check if this field was already read/written in this trace
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureI
    } else {
        OpCode::GetfieldGcI
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_int(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    // GUARD_CLASS(box, cls): guard takes object box directly,
    // backend loads typeptr at offset 0 (llgraph/runner.py:1245).
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(int_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(int_type_addr as usize));
    }
    trace_getfield_gc_int_pureornot(ctx, obj, intval_descr)
}

/// Box a raw i64 into a Python int object.
///
/// Auto-generated equivalent of PyPy's int_box annotation.
/// The helper route preserves pyre's small-int cache instead of always
/// materializing a fresh heap object in the trace.
pub fn trace_box_int(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    int_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;

    // Inline W_Int allocation so OptVirtualize can see the object shape
    // and fold later GetfieldRawI(intval) reads back to `value`.
    let obj = ctx.record_op_with_descr(OpCode::New, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let type_ptr = ctx.const_int(int_type_addr);
    let ob_type_idx = ob_type_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, type_ptr], ob_type_descr);
    ctx.heap_cache_mut().setfield_cached(obj, ob_type_idx, type_ptr);
    let intval_idx = intval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], intval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, intval_idx, value);
    obj
}

/// Emit an overflow-checked binary int operation.
///
/// Auto-generated: unbox a, unbox b, emit ovf op, guard no overflow, box result.
pub fn trace_int_binop_ovf(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    ctx.record_guard_typed_with_fail_args(
        OpCode::GuardNoOverflow, &[],
        vec![majit_ir::Type::Ref; fail_args.len()], fail_args,
    );
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a non-overflow binary int operation (bitwise ops, shifts).
pub fn trace_int_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_int(ctx, result, size_descr, ob_type_descr, intval_descr, int_type_addr)
}

/// Emit a comparison between two Python ints.
pub fn trace_int_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    int_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    intval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_int(ctx, a, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    let b_val = trace_unbox_int(ctx, b, int_type_addr, ob_type_descr.clone(), intval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}

/// Unbox a Python float object: emit GuardClass + GetfieldGc(F|PureF).
///
/// Returns the raw f64 OpRef.
fn trace_getfield_gc_float_pureornot(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    descr: majit_ir::DescrRef,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let field_index = descr.index();
    if let Some(cached) = ctx.heap_cache().getfield_cached(obj, field_index) {
        return cached;
    }
    let opcode = if descr.is_always_pure() {
        OpCode::GetfieldGcPureF
    } else {
        OpCode::GetfieldGcF
    };
    let result = ctx.record_op_with_descr(opcode, &[obj], descr);
    ctx.heap_cache_mut().getfield_now_known(obj, field_index, result);
    result
}

pub fn trace_unbox_float(
    ctx: &mut majit_metainterp::TraceCtx,
    obj: majit_ir::OpRef,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    if !ctx.heap_cache().is_class_known(obj) {
        let type_const = ctx.const_int(float_type_addr);
        ctx.record_guard_typed_with_fail_args(
            OpCode::GuardClass,
            &[obj, type_const],
            vec![majit_ir::Type::Ref; fail_args.len()],
            fail_args,
        );
        ctx.heap_cache_mut()
            .class_now_known(obj, majit_ir::GcRef(float_type_addr as usize));
    }
    trace_getfield_gc_float_pureornot(ctx, obj, floatval_descr)
}

/// Box a raw f64 into a Python float object: emit New + SetfieldGc.
pub fn trace_box_float(
    ctx: &mut majit_metainterp::TraceCtx,
    value: majit_ir::OpRef,
    size_descr: majit_ir::DescrRef,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    float_type_addr: i64,
) -> majit_ir::OpRef {
    use majit_ir::OpCode;
    let obj = ctx.record_op_with_descr(OpCode::New, &[], size_descr);
    ctx.heap_cache_mut().new_object(obj);
    let type_ptr = ctx.const_int(float_type_addr);
    let ob_type_idx = ob_type_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, type_ptr], ob_type_descr);
    ctx.heap_cache_mut().setfield_cached(obj, ob_type_idx, type_ptr);
    let floatval_idx = floatval_descr.index();
    ctx.record_op_with_descr(OpCode::SetfieldGc, &[obj, value], floatval_descr);
    ctx.heap_cache_mut().setfield_cached(obj, floatval_idx, value);
    obj
}

/// Emit a binary float operation: unbox a, unbox b, emit float op, box result.
pub fn trace_float_binop(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    size_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let result = ctx.record_op(opcode, &[a_val, b_val]);
    trace_box_float(ctx, result, size_descr, ob_type_descr, floatval_descr, float_type_addr)
}

/// Emit a comparison between two Python floats.
pub fn trace_float_compare(
    ctx: &mut majit_metainterp::TraceCtx,
    a: majit_ir::OpRef,
    b: majit_ir::OpRef,
    opcode: majit_ir::OpCode,
    float_type_addr: i64,
    ob_type_descr: majit_ir::DescrRef,
    floatval_descr: majit_ir::DescrRef,
    fail_args: &[majit_ir::OpRef],
) -> majit_ir::OpRef {
    let a_val = trace_unbox_float(ctx, a, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    let b_val = trace_unbox_float(ctx, b, float_type_addr, ob_type_descr.clone(), floatval_descr.clone(), fail_args);
    ctx.record_op(opcode, &[a_val, b_val])
}
"#);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_from_graph_produces_function_table() {
        let parsed = crate::parse::parse_source(
            r#"
            fn add(a: i64, b: i64) -> i64 { a + b }
            fn sub(a: i64, b: i64) -> i64 { a - b }
        "#,
        );
        let program = crate::front::build_semantic_program(&parsed);
        let pipeline =
            crate::passes::analyze_program(&program, &crate::passes::PipelineConfig::default());
        let code = generate_from_graph(&pipeline);

        assert!(
            code.contains("GRAPH_FUNCTIONS"),
            "should contain GRAPH_FUNCTIONS table"
        );
        assert!(code.contains("add"), "should list 'add' function");
        assert!(code.contains("sub"), "should list 'sub' function");
        assert!(
            code.contains("graph pipeline"),
            "should have graph pipeline header"
        );
    }

    #[test]
    fn generate_from_pipeline_emits_canonical_header() {
        let mut pipeline = crate::passes::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: vec![crate::passes::PipelineOpcodeArm {
                selector: crate::OpcodeDispatchSelector::Path(crate::CallPath::from_segments([
                    "Instruction",
                    "Add",
                ])),
                flattened: None,
            }],
            jitcodes: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        pipeline.functions.push(crate::passes::PipelineResult {
            name: "add".into(),
            original_blocks: 1,
            annotations_count: 0,
            concrete_types_count: 0,
            vable_rewrites: 0,
            calls_classified: 0,
            transform_notes: Vec::new(),
            flattened: crate::passes::SSARepr {
                name: "add".into(),
                insns: Vec::new(),
                num_values: 0,
                num_blocks: 0,
                value_kinds: std::collections::HashMap::new(),
            },
        });
        let code = generate_from_pipeline(&pipeline);
        assert!(code.contains("canonical pipeline"));
        assert!(code.contains("GRAPH_FUNCTIONS"));
        assert!(code.contains("CANONICAL_TRACE_PATTERNS"));
    }
}
