[package]
name = "majit-backend-cranelift"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Cranelift code generation backend for majit JIT compiler"

[dependencies]
indexmap = { workspace = true }
majit-ir = { workspace = true }
majit-backend = { workspace = true }
majit-translate = { workspace = true }
majit-gc = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
target-lexicon = { workspace = true }

[dev-dependencies]
majit-gc = { workspace = true, features = ["gc_box"] }
majit-ir = { workspace = true, features = ["test-support"] }
smallvec = { workspace = true }
