"""Generate the masking variant's modules from the branching ones.

`marked_masking.py` from `marked.py`, and `fixture_masking.py` from
`fixture.py`.

The two modules must differ in exactly five expressions inside the traced
`shift` walk -- four `return`s and one continuation line in `Sequence._shift`
-- and nothing else, or the A/B they form is not an A/B of the operators.
Writing the variant by hand invites drift -- a fix applied to one and not the
other -- so it is generated, and this script refuses if any substitution no
longer matches.

    python3 make_masking.py           # rewrite marked_masking.py
    python3 make_masking.py --check   # exit 1 if it is out of date

Runs under Python 2 or 3: it is text processing, not RPython.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# part 1's short-circuiting spelling -> part 2's masking spelling.
SUBS = [
    ("        return mark and c == self.c",
     "        return mark & (c == self.c)"),
    ("        return marked_left or marked_right",
     "        return marked_left | marked_right"),
    ("        return self.re.shift(c, mark or self.marked)",
     "        return self.re.shift(c, mark | self.marked)"),
    ("        return (marked_left and self.right.empty) or marked_right",
     "        return (marked_left & self.right.empty) | marked_right"),
    # NOT a `return` line, and missed on the first pass because the table
    # only looked at those. It cost a translation and a measurement: the
    # masking build still grew 1191 bridges over 262144 characters, the same
    # as the branching one, because every `Sequence` node still short-circuited
    # here. `verify_no_short_circuit` below is what makes that unrepeatable.
    ("        c, old_marked_left or (mark and self.left.empty))",
     "        c, old_marked_left | (mark & self.left.empty))"),
]

# `fixture.py` imports the node classes by name, so a masking target that
# imported the plain fixture would build its tree out of `marked`\'s classes
# and then call `marked_masking`\'s `reset` on it. `reset` dispatches on
# `isinstance(re, Binary)`, which is False across two copies of a hierarchy, so
# it silently becomes a no-op and marks leak from one pass into the next. That
# surfaces as a WRONG ANSWER on the second pass, not as an error -- the target's
# `sink` check is what catches it.
FIXTURE_SUBS = [
    ("from marked import Char, Alternative, Repetition, Sequence",
     "from marked_masking import Char, Alternative, Repetition, Sequence"),
    # `count`'s import is function-local, and the table missed it for the same
    # reason it missed `Sequence._shift`'s second short-circuit: it was read as
    # the lines someone remembered rather than as every line naming the module.
    # `count` then ran its `isinstance` across two copies of the hierarchy, so
    # every node fell through to the leaf arm and `target_masking.py` printed
    # `nodes=1` above the timings for the 93-node tree it was timing.
    # `verify_no_plain_marked` below is what makes that unrepeatable.
    ("    from marked import Binary, Repetition as Rep",
     "    from marked_masking import Binary, Repetition as Rep"),
]

# `and` / `or` that survive into the masking variant on purpose. Both compute
# `empty` once while the tree is built; nothing the JitDriver traces reaches
# them, so masking them would change the A/B's shape without changing what it
# measures. `verify_no_short_circuit` scans every other line of the module.
BUILD_TIME_SHORT_CIRCUITS = [
    "Binary.__init__(self, left, right, left.empty or right.empty)",
    "Binary.__init__(self, left, right, left.empty and right.empty)",
]

FIXTURE_HEAD = '''"""The masking variant's fixture: `fixture.py` over `marked_masking`.

GENERATED by `make_masking.py` from `fixture.py` -- edit that one, not this.

It exists only so the tree is built from the same class hierarchy the matcher
walks. Two copies of the hierarchy would make `reset`'s `isinstance` test false
and leave marks standing between passes.
"""
'''

HEAD = '''"""The masking variant: part 2's `&` and `|` instead of part 1's `and`/`or`.

GENERATED by `make_masking.py` from `marked.py` -- edit that one, not this.

Identical to `marked.py` except for five expressions inside the traced `shift`
walk -- four `return`s and one continuation line in `Sequence._shift` -- so the
pair is an A/B of the operators and of nothing else. The two `and`/`or` in
`Alternative.__init__` and `Sequence.__init__` are deliberately NOT masked:
they compute `empty` once while the tree is built, outside anything the
JitDriver traces. The blog post says:

    the JIT-version of the code needs to be adapted to use the
    non-short-circuiting operators `&` and `|` ... If you don't change the
    "and" and "or" you get a lot of assembler code generated, and it's not
    particularly fast

`marked.py` is the unadapted side and this is the adapted one. The crate above
mirrors the pair exactly: `shortcircuit.rs` against `jit_interp.rs`.
"""
'''


def verify_no_short_circuit(body, dest):
    """Refuse to emit a variant that still short-circuits where it is traced.

    The substitution table is a list of exact strings, so it silently does
    nothing about a line nobody thought to add to it -- and a half-masked
    variant is worse than no variant, because it looks like the A/B while
    measuring something else.

    This scans the WHOLE module body rather than the bodies of functions named
    `shift` / `_shift`. Name-scoping was the shape of the first two misses: it
    reads as "the lines someone remembered" and goes quiet about a helper the
    traced walk calls under any other name. The two survivors are named in
    BUILD_TIME_SHORT_CIRCUITS instead, so adding a third is an edit to that
    list rather than a silence.

    `body` is the module WITHOUT its docstring -- the blog quote in the header
    contains the words this scans for.
    """
    for no, line in enumerate(body.split('\n'), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if stripped in BUILD_TIME_SHORT_CIRCUITS:
            continue
        if ' and ' in line or ' or ' in line:
            sys.stderr.write(
                "make_masking.py: %s line %d still short-circuits:\n  %s\n"
                "Add the line to the substitution table, or -- if it runs at\n"
                "tree-build time rather than inside the traced walk -- to\n"
                "BUILD_TIME_SHORT_CIRCUITS.\n"
                % (dest, no, stripped)
            )
            sys.exit(2)


def verify_no_plain_marked(text, dest):
    """Refuse to emit a fixture that still names the branching module.

    Every class the masking fixture touches has to come from
    `marked_masking`. A surviving `marked` import does not raise: `isinstance`
    is simply false across two copies of a hierarchy, so a walk over the tree
    answers as though every node were a leaf, and the wrong answer is printed
    rather than reported.
    """
    for no, line in enumerate(text.split('\n'), 1):
        stripped = line.strip()
        names_it = stripped.startswith('from marked import') or (
            stripped.startswith('import marked')
            and not stripped.startswith('import marked_masking')
        )
        if names_it:
            sys.stderr.write(
                "make_masking.py: %s line %d still imports from the branching\n"
                "module, so its `isinstance` tests run across two copies of\n"
                "the hierarchy:\n  %s\n"
                "Add the line to the substitution table.\n"
                % (dest, no, stripped)
            )
            sys.exit(2)


def render(source, subs, head):
    with open(os.path.join(HERE, source)) as f:
        src = f.read()
    out = src
    for old, new in subs:
        if old not in out:
            sys.stderr.write(
                "make_masking.py: `%s` no longer contains:\n  %s\n"
                "The two sides would stop being an A/B of the operators\n"
                "alone. Update the substitution table to match.\n"
                % (source, old)
            )
            sys.exit(2)
        out = out.replace(old, new, 1)
    i = out.index('"""')
    j = out.index('"""', i + 3) + 3
    body = out[j:].lstrip('\n')
    out = head + body
    if source == 'marked.py':
        # The body, not `out`: the header quotes the post's own sentence about
        # the "and" and "or", which the scan would read as a survivor.
        verify_no_short_circuit(body, 'marked_masking.py')
    if source == 'fixture.py':
        verify_no_plain_marked(out, 'fixture_masking.py')
    return out


GENERATED = [
    ('marked.py', 'marked_masking.py', SUBS, HEAD),
    ('fixture.py', 'fixture_masking.py', FIXTURE_SUBS, FIXTURE_HEAD),
]


def main():
    check = '--check' in sys.argv
    for source, dest, subs, head in GENERATED:
        want = render(source, subs, head)
        path = os.path.join(HERE, dest)
        if check:
            try:
                with open(path) as f:
                    have = f.read()
            except IOError:
                have = None
            if have != want:
                sys.stderr.write(
                    "%s is out of date; run `python3 %s`\n"
                    % (dest, os.path.basename(__file__))
                )
                sys.exit(1)
            sys.stdout.write("%s is up to date\n" % dest)
            continue
        with open(path, 'w') as f:
            f.write(want)
        sys.stdout.write("wrote %s\n" % path)


if __name__ == '__main__':
    main()
