//! pyre-jit: Auto-generated JIT for pyre.
//!
//! This crate is the Rust equivalent of RPython's `rpython/jit/` —
//! it contains automatically generated tracing code produced by
//! `majit-analyze` during build time.
//!
//! The interpreter (`pyre-interp`) has zero JIT dependencies.
//! All JIT logic lives here, generated from static analysis of
//! the interpreter's source code.
//!
//! Architecture:
//! ```text
//! pyre-interp (pure interpreter)
//!       ↓ (source analysis at build time)
//! majit-analyze (RPython translator)
//!       ↓ (code generation)
//! pyre-jit (this crate)
//!   ├── jit_trace_gen.rs (auto-generated trace functions)
//!   ├── driver.rs (JIT driver integration)
//!   └── lib.rs (public API)
//! ```

pub mod call_jit;
pub mod driver;
pub mod eval;
pub mod jit;
mod trace_verify;

// Include auto-generated trace dispatch table and helpers (top-level access)
include!(concat!(env!("OUT_DIR"), "/jit_trace_gen.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_dispatch_table() {
        // Verify the auto-generated code compiled and has content
        assert!(
            CANONICAL_TRACE_PATTERNS.len() > 20,
            "expected >20 patterns, got {}",
            CANONICAL_TRACE_PATTERNS.len()
        );

        // Check key patterns exist — majit-analyze classifies opcodes
        // based on virtualizable array access patterns (RPython parity).
        let has_vable_read = CANONICAL_TRACE_PATTERNS
            .iter()
            .any(|(_, p)| *p == "VableArrayRead");
        assert!(has_vable_read, "missing VableArrayRead pattern");

        let has_vable_write = CANONICAL_TRACE_PATTERNS
            .iter()
            .any(|(_, p)| *p == "VableArrayWrite");
        assert!(has_vable_write, "missing VableArrayWrite pattern");

        let has_vable_field = CANONICAL_TRACE_PATTERNS
            .iter()
            .any(|(_, p)| *p == "VableFieldWrite");
        assert!(has_vable_field, "missing VableFieldWrite pattern");

        eprintln!(
            "Auto-generated {} canonical trace patterns",
            CANONICAL_TRACE_PATTERNS.len()
        );
        for (pat, cls) in CANONICAL_TRACE_PATTERNS {
            if *cls != "Unclassified" {
                eprintln!("  {} → {}", pat, cls);
            }
        }
    }

    #[test]
    fn test_trace_functions_exist() {
        // Verify auto-generated trace functions are callable
        // (they're generated by majit-analyze codegen)
        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            i64,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            &[majit_ir::OpRef],
        ) -> majit_ir::OpRef = trace_unbox_int;

        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            i64,
        ) -> majit_ir::OpRef = trace_box_int;

        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            majit_ir::OpRef,
            majit_ir::OpCode,
            i64,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            &[majit_ir::OpRef],
        ) -> majit_ir::OpRef = trace_int_binop_ovf;

        eprintln!("trace_unbox_int, trace_box_int, trace_int_binop_ovf: ✓");
    }
}
