//! pyre-jit: Auto-generated JIT for pyre.
//!
//! This crate is the Rust equivalent of RPython's `rpython/jit/` —
//! it contains automatically generated tracing code produced by
//! `majit-analyze` during build time.
//!
//! The interpreter (`pyre-interp`) has zero JIT dependencies.
//! All JIT logic lives here, generated from static analysis of
//! the interpreter's source code.
//!
//! Architecture:
//! ```text
//! pyre-interp (pure interpreter)
//!       ↓ (source analysis at build time)
//! majit-analyze (RPython translator)
//!       ↓ (code generation)
//! pyre-jit (this crate)
//!   ├── jit_trace_gen.rs (auto-generated trace functions)
//!   ├── driver.rs (JIT driver integration)
//!   └── lib.rs (public API)
//! ```

pub mod driver;
pub mod eval;
mod trace_verify;

// Include auto-generated trace dispatch table and helpers
include!(concat!(env!("OUT_DIR"), "/jit_trace_gen.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_dispatch_table() {
        // Verify the auto-generated code compiled and has content
        assert!(
            TRACE_PATTERNS.len() > 20,
            "expected >20 patterns, got {}",
            TRACE_PATTERNS.len()
        );

        // Check key patterns exist
        let has_binary = TRACE_PATTERNS
            .iter()
            .any(|(_, p)| p.contains("UnboxIntBinop"));
        assert!(has_binary, "missing UnboxIntBinop pattern");

        let has_local_read = TRACE_PATTERNS.iter().any(|(_, p)| p.contains("LocalRead"));
        assert!(has_local_read, "missing LocalRead pattern");

        let has_call = TRACE_PATTERNS
            .iter()
            .any(|(_, p)| p.contains("FunctionCall"));
        assert!(has_call, "missing FunctionCall pattern");

        eprintln!("Auto-generated {} trace patterns", TRACE_PATTERNS.len());
        for (pat, cls) in TRACE_PATTERNS {
            if *cls != "Unclassified" {
                eprintln!("  {} → {}", pat, cls);
            }
        }
    }

    #[test]
    fn test_trace_functions_exist() {
        // Verify auto-generated trace functions are callable
        // (they're generated by majit-analyze codegen)
        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            i64,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            &[majit_ir::OpRef],
        ) -> majit_ir::OpRef = trace_unbox_int;

        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            i64,
        ) -> majit_ir::OpRef = trace_box_int;

        let _: fn(
            &mut majit_meta::TraceCtx,
            majit_ir::OpRef,
            majit_ir::OpRef,
            majit_ir::OpCode,
            i64,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            majit_ir::DescrRef,
            &[majit_ir::OpRef],
        ) -> majit_ir::OpRef = trace_int_binop_ovf;

        eprintln!("trace_unbox_int, trace_box_int, trace_int_binop_ovf: ✓");
    }
}
