/// Tests that codegen produces valid wasm modules.
///
/// Uses wasmparser to validate the generated bytes without executing them.
use std::collections::HashMap;

use majit_backend_wasm::codegen;
use majit_ir::operand::Operand;
use majit_ir::{InputArg, Op, OpCode, OpRef, Type};
use smallvec::smallvec;

fn validate_wasm(bytes: &[u8]) {
    wasmparser::validate(bytes).expect("generated wasm should be valid");
}

fn make_op(opcode: OpCode, args: &[OpRef], pos: OpRef) -> Op {
    let bx: Vec<Operand> = args.iter().map(|a| rb(*a)).collect();
    let op = Op::new(opcode, &bx);
    op.pos.set(pos);
    op
}

use majit_ir::box_ref::bound_operand_from_opref as rb;

fn make_guard(opcode: OpCode, args: &[OpRef], fail_args: &[OpRef]) -> Op {
    let bx: Vec<Operand> = args.iter().map(|a| rb(*a)).collect();
    let op = Op::new(opcode, &bx);
    op.setfailargs(smallvec![rb(fail_args[0]); 0]);
    let mut fa: smallvec::SmallVec<[Operand; 3]> = smallvec::SmallVec::new();
    for &a in fail_args {
        fa.push(rb(a));
    }
    op.setfailargs(fa);
    op
}

#[test]
fn test_empty_trace() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];
    let ops = vec![{
        let op = Op::new(OpCode::Finish, &[rb(OpRef::input_arg_int(0))]);
        op.setfailargs(smallvec![rb(OpRef::input_arg_int(0))]);
        op
    }];
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
    assert!(guards[0].is_finish);
}

#[test]
fn test_int_add_loop() {
    // Label(i, sum) -> IntAdd(sum, i) -> IntAdd(i, 1) -> IntLt(i, 100)
    // -> GuardTrue -> Jump(new_i, new_sum)
    let inputargs = vec![
        InputArg::from_type(Type::Int, 0), // i
        InputArg::from_type(Type::Int, 1), // sum
    ];

    let const_1 = OpRef::const_int(1);
    let const_100 = OpRef::const_int(100);
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        Op::new(
            OpCode::Label,
            &[rb(OpRef::input_arg_int(0)), rb(OpRef::input_arg_int(1))],
        ),
        make_op(
            OpCode::IntAdd,
            &[OpRef::input_arg_int(1), OpRef::input_arg_int(0)],
            OpRef::int_op(2),
        ), // sum + i
        make_op(
            OpCode::IntAdd,
            &[OpRef::input_arg_int(0), const_1],
            OpRef::int_op(3),
        ), // i + 1
        make_op(
            OpCode::IntLt,
            &[OpRef::int_op(3), const_100],
            OpRef::int_op(4),
        ), // i+1 < 100
        make_guard(
            OpCode::GuardTrue,
            &[OpRef::int_op(4)],
            &[OpRef::int_op(3), OpRef::int_op(2)],
        ),
        Op::new(OpCode::Jump, &[rb(OpRef::int_op(3)), rb(OpRef::int_op(2))]),
    ];

    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1); // one guard
    assert!(!guards[0].is_finish);
}

#[test]
fn test_float_ops() {
    let inputargs = vec![
        InputArg::from_type(Type::Float, 0),
        InputArg::from_type(Type::Float, 1),
    ];

    let ops = vec![
        make_op(
            OpCode::FloatAdd,
            &[OpRef::input_arg_float(0), OpRef::input_arg_float(1)],
            OpRef::float_op(2),
        ),
        make_op(
            OpCode::FloatSub,
            &[OpRef::input_arg_float(0), OpRef::input_arg_float(1)],
            OpRef::float_op(3),
        ),
        make_op(
            OpCode::FloatMul,
            &[OpRef::float_op(2), OpRef::float_op(3)],
            OpRef::float_op(4),
        ),
        make_op(
            OpCode::FloatTrueDiv,
            &[OpRef::float_op(4), OpRef::input_arg_float(0)],
            OpRef::float_op(5),
        ),
        make_op(OpCode::FloatNeg, &[OpRef::float_op(5)], OpRef::float_op(6)),
        make_op(OpCode::FloatAbs, &[OpRef::float_op(6)], OpRef::float_op(7)),
        make_op(
            OpCode::FloatLt,
            &[OpRef::input_arg_float(0), OpRef::input_arg_float(1)],
            OpRef::int_op(8),
        ),
        {
            let op = Op::new(OpCode::Finish, &[rb(OpRef::float_op(7))]);
            op.setfailargs(smallvec![rb(OpRef::float_op(7))]);
            op
        },
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

#[test]
fn test_call_generates_import() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    let func_ptr = OpRef::const_int(42); // fake func_ptr
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        make_op(
            OpCode::CallI,
            &[func_ptr, OpRef::input_arg_int(0)],
            OpRef::int_op(1),
        ),
        {
            let op = Op::new(OpCode::Finish, &[rb(OpRef::int_op(1))]);
            op.setfailargs(smallvec![rb(OpRef::int_op(1))]);
            op
        },
    ];

    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);

    // Verify the module has jit_call import
    let parser = wasmparser::Parser::new(0);
    let mut has_jit_call = false;
    for payload in parser.parse_all(&bytes) {
        if let Ok(wasmparser::Payload::ImportSection(imports)) = payload {
            for import in imports {
                if let Ok(import) = import {
                    if import.name == "jit_call" {
                        has_jit_call = true;
                    }
                }
            }
        }
    }
    assert!(has_jit_call, "module should import jit_call");
}

#[test]
fn test_guard_types() {
    let inputargs = vec![
        InputArg::from_type(Type::Int, 0),
        InputArg::from_type(Type::Int, 1),
    ];

    let ops = vec![
        Op::new(
            OpCode::Label,
            &[rb(OpRef::input_arg_int(0)), rb(OpRef::input_arg_int(1))],
        ),
        // GuardTrue
        make_guard(
            OpCode::GuardTrue,
            &[OpRef::input_arg_int(0)],
            &[OpRef::input_arg_int(0), OpRef::input_arg_int(1)],
        ),
        // GuardFalse
        make_guard(
            OpCode::GuardFalse,
            &[OpRef::input_arg_int(1)],
            &[OpRef::input_arg_int(0), OpRef::input_arg_int(1)],
        ),
        // GuardValue
        make_guard(
            OpCode::GuardValue,
            &[OpRef::input_arg_int(0), OpRef::input_arg_int(1)],
            &[OpRef::input_arg_int(0)],
        ),
        // GuardNonnull
        make_guard(
            OpCode::GuardNonnull,
            &[OpRef::input_arg_int(0)],
            &[OpRef::input_arg_int(0)],
        ),
        // GuardIsnull
        make_guard(
            OpCode::GuardIsnull,
            &[OpRef::input_arg_int(1)],
            &[OpRef::input_arg_int(1)],
        ),
        // GuardNoOverflow (0 args)
        {
            let op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.setfailargs(smallvec![rb(OpRef::input_arg_int(0))]);
            op
        },
        // GuardNotInvalidated (0 args, always pass)
        {
            let op = Op::new(OpCode::GuardNotInvalidated, &[]);
            op.setfailargs(smallvec![rb(OpRef::input_arg_int(0))]);
            op
        },
        Op::new(
            OpCode::Jump,
            &[rb(OpRef::input_arg_int(0)), rb(OpRef::input_arg_int(1))],
        ),
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 7);
}

/// GuardNoException loads the global exception slot and fails when it is set;
/// GuardException compares the pending exception type against the expected one
/// and, on match, binds the caught value into its result var and clears both
/// slots. Validates the emitted bytecode is well-formed (stack-balanced).
#[test]
fn test_exception_guards() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    let ops = vec![
        Op::new(OpCode::Label, &[rb(OpRef::input_arg_int(0))]),
        // GuardNoException — 0 args, fails when an exception is pending.
        {
            let op = Op::new(OpCode::GuardNoException, &[]);
            op.setfailargs(smallvec![rb(OpRef::input_arg_int(0))]);
            op
        },
        // GuardException(expected_type) — caught value bound to int_op(1).
        {
            let op = Op::new(OpCode::GuardException, &[rb(OpRef::input_arg_int(0))]);
            op.pos.set(OpRef::int_op(1));
            op.setfailargs(smallvec![rb(OpRef::input_arg_int(0))]);
            op
        },
        Op::new(OpCode::Jump, &[rb(OpRef::input_arg_int(0))]),
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 2);
}

/// GuardGcType contract in majit: arg0 = object ref, arg1 = expected
/// type_id. The wasm backend reads the GC header word at
/// `obj - GcHeader::SIZE` (matching the cranelift backend and
/// `majit_gc::header::GcHeader` layout) and compares the low
/// `TYPE_ID_BITS` against arg1. arg1 is an immediate type_id, NOT a
/// classptr — no `mem32[obj + 0]` read, no classptr→typeid lookup.
#[test]
fn test_guard_gc_type_uses_immediate_typeid() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    // Inline-Const carrying the immediate typeid 0x42
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        Op::new(OpCode::Label, &[rb(OpRef::input_arg_int(0))]),
        make_guard(
            OpCode::GuardGcType,
            &[OpRef::input_arg_int(0), OpRef::const_int(0x42)],
            &[OpRef::input_arg_int(0)],
        ),
        Op::new(OpCode::Jump, &[rb(OpRef::input_arg_int(0))]),
    ];

    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

/// Build a `GuardGcTypeInfo` matching what `WasmBackend::compile_loop`
/// derives from a real `GcLLDescr_framework`-equivalent allocator.
/// Mirrors `gc.py:592 get_translated_info_for_typeinfo` /
/// `gc.py:619 get_translated_info_for_guard_is_object` /
/// `x86/assembler.py:1951 cpu.subclassrange_min_offset`.
fn enabled_guard_gc_type_info() -> codegen::GuardGcTypeInfo {
    let mut info = codegen::GuardGcTypeInfo::default();
    info.supports_guard_gc_type = true;
    // Pretend the TYPE_INFO table sits at a small in-memory address;
    // wasm validation only checks the bytecode shape, not the actual
    // load addresses, so any value works for codegen testing.
    info.base_type_info = 0x1000;
    // majit `TypeEntry` stride = 32 bytes (TypeInfoLayout 16 + ClassTypeLayout 16).
    // shift_by = log2(32) = 5, sizeof_ti = rffi.sizeof(TYPE_INFO) = 16.
    info.shift_by = 5;
    info.sizeof_ti = 16; // size_of::<TypeInfoLayout>()
    // gc.py:603-622 _setup_guard_is_object: T_IS_RPYTHON_INSTANCE
    // = 0x100000 (gctypelayout.py:196), packed little-endian into a
    // Signed word — byte at offset +2 carries the flag, mask = 0x10.
    info.infobits_offset = 2;
    info.is_object_flag = 0x10;
    info.subclassrange_min_offset = 0; // offset within ClassTypeLayout
    info
}

/// x86/assembler.py:1924-1943 `genop_guard_guard_is_object` lowering —
/// the wasm backend's GUARD_IS_OBJECT arm emits the same MOV+addr_add
/// +TEST8+branch sequence. With `supports_guard_gc_type` enabled the
/// `assert` at line 1925 falls through and the rest of the lowering
/// runs; the resulting module must validate as legal wasm.
#[test]
fn test_guard_is_object_lowers_to_typeinfo_test() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    let ops = vec![
        Op::new(OpCode::Label, &[rb(OpRef::input_arg_int(0))]),
        make_guard(
            OpCode::GuardIsObject,
            &[OpRef::input_arg_int(0)],
            &[OpRef::input_arg_int(0)],
        ),
        Op::new(OpCode::Jump, &[rb(OpRef::input_arg_int(0))]),
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &enabled_guard_gc_type_info(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed when supports_guard_gc_type=true");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

/// x86/assembler.py:1945-1980 `genop_guard_guard_subclass` lowering —
/// the wasm backend's GUARD_SUBCLASS arm emits the gcremovetypeptr
/// branch (cpu.vtable_offset = None) when `vtable_offset` is `None`,
/// otherwise the vtable-load branch. With `supports_guard_gc_type`
/// enabled and the constant classptr's `(min, max)` pre-fetched, the
/// lowering runs to completion.
#[test]
fn test_guard_subclass_lowers_to_subclassrange_check() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    // model.py:199-201 `cls_of_box()` returns `ConstInt(ptr2int(typeptr))` —
    // the emitted guard-class operand is the vtable address carried as a raw
    // integer (read with `op.getarg(1).getint()`, rewrite.py:247). Use the
    // inline ConstInt factory so the variant tag matches the backend reader.
    let class_constant = OpRef::const_int(0xCAFE);
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        Op::new(OpCode::Label, &[rb(OpRef::input_arg_int(0))]),
        make_guard(
            OpCode::GuardSubclass,
            &[OpRef::input_arg_int(0), class_constant],
            &[OpRef::input_arg_int(0)],
        ),
        Op::new(OpCode::Jump, &[rb(OpRef::input_arg_int(0))]),
    ];

    let mut info = enabled_guard_gc_type_info();
    // assembler.py:1971-1974: codegen-time
    // (vtable_ptr.subclassrange_min, vtable_ptr.subclassrange_max).
    info.subclass_ranges.insert(0xCAFE, (10, 20));

    // gcremovetypeptr branch: vtable_offset = None.
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        None,
        &HashMap::new(),
        &info,
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed when supports_guard_gc_type=true");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);

    // vtable-load branch: vtable_offset = Some(...).
    let (bytes2, _, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(8),
        &HashMap::new(),
        &info,
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed when vtable_offset is set");
    validate_wasm(&bytes2);
}

#[test]
fn test_sameas_and_conversions() {
    let inputargs = vec![InputArg::from_type(Type::Int, 0)];

    let ops = vec![
        make_op(
            OpCode::SameAsI,
            &[OpRef::input_arg_int(0)],
            OpRef::int_op(1),
        ),
        make_op(
            OpCode::CastIntToFloat,
            &[OpRef::input_arg_int(0)],
            OpRef::float_op(2),
        ),
        make_op(
            OpCode::CastFloatToInt,
            &[OpRef::float_op(2)],
            OpRef::int_op(3),
        ),
        make_op(
            OpCode::CastIntToPtr,
            &[OpRef::input_arg_int(0)],
            OpRef::ref_op(4),
        ),
        make_op(OpCode::CastPtrToInt, &[OpRef::ref_op(4)], OpRef::int_op(5)),
        make_op(OpCode::IntNeg, &[OpRef::input_arg_int(0)], OpRef::int_op(6)),
        make_op(
            OpCode::IntInvert,
            &[OpRef::input_arg_int(0)],
            OpRef::int_op(7),
        ),
        make_op(
            OpCode::IntIsTrue,
            &[OpRef::input_arg_int(0)],
            OpRef::int_op(8),
        ),
        make_op(
            OpCode::IntIsZero,
            &[OpRef::input_arg_int(0)],
            OpRef::int_op(9),
        ),
        {
            let op = Op::new(OpCode::Finish, &[rb(OpRef::int_op(9))]);
            op.setfailargs(smallvec![rb(OpRef::int_op(9))]);
            op
        },
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, _, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
}

#[test]
fn test_overflow_ops() {
    let inputargs = vec![
        InputArg::from_type(Type::Int, 0),
        InputArg::from_type(Type::Int, 1),
    ];

    let ops = vec![
        make_op(
            OpCode::IntAddOvf,
            &[OpRef::input_arg_int(0), OpRef::input_arg_int(1)],
            OpRef::int_op(2),
        ),
        {
            let op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.setfailargs(smallvec![rb(OpRef::int_op(2))]);
            op
        },
        make_op(
            OpCode::IntSubOvf,
            &[OpRef::input_arg_int(0), OpRef::input_arg_int(1)],
            OpRef::int_op(3),
        ),
        {
            let op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.setfailargs(smallvec![rb(OpRef::int_op(3))]);
            op
        },
        {
            let op = Op::new(OpCode::Finish, &[rb(OpRef::int_op(2))]);
            op.setfailargs(smallvec![rb(OpRef::int_op(2))]);
            op
        },
    ];

    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();
    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 3); // 2 GuardNoOverflow + 1 Finish
}

#[test]
fn test_single_label_peeled_loop_validates() {
    // A single-label PEELED loop: a preamble op (the unrolled first iteration)
    // precedes the LABEL, so codegen wraps it in the resume-at-LABEL preamble-
    // skip dispatch (block $exit / $past_loader / $skip_preamble + br_if, with
    // the preamble at br-depth 2 and the body at 1). This validates the new
    // control-flow nesting and br depths via wasmparser.
    let inputargs = vec![InputArg::from_type(Type::Int, 0)]; // i
    let const_1 = OpRef::const_int(1);
    let const_100 = OpRef::const_int(100);
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        // preamble (unrolled first iteration): i + 1 -> v1
        make_op(
            OpCode::IntAdd,
            &[OpRef::input_arg_int(0), const_1],
            OpRef::int_op(1),
        ),
        // loop header carrying v1 (single LABEL, with the preamble before it)
        Op::new(OpCode::Label, &[rb(OpRef::int_op(1))]),
        // body: v1 + 1 -> v2 ; v2 < 100 -> v3 ; guard ; jump v2 back to LABEL
        make_op(
            OpCode::IntAdd,
            &[OpRef::int_op(1), const_1],
            OpRef::int_op(2),
        ),
        make_op(
            OpCode::IntLt,
            &[OpRef::int_op(2), const_100],
            OpRef::int_op(3),
        ),
        make_guard(OpCode::GuardTrue, &[OpRef::int_op(3)], &[OpRef::int_op(2)]),
        Op::new(OpCode::Jump, &[rb(OpRef::int_op(2))]),
    ];

    // Must be classified as single-label peeled (exercises the dispatch wrapper).
    assert!(codegen::is_single_label_peeled(&ops));

    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
    assert!(!guards[0].is_finish);
}

#[test]
fn test_multi_label_peeled_resumes_at_last_label_validates() {
    // A MULTI-label peeled loop: a preamble precedes an outer entry LABEL and
    // the inner loop-header LABEL. `is_single_label_peeled` is false (two
    // labels) but `is_resumable_peeled` is true, so codegen emits the SAME
    // resume-at-LABEL 3-block wrapper, resuming at the LAST label (where the
    // `loop` is). This proves the wrapper + br depths stay valid for a
    // multi-label source — the case `compile_bridge` newly accepts when a
    // loop-closing bridge targets that last label.
    let inputargs = vec![InputArg::from_type(Type::Int, 0)]; // i
    let const_1 = OpRef::const_int(1);
    let const_100 = OpRef::const_int(100);
    let constants: majit_ir::VecMap<u32, i64> = majit_ir::VecMap::new();

    let ops = vec![
        // preamble (unrolled first iteration): i + 1 -> v1
        make_op(
            OpCode::IntAdd,
            &[OpRef::input_arg_int(0), const_1],
            OpRef::int_op(1),
        ),
        // outer entry LABEL carrying v1 (no `loop` — a codegen no-op)
        Op::new(OpCode::Label, &[rb(OpRef::int_op(1))]),
        // inner loop-header LABEL carrying v1 (the LAST label — `loop` here)
        Op::new(OpCode::Label, &[rb(OpRef::int_op(1))]),
        // body: v1 + 1 -> v2 ; v2 < 100 -> v3 ; guard ; jump v2 back to LABEL
        make_op(
            OpCode::IntAdd,
            &[OpRef::int_op(1), const_1],
            OpRef::int_op(2),
        ),
        make_op(
            OpCode::IntLt,
            &[OpRef::int_op(2), const_100],
            OpRef::int_op(3),
        ),
        make_guard(OpCode::GuardTrue, &[OpRef::int_op(3)], &[OpRef::int_op(2)]),
        Op::new(OpCode::Jump, &[rb(OpRef::int_op(2))]),
    ];

    // Multi-label: NOT the single-label subset, but still resumable-peeled, so
    // the wrapper is emitted and resumes at the last label.
    assert!(!codegen::is_single_label_peeled(&ops));
    assert!(codegen::is_resumable_peeled(&ops));

    let (bytes, guards, _, _, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        &codegen::GuardGcTypeInfo::default(),
        0,
        0,
        0,
        0, // fail_index_base
        0, // external_jump_slot
        codegen::CaParams::default(),
    )
    .expect("wasm codegen should succeed");
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
    assert!(!guards[0].is_finish);
}

#[test]
fn test_registration_loop_stamps_label_block_id() {
    // The bridge-side target-ordinal recovery rests on one fact: a LABEL and the
    // closing JUMP that targets it share their loop-target descr by Arc identity,
    // so the `label_block_id` `compile_loop` stamps on the LABEL is readable from
    // the JUMP's descr in `compile_bridge`. Reproduce that here: build two LABELs
    // each with its own descr, run the registration loop's stamping (ordinals 0,
    // 1), and confirm the JUMP that shares the second LABEL's descr reads back 1.
    let descr0 = majit_ir::make_loop_target_descr(10, false);
    let descr1 = majit_ir::make_loop_target_descr(11, false);

    let label0 = Op::new(OpCode::Label, &[rb(OpRef::int_op(1))]);
    label0.setdescr(descr0.clone());
    let label1 = Op::new(OpCode::Label, &[rb(OpRef::int_op(1))]);
    label1.setdescr(descr1.clone());
    // A loop-closing bridge's terminal JUMP carries the SAME descr Arc as the
    // label it targets (here, the second/last label).
    let jump = Op::new(OpCode::Jump, &[rb(OpRef::int_op(2))]);
    jump.setdescr(descr1.clone());

    // Registration loop (mirrors compile_loop): stamp each LABEL with its ordinal.
    for (ordinal, label) in [&label0, &label1].iter().enumerate() {
        let d = label.getdescr().expect("label has a descr");
        d.as_loop_target_descr()
            .expect("loop-target descr")
            .set_label_block_id(ordinal as u32);
    }

    // Recover the JUMP's target ordinal — it must equal the LAST label's (1),
    // via the shared Arc, NOT 0 (the default) or the first label's ordinal.
    let recovered = jump
        .getdescr()
        .and_then(|d| d.as_loop_target_descr().map(|t| t.label_block_id()));
    assert_eq!(recovered, Some(1));
}
