/// Tests that codegen produces valid wasm modules.
///
/// Uses wasmparser to validate the generated bytes without executing them.
use std::collections::HashMap;

use majit_backend_wasm::codegen;
use majit_ir::{InputArg, Op, OpCode, OpRef, Type};
use smallvec::smallvec;

fn validate_wasm(bytes: &[u8]) {
    wasmparser::validate(bytes).expect("generated wasm should be valid");
}

fn make_op(opcode: OpCode, args: &[OpRef], pos: OpRef) -> Op {
    let mut op = Op::new(opcode, args);
    op.pos = pos;
    op
}

fn make_guard(opcode: OpCode, args: &[OpRef], fail_args: &[OpRef]) -> Op {
    let mut op = Op::new(opcode, args);
    op.fail_args = Some(smallvec![fail_args[0]; 0]);
    let mut fa: smallvec::SmallVec<[OpRef; 3]> = smallvec::SmallVec::new();
    for &a in fail_args {
        fa.push(a);
    }
    op.fail_args = Some(fa);
    op
}

#[test]
fn test_empty_trace() {
    let inputargs = vec![InputArg {
        index: 0,
        tp: Type::Int,
    }];
    let ops = vec![{
        let mut op = Op::new(OpCode::Finish, &[OpRef(0)]);
        op.fail_args = Some(smallvec![OpRef(0)]);
        op
    }];
    let constants = HashMap::new();
    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
    assert!(guards[0].is_finish);
}

#[test]
fn test_int_add_loop() {
    // Label(i, sum) -> IntAdd(sum, i) -> IntAdd(i, 1) -> IntLt(i, 100)
    // -> GuardTrue -> Jump(new_i, new_sum)
    let inputargs = vec![
        InputArg {
            index: 0,
            tp: Type::Int,
        }, // i
        InputArg {
            index: 1,
            tp: Type::Int,
        }, // sum
    ];

    let const_1 = OpRef(10000);
    let const_100 = OpRef(10001);
    let mut constants = HashMap::new();
    constants.insert(10000, 1i64);
    constants.insert(10001, 100i64);

    let ops = vec![
        Op::new(OpCode::Label, &[OpRef(0), OpRef(1)]),
        make_op(OpCode::IntAdd, &[OpRef(1), OpRef(0)], OpRef(2)), // sum + i
        make_op(OpCode::IntAdd, &[OpRef(0), const_1], OpRef(3)),  // i + 1
        make_op(OpCode::IntLt, &[OpRef(3), const_100], OpRef(4)), // i+1 < 100
        make_guard(OpCode::GuardTrue, &[OpRef(4)], &[OpRef(3), OpRef(2)]),
        Op::new(OpCode::Jump, &[OpRef(3), OpRef(2)]),
    ];

    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1); // one guard
    assert!(!guards[0].is_finish);
}

#[test]
fn test_float_ops() {
    let inputargs = vec![
        InputArg {
            index: 0,
            tp: Type::Float,
        },
        InputArg {
            index: 1,
            tp: Type::Float,
        },
    ];

    let ops = vec![
        make_op(OpCode::FloatAdd, &[OpRef(0), OpRef(1)], OpRef(2)),
        make_op(OpCode::FloatSub, &[OpRef(0), OpRef(1)], OpRef(3)),
        make_op(OpCode::FloatMul, &[OpRef(2), OpRef(3)], OpRef(4)),
        make_op(OpCode::FloatTrueDiv, &[OpRef(4), OpRef(0)], OpRef(5)),
        make_op(OpCode::FloatNeg, &[OpRef(5)], OpRef(6)),
        make_op(OpCode::FloatAbs, &[OpRef(6)], OpRef(7)),
        make_op(OpCode::FloatLt, &[OpRef(0), OpRef(1)], OpRef(8)),
        {
            let mut op = Op::new(OpCode::Finish, &[OpRef(7)]);
            op.fail_args = Some(smallvec![OpRef(7)]);
            op
        },
    ];

    let constants = HashMap::new();
    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

#[test]
fn test_call_generates_import() {
    let inputargs = vec![InputArg {
        index: 0,
        tp: Type::Int,
    }];

    let func_ptr = OpRef(10000);
    let mut constants = HashMap::new();
    constants.insert(10000, 42i64); // fake func_ptr

    let ops = vec![make_op(OpCode::CallI, &[func_ptr, OpRef(0)], OpRef(1)), {
        let mut op = Op::new(OpCode::Finish, &[OpRef(1)]);
        op.fail_args = Some(smallvec![OpRef(1)]);
        op
    }];

    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);

    // Verify the module has jit_call import
    let parser = wasmparser::Parser::new(0);
    let mut has_jit_call = false;
    for payload in parser.parse_all(&bytes) {
        if let Ok(wasmparser::Payload::ImportSection(imports)) = payload {
            for import in imports {
                if let Ok(import) = import {
                    if import.name == "jit_call" {
                        has_jit_call = true;
                    }
                }
            }
        }
    }
    assert!(has_jit_call, "module should import jit_call");
}

#[test]
fn test_guard_types() {
    let inputargs = vec![
        InputArg {
            index: 0,
            tp: Type::Int,
        },
        InputArg {
            index: 1,
            tp: Type::Int,
        },
    ];

    let ops = vec![
        Op::new(OpCode::Label, &[OpRef(0), OpRef(1)]),
        // GuardTrue
        make_guard(OpCode::GuardTrue, &[OpRef(0)], &[OpRef(0), OpRef(1)]),
        // GuardFalse
        make_guard(OpCode::GuardFalse, &[OpRef(1)], &[OpRef(0), OpRef(1)]),
        // GuardValue
        make_guard(OpCode::GuardValue, &[OpRef(0), OpRef(1)], &[OpRef(0)]),
        // GuardNonnull
        make_guard(OpCode::GuardNonnull, &[OpRef(0)], &[OpRef(0)]),
        // GuardIsnull
        make_guard(OpCode::GuardIsnull, &[OpRef(1)], &[OpRef(1)]),
        // GuardNoOverflow (0 args)
        {
            let mut op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.fail_args = Some(smallvec![OpRef(0)]);
            op
        },
        // GuardNotInvalidated (0 args, always pass)
        {
            let mut op = Op::new(OpCode::GuardNotInvalidated, &[]);
            op.fail_args = Some(smallvec![OpRef(0)]);
            op
        },
        Op::new(OpCode::Jump, &[OpRef(0), OpRef(1)]),
    ];

    let constants = HashMap::new();
    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 7);
}

/// Verify GuardGcType lowering matches RPython's
/// `_cmp_guard_gc_type(loc_object, loc_expected_typeid)` (assembler.py:
/// 1919-1922): arg1 is an immediate typeid, NOT a classptr.
#[test]
fn test_guard_gc_type_uses_immediate_typeid() {
    let inputargs = vec![InputArg {
        index: 0,
        tp: Type::Int,
    }];

    // OpRef(10000) holds the immediate typeid 0x42
    let mut constants = HashMap::new();
    constants.insert(10_000, 0x42_i64);

    let ops = vec![
        Op::new(OpCode::Label, &[OpRef(0)]),
        make_guard(OpCode::GuardGcType, &[OpRef(0), OpRef(10_000)], &[OpRef(0)]),
        Op::new(OpCode::Jump, &[OpRef(0)]),
    ];

    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

/// Verify GuardIsObject lowering matches RPython's
/// `genop_guard_guard_is_object` (assembler.py:1924-1943): reads the
/// typeid at offset 0, indexes the type_info_group, and tests the
/// `T_IS_RPYTHON_INSTANCE` bit. Requires both
/// `get_translated_info_for_typeinfo` and
/// `get_translated_info_for_guard_is_object` to be installed.
#[test]
fn test_guard_is_object_uses_translated_layout() {
    let inputargs = vec![InputArg {
        index: 0,
        tp: Type::Int,
    }];

    let ops = vec![
        Op::new(OpCode::Label, &[OpRef(0)]),
        make_guard(OpCode::GuardIsObject, &[OpRef(0)], &[OpRef(0)]),
        Op::new(OpCode::Jump, &[OpRef(0)]),
    ];

    let constants = HashMap::new();
    let layout = codegen::WasmTypeinfoLayout {
        // Synthetic type_info_group base; the actual address never gets
        // dereferenced because validate_wasm only checks well-formedness.
        typeinfo: Some((0x4000, 0, 64)),
        guard_is_object: Some((16, 0x01)),
        subclassrange_min_offset: None,
    };
    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        layout,
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 1);
}

#[test]
fn test_sameas_and_conversions() {
    let inputargs = vec![InputArg {
        index: 0,
        tp: Type::Int,
    }];

    let ops = vec![
        make_op(OpCode::SameAsI, &[OpRef(0)], OpRef(1)),
        make_op(OpCode::CastIntToFloat, &[OpRef(0)], OpRef(2)),
        make_op(OpCode::CastFloatToInt, &[OpRef(2)], OpRef(3)),
        make_op(OpCode::CastIntToPtr, &[OpRef(0)], OpRef(4)),
        make_op(OpCode::CastPtrToInt, &[OpRef(4)], OpRef(5)),
        make_op(OpCode::IntNeg, &[OpRef(0)], OpRef(6)),
        make_op(OpCode::IntInvert, &[OpRef(0)], OpRef(7)),
        make_op(OpCode::IntIsTrue, &[OpRef(0)], OpRef(8)),
        make_op(OpCode::IntIsZero, &[OpRef(0)], OpRef(9)),
        {
            let mut op = Op::new(OpCode::Finish, &[OpRef(9)]);
            op.fail_args = Some(smallvec![OpRef(9)]);
            op
        },
    ];

    let constants = HashMap::new();
    let (bytes, _) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
}

#[test]
fn test_overflow_ops() {
    let inputargs = vec![
        InputArg {
            index: 0,
            tp: Type::Int,
        },
        InputArg {
            index: 1,
            tp: Type::Int,
        },
    ];

    let ops = vec![
        make_op(OpCode::IntAddOvf, &[OpRef(0), OpRef(1)], OpRef(2)),
        {
            let mut op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.fail_args = Some(smallvec![OpRef(2)]);
            op
        },
        make_op(OpCode::IntSubOvf, &[OpRef(0), OpRef(1)], OpRef(3)),
        {
            let mut op = Op::new(OpCode::GuardNoOverflow, &[]);
            op.fail_args = Some(smallvec![OpRef(3)]);
            op
        },
        {
            let mut op = Op::new(OpCode::Finish, &[OpRef(2)]);
            op.fail_args = Some(smallvec![OpRef(2)]);
            op
        },
    ];

    let constants = HashMap::new();
    let (bytes, guards) = codegen::build_wasm_module(
        &inputargs,
        &ops,
        &constants,
        Some(0),
        &HashMap::new(),
        codegen::WasmTypeinfoLayout::default(),
    );
    validate_wasm(&bytes);
    assert_eq!(guards.len(), 3); // 2 GuardNoOverflow + 1 Finish
}
