//! End-to-end coverage for the native `_cffi_backend` module, run through the
//! same startup shape as the `pyrex` launcher.
//!
//! The programs are transcribed from `extra_tests/cffi_tests/test_c.py`, whose
//! upstream is `pypy/module/_cffi_backend/test/_backend_test_c.py`.  Only the
//! part of that file the module answers today is covered: primitives, `void`,
//! pointers, arrays, structs, unions, enums, function types and libraries.
//! An uncaught `assert` in a program surfaces here as a failing test, so a
//! passing test means every read-back assertion held.
//!
//! `_backend_test_c.py` calls into a C library built for the test suite; the
//! programs here call libc instead, through the handle `dlopen(NULL)` gives.

use std::rc::Rc;

use pyre_interpreter::call::{register_build_class, set_last_exec_ctx};
use pyre_interpreter::importing;
use pyre_interpreter::pyframe::PyFrame;
use pyre_interpreter::{Mode, PyExecutionContext, compile_source_with_filename};
use pyre_jit::eval::{eval_with_jit, init_jit_hooks, reset_gc_fresh_for_test};

/// The programs share the process-global GC singleton and builtin type state,
/// so they run one at a time regardless of cargo's parallel scheduling.
static SERIAL: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn run_harness(program: &str, name: &str) -> Result<(), String> {
    pyre_interpreter::stack_check::set_recursion_limit(5000)
        .map_err(|_| "set_recursion_limit failed".to_string())?;
    init_jit_hooks();
    reset_gc_fresh_for_test();

    let cwd = std::env::current_dir().map_err(|e| e.to_string())?;
    importing::init_sys_path(&cwd, cwd.as_os_str());
    importing::add_sys_path_0();
    importing::set_sys_argv(&[std::ffi::OsString::from(name)]);

    let code = compile_source_with_filename(program, Mode::Exec, name)
        .map_err(|e| format!("compile error: {e}"))?;

    register_build_class();

    let execution_context = Rc::new(PyExecutionContext::default());
    set_last_exec_ctx(Rc::as_ptr(&execution_context));

    let mut frame = PyFrame::new_with_context(code, execution_context)
        .map_err(|e| format!("frame setup error: {}", e.message))?;

    let canonical = frame.get_w_globals();
    let main_module = pyre_object::w_module_new_aliasing_dict("__main__", canonical);
    importing::set_sys_module("__main__", main_module);

    eval_with_jit(&mut frame, None).map_err(|e| format!("execution error: {}", e.message))?;
    Ok(())
}

fn run_on_worker(program: &'static str, name: &'static str) {
    let _serial = SERIAL.lock().unwrap_or_else(|e| e.into_inner());
    let handle = std::thread::Builder::new()
        .stack_size(256 * 1024 * 1024)
        .spawn(move || run_harness(program, name))
        .expect("spawn worker thread");
    handle.join().expect("worker thread panicked").expect(name);
}

/// One program covering every part of `_cffi_backend` the module answers
/// today, transcribed from `extra_tests/cffi_tests/test_c.py`.
///
/// It is a single `#[test]` on purpose: the module memoises every ctype in
/// process-global caches and roots it for the process, so a second program
/// in the same process would meet those caches holding addresses into the
/// heap `reset_gc_fresh_for_test` has already replaced.  Each section runs
/// through `exec` and reports on its own, so one run names every failure
/// rather than only the first.
#[test]
fn the_module_answers_every_ctype_family_it_has_ported() {
    const PROGRAM: &str = concat!(
        "import sys\n",
        "from _cffi_backend import *\n",
        "from _cffi_backend import _get_common_types, __version__\n",
        "def raises(exc, fn, *a):\n",
        "    try:\n",
        "        fn(*a)\n",
        "    except exc:\n",
        "        return\n",
        "    raise AssertionError('expected ' + exc.__name__)\n",
        "def raises_str(exc, text, fn, *a):\n",
        "    try:\n",
        "        fn(*a)\n",
        "    except exc as e:\n",
        "        assert str(e) == text, str(e)\n",
        "        return\n",
        "    raise AssertionError('expected ' + exc.__name__)\n",
        "_failures = []\n",
        "def _run(label, body):\n",
        "    try:\n",
        "        exec(body, globals())\n",
        "    except BaseException as e:\n",
        "        _failures.append(label + ': ' + type(e).__name__ + ': ' + str(e))\n",
        "        print('FAILED', _failures[-1])\n",
        "_run('''primitive_types_are_memoised_and_inspectable''', r'''",
        "assert __version__ == \"1.18.0.dev0\", __version__\n",
        "raises(KeyError, new_primitive_type, \"foo\")\n",
        "p = new_primitive_type(\"signed char\")\n",
        "assert repr(p) == \"<ctype 'signed char'>\", repr(p)\n",
        "assert p is new_primitive_type(\"signed char\")\n",
        "assert p.kind == \"primitive\"\n",
        "assert p.cname == \"signed char\"\n",
        "assert [n for n in dir(p) if not n.startswith('_')] == ['cname', 'kind']\n",
        "''')\n",
        "_run('''casting_to_a_signed_char_truncates_and_compares_by_value''', r'''",
        "p = new_primitive_type(\"signed char\")\n",
        "x = cast(p, -65 + 17*256)\n",
        "assert repr(x) == \"<cdata 'signed char' -65>\", repr(x)\n",
        "assert repr(type(x)) == \"<class '_cffi_backend._CDataBase'>\", repr(type(x))\n",
        "assert int(x) == -65\n",
        "x = cast(p, -66 + (1<<199)*256)\n",
        "assert repr(x) == \"<cdata 'signed char' -66>\", repr(x)\n",
        "assert int(x) == -66\n",
        "assert (x == cast(p, -66)) is True\n",
        "assert (x != cast(p, -66)) is False\n",
        "q = new_primitive_type(\"short\")\n",
        "assert (x == cast(q, -66)) is True\n",
        "assert (x != cast(q, -66)) is False\n",
        "raises(TypeError, sizeof, 42.5)\n",
        "assert sizeof(new_primitive_type(\"short\")) == 2\n",
        "''')\n",
        "_run('''integer_ctypes_wrap_at_their_own_width''', r'''",
        "for name in ['signed char', 'short', 'int', 'long', 'long long']:\n",
        "    p = new_primitive_type(name)\n",
        "    size = sizeof(p)\n",
        "    lo = -(1 << (8*size-1))\n",
        "    hi = (1 << (8*size-1)) - 1\n",
        "    assert int(cast(p, lo)) == lo, name\n",
        "    assert int(cast(p, hi)) == hi, name\n",
        "    assert int(cast(p, lo - 1)) == hi, name\n",
        "    assert int(cast(p, hi + 1)) == lo, name\n",
        "    raises(TypeError, cast, p, None)\n",
        "    assert int(cast(p, b'\\x08')) == 8\n",
        "    assert int(cast(p, '\\x08')) == 8\n",
        "for name in ['char', 'short', 'int', 'long', 'long long']:\n",
        "    p = new_primitive_type('unsigned ' + name)\n",
        "    size = sizeof(p)\n",
        "    hi = (1 << (8*size)) - 1\n",
        "    assert int(cast(p, 0)) == 0\n",
        "    assert int(cast(p, hi)) == hi, name\n",
        "    assert int(cast(p, -1)) == hi, name\n",
        "    assert int(cast(p, hi + 1)) == 0, name\n",
        "    assert int(cast(p, b'\\xFE')) == 254\n",
        "    assert int(cast(p, '\\xFE')) == 254\n",
        "''')\n",
        "_run('''float_and_character_ctypes_round_trip''', r'''",
        "INF = 1E200 * 1E200\n",
        "for name in [\"float\", \"double\"]:\n",
        "    p = new_primitive_type(name)\n",
        "    assert bool(cast(p, 0)) is False\n",
        "    assert bool(cast(p, INF)) is True\n",
        "    assert bool(cast(p, -INF)) is True\n",
        "    assert int(cast(p, -150)) == -150\n",
        "    assert int(cast(p, 61.91)) == 61\n",
        "    assert float(cast(p, 1.25)) == 1.25\n",
        "    assert float(cast(p, b'\\x09')) == 9.0\n",
        "    assert float(cast(p, '\\x09')) == 9.0\n",
        "    assert float(cast(p, True)) == 1.0\n",
        "    raises(TypeError, cast, p, None)\n",
        "p = new_primitive_type(\"char\")\n",
        "assert bool(cast(p, b'A')) is True\n",
        "assert bool(cast(p, b'\\x00')) is False\n",
        "assert cast(p, b'A') == cast(p, 65)\n",
        "assert int(cast(p, b'A')) == 65\n",
        "assert repr(cast(p, b'A')) == \"<cdata 'char' b'A'>\", repr(cast(p, b'A'))\n",
        "''')\n",
        "_run('''pointer_ctypes_are_memoised_and_spell_their_own_name''', r'''",
        "p1 = new_primitive_type(\"int\")\n",
        "p2 = new_pointer_type(p1)\n",
        "assert repr(p2) == \"<ctype 'int *'>\", repr(p2)\n",
        "assert p2 is new_pointer_type(p1)\n",
        "assert repr(new_pointer_type(p2)) == \"<ctype 'int * *'>\", repr(new_pointer_type(p2))\n",
        "assert p2.kind == \"pointer\"\n",
        "assert p2.cname == \"int *\"\n",
        "assert p2.item is p1\n",
        "assert [n for n in dir(p2) if not n.startswith('_')] == ['cname', 'item', 'kind']\n",
        "''')\n",
        "_run('''newp_owns_one_int_and_indexes_only_zero''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "raises(TypeError, newp, BInt)\n",
        "BPtr = new_pointer_type(BInt)\n",
        "p = newp(BPtr)\n",
        "assert repr(p) == \"<cdata 'int *' owning 4 bytes>\", repr(p)\n",
        "assert p[0] == 0\n",
        "p = newp(BPtr, None)\n",
        "assert p[0] == 0\n",
        "p = newp(BPtr, 5000)\n",
        "assert p[0] == 5000\n",
        "raises(IndexError, lambda: p[1])\n",
        "raises(IndexError, lambda: p[-1])\n",
        "p[0] = -12\n",
        "assert p[0] == -12\n",
        "q = cast(BPtr, p)\n",
        "assert repr(q).startswith(\"<cdata 'int *' 0x\"), repr(q)\n",
        "assert q[0] == -12\n",
        "''')\n",
        "_run('''the_void_ctype_can_be_neither_cast_to_nor_instantiated''', r'''",
        "p = new_void_type()\n",
        "assert p is new_void_type()\n",
        "assert p.kind == \"void\"\n",
        "assert p.cname == \"void\"\n",
        "assert [n for n in dir(p) if not n.startswith('_')] == ['cname', 'kind']\n",
        "raises(TypeError, newp, p, None)\n",
        "raises(TypeError, cast, p, 42)\n",
        "assert sizeof(new_pointer_type(p)) == sizeof(new_pointer_type(new_primitive_type(\"int\")))\n",
        "''')\n",
        "_run('''array_ctypes_nest_their_names_and_refuse_an_overflowing_length''', r'''",
        "p = new_primitive_type(\"int\")\n",
        "raises(TypeError, new_array_type, new_pointer_type(p), \"foo\")\n",
        "p1 = new_array_type(new_pointer_type(p), None)\n",
        "assert repr(p1) == \"<ctype 'int[]'>\", repr(p1)\n",
        "assert p1 is new_array_type(new_pointer_type(p), None)\n",
        "assert repr(new_pointer_type(p1)) == \"<ctype 'int(*)[]'>\", repr(new_pointer_type(p1))\n",
        "p1 = new_array_type(new_pointer_type(p), 42)\n",
        "p2 = new_array_type(new_pointer_type(p1), 25)\n",
        "assert repr(p2) == \"<ctype 'int[25][42]'>\", repr(p2)\n",
        "assert repr(new_pointer_type(p2)) == \"<ctype 'int(*)[25][42]'>\", repr(new_pointer_type(p2))\n",
        "raises(OverflowError, new_array_type, new_pointer_type(p), sys.maxsize+1)\n",
        "raises(OverflowError, new_array_type, new_pointer_type(p), sys.maxsize // 3)\n",
        "assert p1.kind == \"array\"\n",
        "assert p1.cname == \"int[42]\"\n",
        "assert p1.item is p\n",
        "assert p1.length == 42\n",
        "assert new_array_type(new_pointer_type(p), None).length is None\n",
        "assert [n for n in dir(p1) if not n.startswith('_')] == ['cname', 'item', 'kind', 'length']\n",
        "''')\n",
        "_run('''array_cdata_reads_writes_iterates_and_bounds_check''', r'''",
        "p = new_primitive_type(\"int\")\n",
        "LENGTH = 1423\n",
        "p1 = new_array_type(new_pointer_type(p), LENGTH)\n",
        "a = newp(p1, None)\n",
        "assert repr(a) == \"<cdata 'int[%d]' owning %d bytes>\" % (LENGTH, LENGTH*4), repr(a)\n",
        "assert len(a) == LENGTH\n",
        "for i in range(LENGTH):\n",
        "    assert a[i] == 0\n",
        "raises(IndexError, lambda: a[LENGTH])\n",
        "raises(IndexError, lambda: a[-1])\n",
        "for i in range(LENGTH):\n",
        "    a[i] = i * i + 1\n",
        "for i in range(LENGTH):\n",
        "    assert a[i] == i * i + 1\n",
        "\n",
        "pu = new_array_type(new_pointer_type(p), None)\n",
        "raises(TypeError, newp, pu)\n",
        "raises(ValueError, newp, pu, -1)\n",
        "assert len(newp(pu, 42)) == 42\n",
        "a = newp(pu, list(range(100, 110)))\n",
        "assert len(a) == 10\n",
        "for i in range(10):\n",
        "    assert a[i] == 100 + i\n",
        "raises(IndexError, lambda: a[10])\n",
        "assert list(a) == list(range(100, 110))\n",
        "\n",
        "p2 = new_array_type(new_pointer_type(p), 42)\n",
        "a = newp(p2, list(range(100, 110)))\n",
        "for i in range(10):\n",
        "    assert a[i] == 100 + i\n",
        "for i in range(10, 42):\n",
        "    assert a[i] == 0\n",
        "''')\n",
        "_run('''pointer_arithmetic_and_alignment''', r'''",
        "p = new_primitive_type(\"int\")\n",
        "p1 = new_array_type(new_pointer_type(p), 5)\n",
        "p2 = new_array_type(new_pointer_type(p1), 3)\n",
        "a = newp(p2, [[1, 2], [3, 4], [5, 6]])\n",
        "assert a[0][0] == 1\n",
        "assert a[2][1] == 6\n",
        "assert repr(a + 1).startswith(\"<cdata 'int(*)[5]' 0x\"), repr(a + 1)\n",
        "BInt = new_primitive_type(\"int\")\n",
        "assert alignof(BInt) == sizeof(BInt)\n",
        "BPtr = new_pointer_type(BInt)\n",
        "assert alignof(BPtr) == sizeof(BPtr)\n",
        "assert alignof(new_array_type(BPtr, None)) == alignof(BInt)\n",
        "''')\n",
        "_run('''string_and_unpack_read_a_char_and_int_array''', r'''",
        "BChar = new_primitive_type(\"char\")\n",
        "BArray = new_array_type(new_pointer_type(BChar), 10)\n",
        "a = newp(BArray, b\"hello\")\n",
        "assert len(a) == 10\n",
        "assert string(a) == b\"hello\"\n",
        "BInt = new_primitive_type(\"int\")\n",
        "BIntArray = new_array_type(new_pointer_type(BInt), 5)\n",
        "b = newp(BIntArray, [10, 20, 30, 40, 50])\n",
        "assert unpack(b, 5) == [10, 20, 30, 40, 50]\n",
        "''')\n",
        "_run('''the_module_publishes_its_abi_and_common_type_tables''', r'''",
        "FFI_DEFAULT_ABI\n",
        "FFI_CDECL\n",
        "RTLD_LAZY\n",
        "RTLD_NOW\n",
        "RTLD_GLOBAL\n",
        "RTLD_LOCAL\n",
        "d = {}\n",
        "_get_common_types(d)\n",
        "assert d[\"bool\"] == \"_Bool\", d.get(\"bool\")\n",
        "''')\n",
        "_run('''struct_types_declare_complete_and_lay_out_fields''', r'''",
        "BStruct = new_struct_type(\"foo\")\n",
        "assert repr(BStruct) == \"<ctype 'foo'>\", repr(BStruct)\n",
        "BStruct = new_struct_type(\"struct foo\")\n",
        "assert repr(BStruct) == \"<ctype 'struct foo'>\", repr(BStruct)\n",
        "assert repr(new_pointer_type(BStruct)) == \"<ctype 'struct foo *'>\"\n",
        "raises(ValueError, sizeof, BStruct)\n",
        "raises(ValueError, alignof, BStruct)\n",
        "BLong = new_primitive_type(\"long\")\n",
        "BChar = new_primitive_type(\"char\")\n",
        "BShort = new_primitive_type(\"short\")\n",
        "assert BStruct.kind == \"struct\"\n",
        "assert BStruct.cname == \"struct foo\"\n",
        "assert BStruct.fields is None\n",
        "assert [n for n in dir(BStruct) if not n.startswith('_')] == ['cname', 'fields', 'kind']\n",
        "complete_struct_or_union(BStruct, [('a1', BLong, -1), ('a2', BChar, -1), ('a3', BShort, -1)])\n",
        "d = BStruct.fields\n",
        "assert len(d) == 3\n",
        "assert d[0][0] == 'a1' and d[0][1].type is BLong\n",
        "assert d[0][1].offset == 0 and d[0][1].bitshift == -1 and d[0][1].bitsize == -1\n",
        "assert d[1][0] == 'a2' and d[1][1].type is BChar\n",
        "assert d[1][1].offset == sizeof(BLong)\n",
        "assert d[2][0] == 'a3' and d[2][1].type is BShort\n",
        "assert d[2][1].offset == sizeof(BLong) + sizeof(BShort)\n",
        "assert sizeof(BStruct) == 2 * sizeof(BLong)\n",
        "assert alignof(BStruct) == alignof(BLong)\n",
        "''')\n",
        "_run('''union_types_overlay_their_fields''', r'''",
        "BLong = new_primitive_type(\"long\")\n",
        "BChar = new_primitive_type(\"char\")\n",
        "BUnion = new_union_type(\"union foo\")\n",
        "assert repr(BUnion) == \"<ctype 'union foo'>\", repr(BUnion)\n",
        "assert repr(new_pointer_type(BUnion)) == \"<ctype 'union foo *'>\"\n",
        "assert BUnion.kind == \"union\"\n",
        "assert BUnion.cname == \"union foo\"\n",
        "assert BUnion.fields is None\n",
        "complete_struct_or_union(BUnion, [('a1', BLong, -1), ('a2', BChar, -1)])\n",
        "d = BUnion.fields\n",
        "assert len(d) == 2\n",
        "assert d[0][0] == 'a1' and d[0][1].type is BLong and d[0][1].offset == 0\n",
        "assert d[1][0] == 'a2' and d[1][1].type is BChar and d[1][1].offset == 0\n",
        "assert sizeof(BUnion) == sizeof(BLong)\n",
        "assert alignof(BUnion) == alignof(BLong)\n",
        "''')\n",
        "_run('''struct_cdata_reads_and_writes_its_fields''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "BStruct = new_struct_type(\"struct foo\")\n",
        "BStructPtr = new_pointer_type(BStruct)\n",
        "p = cast(BStructPtr, 42)\n",
        "raises_str(AttributeError, \"cdata 'struct foo *' points to an opaque type: cannot read fields\", lambda: p.a1)\n",
        "raises_str(AttributeError, \"cdata 'struct foo *' points to an opaque type: cannot write fields\", setattr, p, 'a1', 10)\n",
        "complete_struct_or_union(BStruct, [('a1', BInt, -1), ('a2', BInt, -1)])\n",
        "p = newp(BStructPtr, None)\n",
        "s = p[0]\n",
        "assert s.a1 == 0\n",
        "s.a2 = 123\n",
        "assert s.a1 == 0 and s.a2 == 123\n",
        "assert p.a2 == 123\n",
        "p.a1 = 5\n",
        "assert s.a1 == 5\n",
        "raises(OverflowError, setattr, s, 'a1', sys.maxsize + 1)\n",
        "assert s.a1 == 5\n",
        "raises_str(AttributeError, \"cdata 'struct foo *' has no field 'foobar'\", lambda: p.foobar)\n",
        "raises_str(AttributeError, \"cdata 'struct foo *' has no field 'foobar'\", setattr, p, 'foobar', 42)\n",
        "raises_str(AttributeError, \"cdata 'struct foo' has no field 'foobar'\", lambda: s.foobar)\n",
        "raises_str(AttributeError, \"cdata 'struct foo' has no field 'foobar'\", setattr, s, 'foobar', 42)\n",
        "j = cast(BInt, 42)\n",
        "raises_str(AttributeError, \"cdata 'int' has no attribute 'foobar'\", lambda: j.foobar)\n",
        "raises_str(AttributeError, \"cdata 'int' has no attribute 'foobar'\", setattr, j, 'foobar', 42)\n",
        "k = cast(new_pointer_type(BInt), 42)\n",
        "raises_str(AttributeError, \"cdata 'int *' has no attribute 'foobar'\", lambda: k.foobar)\n",
        "pp = newp(new_pointer_type(BStructPtr), p)\n",
        "raises_str(AttributeError, \"cdata 'struct foo * *' has no attribute 'a1'\", lambda: pp.a1)\n",
        "assert sorted(dir(p)) == ['a1', 'a2'], dir(p)\n",
        "assert sorted(dir(s)) == ['a1', 'a2'], dir(s)\n",
        "q = newp(BStructPtr, [10, 20])\n",
        "assert q.a1 == 10 and q.a2 == 20\n",
        "q = newp(BStructPtr, {'a2': 30})\n",
        "assert q.a1 == 0 and q.a2 == 30\n",
        "''')\n",
        "_run('''union_cdata_aliases_one_storage''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "BUInt = new_primitive_type(\"unsigned int\")\n",
        "BUnion = new_union_type(\"union bar\")\n",
        "complete_struct_or_union(BUnion, [('a1', BInt, -1), ('a2', BUInt, -1)])\n",
        "bigval = -42 + (1 << (8 * sizeof(BInt)))\n",
        "p = newp(new_pointer_type(BUnion), [-42])\n",
        "assert p.a1 == -42\n",
        "assert p.a2 == bigval\n",
        "p = newp(new_pointer_type(BUnion), {'a2': bigval})\n",
        "assert p.a1 == -42\n",
        "assert p.a2 == bigval\n",
        "raises(OverflowError, newp, new_pointer_type(BUnion), {'a1': bigval})\n",
        "p = newp(new_pointer_type(BUnion), [])\n",
        "assert p.a1 == p.a2 == 0\n",
        "''')\n",
        "_run('''bitfields_pack_into_their_declared_widths''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "BUnsignedInt = new_primitive_type(\"unsigned int\")\n",
        "BStruct = new_struct_type(\"struct foo\")\n",
        "complete_struct_or_union(BStruct, [('a1', BInt, 1), ('a2', BUnsignedInt, 2), ('a3', BInt, 3)])\n",
        "assert sizeof(BStruct) == sizeof(BInt)\n",
        "p = newp(new_pointer_type(BStruct), None)\n",
        "p.a1 = -1\n",
        "assert p.a1 == -1\n",
        "p.a1 = 0\n",
        "raises(OverflowError, setattr, p, 'a1', 2)\n",
        "assert p.a1 == 0\n",
        "p.a1 = -1\n",
        "p.a2 = 3\n",
        "p.a3 = -4\n",
        "raises(OverflowError, setattr, p, 'a3', 4)\n",
        "raises_str(OverflowError, \"value -5 outside the range allowed by the bit field width: -4 <= x <= 3\", setattr, p, 'a3', -5)\n",
        "assert p.a1 == -1 and p.a2 == 3 and p.a3 == -4\n",
        "p.a1 = 1\n",
        "assert p.a1 == -1\n",
        "raises_str(OverflowError, \"value -2 outside the range allowed by the bit field width: -1 <= x <= 1\", setattr, p, 'a1', -2)\n",
        "BStruct2 = new_struct_type(\"struct foo2\")\n",
        "complete_struct_or_union(BStruct2, [('a1', BInt, 1)])\n",
        "q = newp(new_pointer_type(BStruct2), [-1])\n",
        "assert q.a1 == -1\n",
        "q = newp(new_pointer_type(BStruct2), {'a1': -1})\n",
        "assert q.a1 == -1\n",
        "BUnion2 = new_union_type(\"union bar2\")\n",
        "complete_struct_or_union(BUnion2, [('a1', BInt, 1)])\n",
        "u = newp(new_pointer_type(BUnion2), [-1])\n",
        "assert u.a1 == -1\n",
        "raises(TypeError, typeoffsetof, BStruct2, 'a1')\n",
        "''')\n",
        "_run('''enum_types_map_names_to_values_both_ways''', r'''",
        "BUInt = new_primitive_type(\"unsigned int\")\n",
        "BEnum = new_enum_type(\"foo\", (), (), BUInt)\n",
        "assert repr(BEnum) == \"<ctype 'foo'>\", repr(BEnum)\n",
        "assert BEnum.kind == \"enum\"\n",
        "assert BEnum.cname == \"foo\"\n",
        "assert BEnum.elements == {}\n",
        "BInt = new_primitive_type(\"int\")\n",
        "BEnum = new_enum_type(\"enum foo\", ('def', 'c', 'ab'), (0, 1, -20), BInt)\n",
        "assert BEnum.cname == \"enum foo\"\n",
        "assert BEnum.elements == {-20: 'ab', 0: 'def', 1: 'c'}, BEnum.elements\n",
        "BEnum.elements[2] = '??'\n",
        "assert BEnum.elements == {-20: 'ab', 0: 'def', 1: 'c'}\n",
        "BEnum2 = new_enum_type(\"enum bar\", ('ab', 'cd'), (5, 5), BUInt)\n",
        "assert BEnum2.elements == {5: 'ab'}\n",
        "assert BEnum2.relements == {'ab': 5, 'cd': 5}\n",
        "assert sizeof(BEnum) == sizeof(BInt)\n",
        "e = cast(BEnum, 0)\n",
        "assert repr(e) == \"<cdata 'enum foo' 0: def>\", repr(e)\n",
        "assert repr(cast(BEnum, -42)) == \"<cdata 'enum foo' -42>\"\n",
        "assert repr(cast(BEnum, -20)) == \"<cdata 'enum foo' -20: ab>\"\n",
        "assert string(e) == 'def'\n",
        "assert string(cast(BEnum, -20)) == 'ab'\n",
        "assert int(cast(BEnum, 1)) == 1\n",
        "assert int(cast(BEnum, -242 + 2**128)) == -242\n",
        "assert string(cast(BEnum, -242 + 2**128)) == '-242'\n",
        "BEnum3 = new_enum_type(\"enum bar\", ('def', 'c', 'ab'), (0, 1, 20), BUInt)\n",
        "assert repr(cast(BEnum3, -1)) == \"<cdata 'enum bar' 4294967295>\", repr(cast(BEnum3, -1))\n",
        "BLong = new_primitive_type(\"long\")\n",
        "BEnum4 = new_enum_type(\"enum baz\", (), (), BLong)\n",
        "assert sizeof(BEnum4) == sizeof(BLong)\n",
        "assert repr(cast(BEnum4, -1)) == \"<cdata 'enum baz' -1>\"\n",
        "BEnum5 = new_enum_type(\"enum foo\", ('ab', 'cd'), (7, 7), BInt)\n",
        "assert repr(cast(BEnum5, 7)) == \"<cdata 'enum foo' 7: ab>\"\n",
        "assert string(cast(BEnum5, 7)) == 'ab'\n",
        "BStruct = new_struct_type(\"struct bar\")\n",
        "BStructPtr = new_pointer_type(BStruct)\n",
        "complete_struct_or_union(BStruct, [('a1', BEnum, -1)])\n",
        "p = newp(BStructPtr, [-20])\n",
        "assert p.a1 == -20\n",
        "p = newp(BStructPtr, [12])\n",
        "assert p.a1 == 12\n",
        "raises(TypeError, newp, BStructPtr, [None])\n",
        "raises(TypeError, setattr, p, 'a1', \"def\")\n",
        "''')\n",
        "_run('''function_ctypes_name_themselves_and_memoise''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "BFunc = new_function_type((BInt, BInt), BInt, False)\n",
        "assert repr(BFunc) == \"<ctype 'int(*)(int, int)'>\", repr(BFunc)\n",
        "assert BFunc is new_function_type((BInt, BInt), BInt, False)\n",
        "BFunc2 = new_function_type((), BFunc, False)\n",
        "assert repr(BFunc2) == \"<ctype 'int(*(*)())(int, int)'>\", repr(BFunc2)\n",
        "assert BFunc.kind == \"function\"\n",
        "assert BFunc.cname == \"int(*)(int, int)\"\n",
        "assert BFunc.args == (BInt, BInt)\n",
        "assert BFunc.result is BInt\n",
        "assert BFunc.ellipsis is False\n",
        "assert BFunc.abi == FFI_DEFAULT_ABI\n",
        "assert sizeof(BFunc) == sizeof(new_pointer_type(BInt))\n",
        "assert alignof(BFunc) == alignof(new_pointer_type(BInt))\n",
        "BChar = new_primitive_type(\"char\")\n",
        "BShort = new_primitive_type(\"short\")\n",
        "BStruct = new_struct_type(\"struct foo\")\n",
        "complete_struct_or_union(BStruct, [('a1', BChar, -1), ('a2', BShort, -1)])\n",
        "assert repr(new_function_type((BStruct,), BShort, False)) == \"<ctype 'short(*)(struct foo)'>\"\n",
        "BVoid = new_void_type()\n",
        "assert repr(new_function_type((BInt, BInt), BVoid, False)) == \"<ctype 'void(*)(int, int)'>\"\n",
        "raises(TypeError, new_function_type, (BVoid,), BInt, False)\n",
        "BEllipsis = new_function_type((BInt,), BInt, True)\n",
        "assert repr(BEllipsis) == \"<ctype 'int(*)(int, ...)'>\", repr(BEllipsis)\n",
        "assert BEllipsis.ellipsis is True\n",
        "BOpaque = new_struct_type(\"struct opaque\")\n",
        "raises(TypeError, new_function_type, (BInt,), BOpaque, False)\n",
        "''')\n",
        "_run('''typeoffsetof_and_rawaddressof_reach_a_struct_field''', r'''",
        "BChar = new_primitive_type(\"char\")\n",
        "BCharP = new_pointer_type(BChar)\n",
        "BStruct = new_struct_type(\"struct foo\")\n",
        "BStructPtr = new_pointer_type(BStruct)\n",
        "complete_struct_or_union(BStruct, [('a1', BChar, -1), ('a2', BChar, -1), ('a3', BChar, -1)])\n",
        "raises(TypeError, typeoffsetof, BStructPtr, None)\n",
        "raises(TypeError, typeoffsetof, BStruct, None)\n",
        "assert typeoffsetof(BStructPtr, 'a1') == (BChar, 0)\n",
        "assert typeoffsetof(BStruct, 'a1') == (BChar, 0)\n",
        "assert typeoffsetof(BStructPtr, 'a2') == (BChar, 1)\n",
        "assert typeoffsetof(BStruct, 'a3') == (BChar, 2)\n",
        "assert typeoffsetof(BStructPtr, 'a2', 0) == (BChar, 1)\n",
        "raises(TypeError, typeoffsetof, BStructPtr, 'a2', 1)\n",
        "raises(KeyError, typeoffsetof, BStructPtr, 'a4')\n",
        "raises(KeyError, typeoffsetof, BStruct, 'a5')\n",
        "raises(TypeError, typeoffsetof, BStruct, 42)\n",
        "raises(TypeError, typeoffsetof, BChar, 'a1')\n",
        "p = newp(BStructPtr, None)\n",
        "assert repr(p) == \"<cdata 'struct foo *' owning 3 bytes>\", repr(p)\n",
        "s = p[0]\n",
        "assert repr(s) == \"<cdata 'struct foo' owning 3 bytes>\", repr(s)\n",
        "a = rawaddressof(BStructPtr, s, 0)\n",
        "assert repr(a).startswith(\"<cdata 'struct foo *' 0x\"), repr(a)\n",
        "raises(TypeError, rawaddressof, BStruct, s, 0)\n",
        "assert rawaddressof(BCharP, s, 0) == cast(BCharP, p)\n",
        "assert rawaddressof(BStructPtr, a, 0) == a\n",
        "raises(TypeError, rawaddressof, BStructPtr, cast(BChar, b'?'), 0)\n",
        "assert rawaddressof(BCharP, s, 1) == cast(BCharP, p) + 1\n",
        "''')\n",
        "_run('''a_library_loads_and_its_functions_can_be_called''', r'''",
        "BChar = new_primitive_type(\"char\")\n",
        "BCharP = new_pointer_type(BChar)\n",
        "BInt = new_primitive_type(\"int\")\n",
        "BSizeT = new_primitive_type(\"size_t\")\n",
        "BDouble = new_primitive_type(\"double\")\n",
        "ll = load_library(None, RTLD_NOW)\n",
        "assert repr(ll).startswith(\"<clibrary \"), repr(ll)\n",
        "strlen = ll.load_function(new_function_type((BCharP,), BSizeT, False), \"strlen\")\n",
        "assert strlen(b\"hello\") == 5\n",
        "assert strlen(b\"\") == 0\n",
        "BStrcmp = new_function_type((BCharP, BCharP), BInt, False)\n",
        "strcmp = ll.load_function(BStrcmp, \"strcmp\")\n",
        "assert strcmp(b\"abc\", b\"abc\") == 0\n",
        "assert strcmp(b\"abc\", b\"abd\") < 0\n",
        "assert strcmp(b\"abd\", b\"abc\") > 0\n",
        "abs_ = ll.load_function(new_function_type((BInt,), BInt, False), \"abs\")\n",
        "assert abs_(-42) == 42\n",
        "atof = ll.load_function(new_function_type((BCharP,), BDouble, False), \"atof\")\n",
        "assert atof(b\"1.25\") == 1.25\n",
        "raises(AttributeError, ll.load_function, BStrcmp, \"no_such_symbol_at_all\")\n",
        "raises(TypeError, strcmp, b\"abc\")\n",
        "raises(TypeError, strcmp, b\"abc\", b\"abd\", b\"abe\")\n",
        "''')\n",
        "_run('''a_c_call_returns_a_struct_by_value_and_takes_varargs''', r'''",
        "BChar = new_primitive_type(\"char\")\n",
        "BCharP = new_pointer_type(BChar)\n",
        "BInt = new_primitive_type(\"int\")\n",
        "BSizeT = new_primitive_type(\"size_t\")\n",
        "ll = load_library(None, RTLD_NOW)\n",
        "BDivT = new_struct_type(\"struct div_t\")\n",
        "complete_struct_or_union(BDivT, [('quot', BInt, -1), ('rem', BInt, -1)])\n",
        "div = ll.load_function(new_function_type((BInt, BInt), BDivT, False), \"div\")\n",
        "r = div(17, 5)\n",
        "assert r.quot == 3 and r.rem == 2, (r.quot, r.rem)\n",
        "BCharArray = new_array_type(BCharP, 32)\n",
        "buf = newp(BCharArray, None)\n",
        "snprintf = ll.load_function(new_function_type((BCharP, BSizeT, BCharP), BInt, True), \"snprintf\")\n",
        "n = snprintf(buf, 32, b\"[%d]\", cast(BInt, 42))\n",
        "assert n == 4, n\n",
        "assert string(buf) == b\"[42]\", string(buf)\n",
        "''')\n",
        "_run('''a_library_reads_and_writes_a_data_symbol_and_then_closes''', r'''",
        "BInt = new_primitive_type(\"int\")\n",
        "BVoidP = new_pointer_type(new_void_type())\n",
        "ll = load_library(None, RTLD_NOW)\n",
        "name = \"__stderrp\" if sys.platform == \"darwin\" else \"stderr\"\n",
        "assert ll.read_variable(BVoidP, name)\n",
        "saved = ll.read_variable(BInt, \"optind\")\n",
        "ll.write_variable(BInt, \"optind\", 12345)\n",
        "assert ll.read_variable(BInt, \"optind\") == 12345\n",
        "ll.write_variable(BInt, \"optind\", saved)\n",
        "assert ll.read_variable(BInt, \"optind\") == saved\n",
        "raises(KeyError, ll.read_variable, BInt, \"no_such_variable_at_all\")\n",
        "ll.close_lib()\n",
        "raises(ValueError, ll.read_variable, BInt, \"optind\")\n",
        "raises(ValueError, ll.write_variable, BInt, \"optind\", 0)\n",
        "raises(ValueError, ll.load_function, new_function_type((BInt,), BInt, False), \"abs\")\n",
        "''')\n",
        "if _failures:\n",
        "    raise AssertionError('; '.join(_failures))\n",
    );
    run_on_worker(PROGRAM, "cffi_backend");
}
