//! Generator wrapper for the integer optimization rule DSL.
//!
//! RPython counterpart: `rpython/jit/metainterp/ruleopt/generate.py`.

use std::path::{Path, PathBuf};

use crate::ruleopt::{REAL_RULES, codegen, parse, rust_codegen};

/// Python header written by PyPy `ruleopt/generate.py` before the generated
/// `OptIntAutoGenerated` mixin body.
pub const AUTOGENINTRULES_HEADER: &str = r#"# Generated by ruleopt/generate.py, don't edit!

import sys
from rpython.jit.metainterp.history import ConstInt
from rpython.jit.metainterp.optimizeopt.util import (
    get_box_replacement)
from rpython.jit.metainterp.resoperation import rop

from rpython.rlib.rarithmetic import LONG_BIT, r_uint, intmask, ovfcheck, uint_mul_high, highest_bit
MAXINT = sys.maxint
MININT = -sys.maxint - 1

"#;

/// Fixed preamble for the generated Rust `OptIntAutoGenerated` mixin.
pub const RUST_AUTOGEN_HEADER: &str = r#"//! Generated from `rpython/jit/metainterp/ruleopt/real.rules` by
//! `ruleopt/rust_codegen.rs`; do not edit by hand. Regenerate via the
//! `ruleopt::generate::generate_rust_real_rules` path.
//!
//! Defines `OptIntAutoGenerated`, mixed into `OptIntBounds` (intbounds.rs)
//! (`objectmodel.import_from_mixin`).

use crate::optimizeopt::intbounds::OptIntBounds;
use crate::optimizeopt::intutils::IntBound;
use crate::optimizeopt::{OptContext, OptimizationResult};
use majit_ir::{Op, OpCode, operand::Operand};
use std::sync::atomic::{AtomicU64, Ordering};

"#;

/// Upstream `def_file = os.path.join(here, "real.rules")`.
pub fn def_file(ruleopt_dir: impl AsRef<Path>) -> PathBuf {
    ruleopt_dir.as_ref().join("real.rules")
}

/// Upstream `out_file = os.path.join(here, "..", "optimizeopt",
/// "autogenintrules.py")`.
pub fn out_file(ruleopt_dir: impl AsRef<Path>) -> PathBuf {
    ruleopt_dir
        .as_ref()
        .join("..")
        .join("optimizeopt")
        .join("autogenintrules.py")
}

/// Generate the `OptIntAutoGenerated` mixin body from already-parsed rules.
pub fn generate_mixin(ast: &parse::File) -> String {
    let mut cgen = codegen::Codegen::new();
    cgen.generate_mixin(ast)
}

/// Parse rule source and generate the complete `autogenintrules.py` text.
///
/// PyPy calls `proof.prove_source(content)` before codegen; the Rust proof
/// module is still a separate parity item, so this wrapper mirrors the
/// generation step over the typed AST produced by `parse`.
pub fn generate_source(content: &str) -> Result<String, parse::RuleParseError> {
    let ast = parse::parse(content)?;
    Ok(format!(
        "{}\n{}",
        AUTOGENINTRULES_HEADER,
        generate_mixin(&ast)
    ))
}

/// Generate from the vendored PyPy `real.rules` source.
pub fn generate_real_rules() -> Result<String, parse::RuleParseError> {
    generate_source(REAL_RULES)
}

/// Generate the Rust `OptIntAutoGenerated` mixin from already-parsed rules.
pub fn generate_rust_mixin(ast: &parse::File) -> String {
    let mut cgen = rust_codegen::RustCodegen::new();
    cgen.generate_mixin(ast)
}

/// Parse rule source and generate the complete Rust mixin source.
pub fn generate_rust_source(content: &str) -> Result<String, parse::RuleParseError> {
    let ast = parse::parse(content)?;
    Ok(format!(
        "{}{}",
        RUST_AUTOGEN_HEADER,
        generate_rust_mixin(&ast)
    ))
}

/// Generate Rust source from the vendored `real.rules` source of truth.
pub fn generate_rust_real_rules() -> Result<String, parse::RuleParseError> {
    generate_rust_source(REAL_RULES)
}

/// Rust library counterpart of PyPy `main(argv)` (`generate.py:7`).
///
/// PyPy's script writes `optimizeopt/autogenintrules.py` as a CLI side effect.
/// This module is consumed as a library, so the parity entry point returns the
/// generated source and leaves the destination choice to the caller.
pub fn main(_argv: &[String]) -> Result<String, parse::RuleParseError> {
    generate_real_rules()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_paths_follow_generate_py() {
        let here = Path::new("rpython/jit/metainterp/ruleopt");
        assert_eq!(
            def_file(here),
            PathBuf::from("rpython/jit/metainterp/ruleopt/real.rules")
        );
        assert_eq!(
            out_file(here),
            PathBuf::from("rpython/jit/metainterp/ruleopt/../optimizeopt/autogenintrules.py")
        );
    }

    #[test]
    fn test_generate_source_header_and_mixin() {
        let source = "add_zero: int_add(x, 0)\n    => x\n";
        let generated = generate_source(source).unwrap();
        assert!(generated.starts_with(AUTOGENINTRULES_HEADER));
        assert!(generated.contains("class OptIntAutoGenerated(object):"));
        assert!(generated.contains("def optimize_INT_ADD(self, op):"));
    }

    #[test]
    fn test_generate_real_rules() {
        let generated = generate_real_rules().unwrap();
        assert!(generated.contains("def optimize_INT_ADD(self, op):"));
        assert!(generated.contains("def optimize_UINT_RSHIFT(self, op):"));
    }

    #[test]
    fn test_main_generates_real_rules() {
        let generated = main(&[]).unwrap();
        assert!(generated.contains("class OptIntAutoGenerated(object):"));
        assert!(generated.contains("def optimize_INT_ADD(self, op):"));
    }

    fn normalize_whitespace(source: &str) -> String {
        let mut normalized = source.split_whitespace().collect::<String>();
        loop {
            let without_optional_commas = normalized.replace(",)", ")").replace(",]", "]");
            if without_optional_commas == normalized {
                return normalized;
            }
            normalized = without_optional_commas;
        }
    }

    #[test]
    fn test_generate_rust_real_rules_covers_all_rules() {
        let ast = parse::parse(REAL_RULES).unwrap();
        assert_eq!(ast.rules.len(), 72);
        let generated = generate_rust_real_rules().unwrap();
        for rule in &ast.rules {
            assert!(
                generated.contains(&format!("// {}:", rule.name)),
                "missing generated rule {}",
                rule.name
            );
        }
    }

    #[test]
    fn test_generated_rust_rules_are_fresh() {
        let generated = generate_rust_real_rules().unwrap();
        let committed = include_str!("../optimizeopt/autogenintrules.rs");
        assert_eq!(
            normalize_whitespace(&generated),
            normalize_whitespace(committed),
            "real.rules changed without regenerating optimizeopt/autogenintrules.rs"
        );
    }
}
