//! Rust emitter for the integer optimization rule DSL.
//!
//! The matcher construction and rule ordering are shared with `codegen.rs`,
//! whose walk mirrors `rpython/jit/metainterp/ruleopt/codegen.py`. This module
//! supplies the corresponding walk for the Rust `OptIntAutoGenerated` mixin.

use std::collections::HashMap;

use crate::ruleopt::codegen::{
    BaseMatcher, IsConstMatcher, OpMatcher, Path, PathElement, Terminal, create_matcher,
    generate_commutative_rules, sort_rules, split_by_result_type,
};
use crate::ruleopt::parse::{
    Compute, Element, Expression, File, Pattern, PatternVar, Rule, RuleType,
};

const OPS_WITH_OP_RC: &[&str] = &[
    "int_eq",
    "int_add",
    "int_sub",
    "int_mul",
    "int_and",
    "int_or",
    "int_xor",
    "int_neg",
    "int_invert",
    "int_lshift",
    "int_rshift",
    "uint_rshift",
    "int_is_true",
    "int_force_ge_zero",
];

#[derive(Default)]
pub struct RustCodegen {
    code: Vec<String>,
    level: usize,
    bindings: HashMap<String, String>,
    intbound_bindings: HashMap<String, String>,
    binding_types: HashMap<String, RuleType>,
    method_opname: String,
    name_positions: HashMap<String, usize>,
    pattern_bindings: HashMap<Pattern, String>,
}

impl RustCodegen {
    pub fn new() -> Self {
        Self::default()
    }

    fn emit(&mut self, line: impl AsRef<str>) {
        let line = line.as_ref();
        if line.trim().is_empty() {
            self.code.push(String::new());
        } else {
            self.code
                .push(format!("{}{}", "    ".repeat(self.level), line));
        }
    }

    fn with_block(&mut self, line: impl AsRef<str>, f: impl FnOnce(&mut Self)) {
        self.emit(line);
        self.level += 1;
        f(self);
        self.level -= 1;
        self.emit("}");
    }

    fn emit_stacking_condition(&mut self, condition: impl AsRef<str>) {
        self.emit(format!("if {} {{", condition.as_ref()));
        self.level += 1;
    }

    fn rust_matcher_name(name: &str) -> String {
        if let Some(rest) = name.strip_prefix("arg_") {
            format!("arg{rest}")
        } else if let Some(rest) = name.strip_prefix("C_arg_") {
            format!("c_arg{rest}")
        } else {
            name.to_ascii_lowercase()
        }
    }

    fn bound_name(boxname: &str) -> String {
        format!("b_{boxname}")
    }

    fn local_name(name: &str) -> String {
        name.to_ascii_lowercase()
    }

    fn opcode_name(opname: &str) -> String {
        let mut result = String::new();
        for part in opname.split('_') {
            let mut chars = part.chars();
            if let Some(first) = chars.next() {
                result.extend(first.to_uppercase());
                result.extend(chars);
            }
        }
        result
    }

    fn static_suffix(opname: &str) -> String {
        opname.to_ascii_uppercase()
    }

    fn rust_constant(value: &str) -> String {
        match value {
            "LONG_BIT" => "64".to_string(),
            "MININT" => "i64::MIN".to_string(),
            "MAXINT" => "i64::MAX".to_string(),
            _ => value
                .parse::<i64>()
                .unwrap_or_else(|_| panic!("unsupported rule constant {value:?}"))
                .to_string(),
        }
    }

    fn unique_expanded_rules(rules: &[Rule]) -> Vec<Rule> {
        let mut seen = Vec::new();
        let mut result = Vec::new();
        for rule in rules {
            for expanded in generate_commutative_rules(rule) {
                let key = (expanded.name.clone(), expanded.pattern.to_string());
                if !seen.contains(&key) {
                    seen.push(key);
                    result.push(expanded);
                }
            }
        }
        result
    }

    fn per_op(ast: &File) -> Vec<(String, Vec<Rule>)> {
        let mut result: Vec<(String, Vec<Rule>)> = Vec::new();
        for rule in &ast.rules {
            let Pattern::PatternOp(pattern) = &rule.pattern else {
                continue;
            };
            if let Some((_, rules)) = result
                .iter_mut()
                .find(|(opname, _)| opname == &pattern.opname)
            {
                rules.push(rule.clone());
            } else {
                result.push((pattern.opname.clone(), vec![rule.clone()]));
            }
        }
        result
    }

    fn rule_names(rules: &[Rule]) -> Vec<String> {
        let mut seen = Vec::new();
        rules
            .iter()
            .filter_map(|rule| {
                if !seen.contains(&rule.name) {
                    seen.push(rule.name.clone());
                    Some(rule.name.clone())
                } else {
                    None
                }
            })
            .collect()
    }

    fn emit_rule_tables(&mut self, per_op: &[(String, Vec<Rule>)]) {
        for (opname, rules) in per_op {
            let suffix = Self::static_suffix(opname);
            let names = Self::rule_names(rules);
            self.emit(format!("static RULE_NAMES_{suffix}: &[&str] = &["));
            self.level += 1;
            for name in &names {
                self.emit(format!("{name:?},"));
            }
            self.level -= 1;
            self.emit("];");
            self.emit(format!(
                "static RULE_FIRED_{suffix}: [AtomicU64; {}] = [const {{ AtomicU64::new(0) }}; {}];",
                names.len(),
                names.len()
            ));
        }
        self.emit("");
        self.with_block(
            "pub fn all_rules_fired() -> Vec<(&'static str, &'static [&'static str], &'static [AtomicU64])> {",
            |this| {
                this.emit("vec![");
                this.level += 1;
                for (opname, _) in per_op {
                    let suffix = Self::static_suffix(opname);
                    this.emit(format!(
                        "({opname:?}, RULE_NAMES_{suffix}, &RULE_FIRED_{suffix}),"
                    ));
                }
                this.level -= 1;
                this.emit("]");
            },
        );
        self.emit("");
    }

    fn emit_helpers(&mut self) {
        self.emit("#[inline]");
        self.with_block("fn fire(counts: &[AtomicU64], index: usize) {", |this| {
            this.emit("counts[index].fetch_add(1, Ordering::Relaxed);");
        });
        self.emit("");
        self.with_block(
            "fn autogen_eq_b(box1: &Operand, bound1: &IntBound, box2: &Operand, bound2: &IntBound) -> bool {",
            |this| {
                this.with_block("if box1 == box2 {", |this| this.emit("return true;"));
                this.with_block(
                    "if bound1.is_constant() && bound2.is_constant() && bound1.get_constant_int() == bound2.get_constant_int() {",
                    |this| this.emit("return true;"),
                );
                this.emit("false");
            },
        );
        self.emit("");
        self.with_block(
            "fn replace_with(original: &Op, opcode: OpCode, args: &[Operand]) -> OptimizationResult {",
            |this| {
                this.emit("let new_op = Op::new(opcode, args);");
                this.emit("new_op.pos.set(original.pos.get());");
                this.emit("OptimizationResult::Restart(new_op)");
            },
        );
        self.emit("");
        self.with_block(
            "fn as_operation_b(b: &Operand, opcode: OpCode, ctx: &mut OptContext) -> Option<Op> {",
            |this| {
                this.emit("let op = ctx.get_producing_op(b)?;");
                this.with_block("if op.opcode == opcode {", |this| this.emit("Some(op)"));
                this.emit("else {");
                this.level += 1;
                this.emit("None");
                this.level -= 1;
                this.emit("}");
            },
        );
        self.emit("");
    }

    fn method_signature(opname: &str, declaration: bool) -> String {
        let end = if declaration { ";" } else { " {" };
        if OPS_WITH_OP_RC.contains(&opname) {
            format!(
                "fn optimize_{opname}(&mut self, op: &Op, op_rc: &majit_ir::OpRc, ctx: &mut OptContext) -> OptimizationResult{end}"
            )
        } else {
            format!(
                "fn optimize_{opname}(&mut self, op: &Op, ctx: &mut OptContext) -> OptimizationResult{end}"
            )
        }
    }

    fn emit_trait(&mut self, per_op: &[(String, Vec<Rule>)]) {
        self.emit("pub trait OptIntAutoGenerated {");
        self.level += 1;
        for (opname, _) in per_op {
            self.emit(Self::method_signature(opname, true));
        }
        self.level -= 1;
        self.emit("}");
        self.emit("");
    }

    fn emit_arg_reads(&mut self, prefix: &str, opname: &str, numargs: usize) -> Vec<String> {
        let mut boxnames = Vec::new();
        for index in 0..numargs {
            let matcher_name = format!("{prefix}_{index}");
            let boxname = Self::rust_matcher_name(&matcher_name);
            let boundname = Self::bound_name(&boxname);
            boxnames.push(boxname.clone());
            self.emit(format!(
                "let {boxname} = self.resolve_box(&{opname}.arg({index}), ctx);"
            ));
            self.emit(format!(
                "let {boundname} = self.getintbound_b(&{boxname}, ctx);"
            ));
        }
        boxnames
    }

    fn add_binding(&mut self, pattern: &Pattern, path: &Path, name: &str) {
        let mut pattern = pattern;
        for element in &path.0 {
            match element {
                PathElement::Const => assert!(pattern.matches_constant()),
                PathElement::Op(opname, index) => {
                    let Pattern::PatternOp(op) = pattern else {
                        unreachable!("path expects op pattern");
                    };
                    assert_eq!(&op.opname, opname);
                    pattern = &op.args[*index];
                }
            }
        }
        self.pattern_bindings
            .insert(pattern.clone(), Self::rust_matcher_name(name));
    }

    fn pattern_binding(&self, pattern: &Pattern) -> String {
        self.pattern_bindings
            .get(pattern)
            .cloned()
            .unwrap_or_else(|| panic!("missing matcher binding for {pattern}"))
    }

    fn visit_matcher(&mut self, matcher: &BaseMatcher) {
        match matcher {
            BaseMatcher::Terminal(ast) => self.visit_terminal(ast),
            BaseMatcher::IsConstMatcher(ast) => self.visit_is_const_matcher(ast),
            BaseMatcher::OpMatcher(ast) => self.visit_op_matcher(ast),
        }
    }

    fn visit_terminal(&mut self, ast: &Terminal) {
        for rule in &ast.rules {
            self.bindings.clear();
            self.intbound_bindings.clear();
            self.binding_types.clear();
            self.pattern_bindings.clear();
            for (path, name) in &ast.bindings {
                self.add_binding(&rule.pattern, path, name);
            }
            let position = self.name_positions[&rule.name];
            self.generate_rule(rule, position);
            if Self::rule_is_unconditional_at_terminal(rule) {
                break;
            }
        }
    }

    fn rule_is_unconditional_at_terminal(rule: &Rule) -> bool {
        fn pattern_is_unconditional(pattern: &Pattern, names: &mut Vec<String>) -> bool {
            match pattern {
                Pattern::PatternVar(var) => {
                    if names.contains(&var.name) {
                        false
                    } else {
                        names.push(var.name.clone());
                        true
                    }
                }
                Pattern::PatternConst(_) => false,
                Pattern::PatternOp(op) => op
                    .args
                    .iter()
                    .all(|arg| pattern_is_unconditional(arg, names)),
            }
        }

        !rule
            .elements
            .iter()
            .any(|element| matches!(element, Element::Check(_)))
            && pattern_is_unconditional(&rule.pattern, &mut Vec::new())
    }

    fn visit_is_const_matcher(&mut self, ast: &IsConstMatcher) {
        let currlevel = self.level;
        let boxname = Self::rust_matcher_name(&ast.name);
        let boundname = Self::bound_name(&boxname);
        let constname = Self::rust_matcher_name(&ast.constname);
        self.emit_stacking_condition(format!("{boundname}.is_constant()"));
        self.emit(format!("let {constname} = {boundname}.get_constant_int();"));
        if let Some(ifyes) = &ast.ifyes {
            self.visit_matcher(ifyes);
        }
        self.level = currlevel;
        self.emit("}");
        if let Some(ifno) = &ast.ifno {
            self.emit("else {");
            self.level += 1;
            self.visit_matcher(ifno);
            self.level = currlevel;
            self.emit("}");
        }
        if let Some(nextmatcher) = &ast.nextmatcher {
            self.visit_matcher(nextmatcher);
        }
    }

    fn visit_op_matcher(&mut self, ast: &OpMatcher) {
        let currlevel = self.level;
        let operand = Self::rust_matcher_name(&ast.name);
        let opname = Self::opcode_name(&ast.opname);
        let operation = format!("{operand}_{}", ast.opname);
        self.emit(format!(
            "if let Some({operation}) = as_operation_b(&{operand}, OpCode::{opname}, ctx) {{"
        ));
        self.level += 1;
        let boxnames = self.emit_arg_reads(&ast.name, &operation, ast.argnames.len());
        assert_eq!(
            boxnames,
            ast.argnames
                .iter()
                .map(|name| Self::rust_matcher_name(name))
                .collect::<Vec<_>>()
        );
        if let Some(ifyes) = &ast.ifyes {
            self.visit_matcher(ifyes);
        }
        self.level = currlevel;
        self.emit("}");
        if let Some(ifno) = &ast.ifno {
            self.emit("else {");
            self.level += 1;
            self.visit_matcher(ifno);
            self.level = currlevel;
            self.emit("}");
        }
        if let Some(nextmatcher) = &ast.nextmatcher {
            self.visit_matcher(nextmatcher);
        }
    }

    fn visit_pattern(&mut self, pattern: &Pattern) {
        match pattern {
            Pattern::PatternVar(pattern) => self.visit_pattern_var(pattern),
            Pattern::PatternConst(pattern_const) => {
                let binding = self.pattern_binding(pattern);
                self.emit_stacking_condition(format!(
                    "{binding} == {}",
                    Self::rust_constant(&pattern_const.const_value)
                ));
            }
            Pattern::PatternOp(pattern_op) => {
                for arg in &pattern_op.args {
                    self.visit_pattern(arg);
                }
            }
        }
    }

    fn visit_pattern_var(&mut self, pattern: &PatternVar) {
        let ast = Pattern::PatternVar(pattern.clone());
        let varname = self.pattern_binding(&ast);
        let typ = pattern.typ.unwrap_or_else(|| {
            if pattern.name.starts_with('C') {
                RuleType::Int
            } else {
                RuleType::IntBound
            }
        });
        if typ == RuleType::Int {
            if let Some(previous) = self.bindings.get(&pattern.name) {
                if previous != &varname {
                    self.emit_stacking_condition(format!("{varname} == {previous}"));
                }
            } else {
                self.bindings.insert(pattern.name.clone(), varname);
                self.binding_types.insert(pattern.name.clone(), typ);
            }
            return;
        }

        let boundname = Self::bound_name(&varname);
        if let Some(previous) = self.bindings.get(&pattern.name).cloned() {
            if previous != varname {
                let previous_bound = self.intbound_bindings[&pattern.name].clone();
                self.emit_stacking_condition(format!(
                    "autogen_eq_b(&{varname}, &{boundname}, &{previous}, &{previous_bound})"
                ));
            }
        } else {
            self.bindings.insert(pattern.name.clone(), varname);
            self.intbound_bindings
                .insert(pattern.name.clone(), boundname);
            self.binding_types.insert(pattern.name.clone(), typ);
        }
    }

    fn expression_type(expr: &Expression) -> RuleType {
        match expr {
            Expression::Name(expr) => expr.typ.unwrap_or(RuleType::IntBound),
            Expression::Number(expr) => expr.typ,
            Expression::Add(expr) => expr.typ,
            Expression::Sub(expr) => expr.typ,
            Expression::Mul(expr) => expr.typ,
            Expression::Div(expr) => expr.typ,
            Expression::LShift(expr) => expr.typ,
            Expression::URShift(expr) => expr.typ,
            Expression::ARShift(expr) => expr.typ,
            Expression::OpAnd(expr) => expr.typ,
            Expression::OpOr(expr) => expr.typ,
            Expression::OpXor(expr) => expr.typ,
            Expression::Eq(expr) => expr.typ,
            Expression::Ge(expr) => expr.typ,
            Expression::Gt(expr) => expr.typ,
            Expression::Le(expr) => expr.typ,
            Expression::Lt(expr) => expr.typ,
            Expression::Ne(expr) => expr.typ,
            Expression::ShortcutAnd(expr) => expr.typ,
            Expression::ShortcutOr(expr) => expr.typ,
            Expression::Invert(expr) => expr.typ,
            Expression::Attribute(expr) => expr.typ,
            Expression::MethodCall(expr) => expr.typ.unwrap_or(RuleType::IntBound),
            Expression::FuncCall(expr) => expr.typ.unwrap_or(RuleType::Int),
        }
    }

    fn visit_compute(&mut self, compute: &Compute) {
        let typ = Self::expression_type(&compute.expr);
        let local = Self::local_name(&compute.name);
        let expression = self.visit_expression(&compute.expr);
        self.emit(format!("let {local} = {expression};"));
        self.binding_types.insert(compute.name.clone(), typ);
        if typ == RuleType::IntBound {
            self.intbound_bindings.insert(compute.name.clone(), local);
        } else {
            self.bindings.insert(compute.name.clone(), local);
        }
    }

    fn range_condition(&self, expr: &Expression) -> Option<String> {
        let Expression::ShortcutAnd(expr) = expr else {
            return None;
        };
        let Expression::Le(left) = &expr.left else {
            return None;
        };
        let Expression::Number(zero) = &left.left else {
            return None;
        };
        if zero.value != 0 {
            return None;
        }
        let Expression::Name(lower_name) = &left.right else {
            return None;
        };
        let Expression::Lt(right) = &expr.right else {
            return None;
        };
        let Expression::Name(upper_name) = &right.left else {
            return None;
        };
        let Expression::Name(long_bit) = &right.right else {
            return None;
        };
        if lower_name.name != upper_name.name || long_bit.name != "LONG_BIT" {
            return None;
        }
        Some(format!(
            "(0..64).contains(&{})",
            self.bindings[&lower_name.name]
        ))
    }

    fn visit_expression(&self, expr: &Expression) -> String {
        self.visit_expression_prec(expr, 0)
    }

    fn visit_expression_prec(&self, expr: &Expression, parent_prec: u8) -> String {
        if let Some(range) = self.range_condition(expr) {
            return range;
        }
        match expr {
            Expression::Name(expr) => match expr.name.as_str() {
                "LONG_BIT" => "64i64".to_string(),
                "MININT" => "i64::MIN".to_string(),
                "MAXINT" => "i64::MAX".to_string(),
                _ if expr.typ == Some(RuleType::IntBound) => {
                    self.intbound_bindings[&expr.name].clone()
                }
                _ => self.bindings[&expr.name].clone(),
            },
            Expression::Number(expr) => format!("{}i64", expr.value),
            Expression::Add(expr) => format!(
                "({}).wrapping_add({})",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::Sub(expr) => format!(
                "({}).wrapping_sub({})",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::Mul(expr) => format!(
                "({}).wrapping_mul({})",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::Div(expr) => format!(
                "({}).wrapping_div({})",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::LShift(expr) => format!(
                "({}).wrapping_shl(({}) as u32)",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::URShift(expr) => format!(
                "((({}) as u64) >> (({}) as u32)) as i64",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::ARShift(expr) => format!(
                "(({}) >> (({}) as u32))",
                self.visit_expression_prec(&expr.left, 0),
                self.visit_expression_prec(&expr.right, 0)
            ),
            Expression::OpAnd(expr) => self.binop(&expr.left, "&", &expr.right, 6, parent_prec),
            Expression::OpOr(expr) => self.binop(&expr.left, "|", &expr.right, 4, parent_prec),
            Expression::OpXor(expr) => self.binop(&expr.left, "^", &expr.right, 5, parent_prec),
            Expression::Eq(expr) => self.binop(&expr.left, "==", &expr.right, 3, parent_prec),
            Expression::Ge(expr) => self.binop(&expr.left, ">=", &expr.right, 3, parent_prec),
            Expression::Gt(expr) => self.binop(&expr.left, ">", &expr.right, 3, parent_prec),
            Expression::Le(expr) => self.binop(&expr.left, "<=", &expr.right, 3, parent_prec),
            Expression::Lt(expr) => self.binop(&expr.left, "<", &expr.right, 3, parent_prec),
            Expression::Ne(expr) => self.binop(&expr.left, "!=", &expr.right, 3, parent_prec),
            Expression::ShortcutAnd(expr) => {
                self.binop(&expr.left, "&&", &expr.right, 2, parent_prec)
            }
            Expression::ShortcutOr(expr) => {
                self.binop(&expr.left, "||", &expr.right, 1, parent_prec)
            }
            Expression::Invert(expr) => {
                format!("!{}", self.visit_expression_prec(&expr.left, 10))
            }
            Expression::Attribute(expr) => {
                let bound = &self.intbound_bindings[&expr.varname];
                match expr.attrname.as_str() {
                    "ones" => format!("({bound}.tvalue as i64)"),
                    "zeros" => format!("(!({bound}.tvalue | {bound}.tmask) as i64)"),
                    "tvalue" => format!("({bound}.tvalue as i64)"),
                    "lower" | "upper" => format!("{bound}.{}", expr.attrname),
                    other => panic!("unsupported IntBound attribute {other:?}"),
                }
            }
            Expression::MethodCall(expr) => {
                let receiver = self.visit_expression_prec(&expr.value, 11);
                let args = expr
                    .args
                    .iter()
                    .map(|arg| {
                        let value = self.visit_expression_prec(arg, 0);
                        if Self::expression_type(arg) == RuleType::IntBound {
                            format!("&{value}")
                        } else {
                            value
                        }
                    })
                    .collect::<Vec<_>>();
                format!("{receiver}.{}({})", expr.methname, args.join(", "))
            }
            Expression::FuncCall(expr) => {
                let args = expr
                    .args
                    .iter()
                    .map(|arg| self.visit_expression_prec(arg, 0))
                    .collect::<Vec<_>>();
                match expr.funcname.as_str() {
                    "highest_bit" => format!("({}).trailing_zeros() as i64", args[0]),
                    "min" => format!("({}).min({})", args[0], args[1]),
                    other => panic!("unsupported rule function {other:?}"),
                }
            }
        }
    }

    fn binop(
        &self,
        left: &Expression,
        op: &str,
        right: &Expression,
        precedence: u8,
        parent_prec: u8,
    ) -> String {
        let expression = format!(
            "{} {op} {}",
            self.visit_expression_prec(left, precedence),
            self.visit_expression_prec(right, precedence + 1)
        );
        if parent_prec > precedence {
            format!("({expression})")
        } else {
            expression
        }
    }

    fn emit_target_constant(&mut self, value: String, position: usize) {
        let suffix = Self::static_suffix(&self.method_opname);
        self.emit(format!("self.make_constant_int(op, {value}, ctx);"));
        self.emit(format!("fire(&RULE_FIRED_{suffix}, {position});"));
        self.emit("return OptimizationResult::Remove;");
    }

    fn generate_target(&mut self, target: &Pattern, position: usize) {
        let suffix = Self::static_suffix(&self.method_opname);
        match target {
            Pattern::PatternVar(target) => {
                let typ = target.typ.unwrap_or(self.binding_types[&target.name]);
                if typ == RuleType::Int {
                    self.emit_target_constant(self.bindings[&target.name].clone(), position);
                } else {
                    let value = self.bindings[&target.name].clone();
                    self.emit("let b_old = Operand::from_bound_op(op_rc);");
                    self.emit(format!("ctx.make_equal_to(&b_old, &{value});"));
                    self.emit(format!("fire(&RULE_FIRED_{suffix}, {position});"));
                    self.emit("return OptimizationResult::Remove;");
                }
            }
            Pattern::PatternConst(target) => {
                self.emit_target_constant(Self::rust_constant(&target.const_value), position);
            }
            Pattern::PatternOp(target) => {
                let mut args = Vec::new();
                for (index, arg) in target.args.iter().enumerate() {
                    match arg {
                        Pattern::PatternVar(var) => {
                            let typ = var.typ.unwrap_or(self.binding_types[&var.name]);
                            if typ == RuleType::Int {
                                let value = self.bindings[&var.name].clone();
                                let reference = format!("target_ref_{index}");
                                let operand = format!("target_arg_{index}");
                                self.emit(format!(
                                    "let {reference} = ctx.make_constant_int({value});"
                                ));
                                self.emit(format!(
                                    "let {operand} = ctx.materialize_operand_at({reference});"
                                ));
                                args.push(operand);
                            } else {
                                args.push(format!("{}.clone()", self.bindings[&var.name]));
                            }
                        }
                        Pattern::PatternConst(value) => {
                            let value = Self::rust_constant(&value.const_value);
                            let reference = format!("target_ref_{index}");
                            let operand = format!("target_arg_{index}");
                            self.emit(format!("let {reference} = ctx.make_constant_int({value});"));
                            self.emit(format!(
                                "let {operand} = ctx.materialize_operand_at({reference});"
                            ));
                            args.push(operand);
                        }
                        Pattern::PatternOp(_) => {
                            unreachable!("generated targets use flat arguments")
                        }
                    }
                }
                self.emit(format!("fire(&RULE_FIRED_{suffix}, {position});"));
                self.emit(format!(
                    "return replace_with(op, OpCode::{}, &[{}]);",
                    Self::opcode_name(&target.opname),
                    args.join(", ")
                ));
            }
        }
    }

    fn generate_rule(&mut self, rule: &Rule, position: usize) {
        self.emit(format!(
            "// {}: {} => {}",
            rule.name, rule.pattern, rule.target
        ));
        let currlevel = self.level;
        if let Pattern::PatternOp(pattern) = &rule.pattern {
            for arg in &pattern.args {
                self.visit_pattern(arg);
            }
        }
        for element in &rule.elements {
            match element {
                Element::Compute(compute) => self.visit_compute(compute),
                Element::Check(check) => {
                    let condition = self.visit_expression(&check.expr);
                    self.emit_stacking_condition(condition);
                }
            }
        }
        self.generate_target(&rule.target, position);
        while self.level > currlevel {
            self.level -= 1;
            self.emit("}");
        }
    }

    fn generate_method(&mut self, opname: &str, rules: &[Rule]) {
        let all_rules = Self::unique_expanded_rules(rules);
        let names = Self::rule_names(&all_rules);
        self.name_positions = names
            .into_iter()
            .enumerate()
            .map(|(index, name)| (name, index))
            .collect();
        self.method_opname = opname.to_string();

        self.emit(Self::method_signature(opname, false));
        self.level += 1;
        let numargs = match &rules[0].pattern {
            Pattern::PatternOp(pattern) => pattern.args.len(),
            _ => unreachable!("top-level rule pattern must be PatternOp"),
        };
        self.emit_arg_reads("arg", "op", numargs);
        let subsets = split_by_result_type(&all_rules);
        for subset in [subsets.0, subsets.1, subsets.2] {
            let sorted = sort_rules(&subset);
            if let Some(matcher) = create_matcher(&sorted) {
                self.visit_matcher(&matcher);
            }
        }
        self.emit("OptimizationResult::PassOn");
        self.level -= 1;
        self.emit("}");
        self.emit("");
    }

    pub fn generate_mixin(&mut self, ast: &File) -> String {
        let per_op = Self::per_op(ast);
        self.emit_rule_tables(&per_op);
        self.emit_helpers();
        self.emit_trait(&per_op);
        self.emit("impl OptIntAutoGenerated for OptIntBounds {");
        self.level += 1;
        for (opname, rules) in &per_op {
            self.generate_method(opname, rules);
        }
        self.level -= 1;
        self.emit("}");
        self.emit("");
        self.code.join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ruleopt::{REAL_RULES, parse};

    #[test]
    fn generates_contract_fixtures() {
        let ast = parse::parse(REAL_RULES).unwrap();
        let generated = RustCodegen::new().generate_mixin(&ast);
        assert!(generated.contains("fn optimize_int_add"));
        assert!(generated.contains("(0..64).contains(&c_arg"));
        assert!(generated.contains("trailing_zeros() as i64"));
        assert!(generated.contains("autogen_eq_b"));
        assert!(generated.contains("OptimizationResult::Restart"));
    }
}
