//! Metadata code generation from canonical JitCode pipeline results.
//!
//! Executable tracing semantics live in the assembled JitCodes. The generated
//! Rust source is intentionally consumer-neutral and exposes only driver and
//! JitCode census data for diagnostics.

/// Generate a summary from raw graph-pipeline output.
///
/// Test-only summary emitter for the diagnostic `functions` view. Active
/// consumers should use [`generate_from_pipeline`], which reports the
/// canonical assembled JitCode and driver metadata.
#[cfg(test)]
pub fn generate_from_graph(result: &crate::pipeline::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-translate graph pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));

    // Function summary
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    ({:?}, {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");

    out
}

/// Flavor toggles for [`generate_from_pipeline_with_flavor`].
///
/// Retained for API compatibility with consumers that drive the JIT through
/// the `#[jit_interp]` proc macro. This used to gate emission of Pyre-specific
/// trace helpers; executable semantics now live in assembled JitCodes, so
/// `Full` and `Minimal` currently produce identical metadata output.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenFlavor {
    /// Full metadata output. Currently identical to [`Self::Minimal`].
    Full,
    /// Minimal metadata output. Currently identical to [`Self::Full`].
    Minimal,
}

/// Generate metadata directly from the canonical pipeline result.
///
/// This is the RPython-leaning entry point: graph/pipeline output is the only
/// source-of-truth used for emission.
pub fn generate_from_pipeline(result: &crate::pipeline::ProgramPipelineResult) -> String {
    generate_from_pipeline_with_flavor(result, CodegenFlavor::Full)
}

/// Like [`generate_from_pipeline`] but takes a [`CodegenFlavor`].
///
/// The flavor is currently a no-op and is retained so external callers keep
/// compiling; see [`CodegenFlavor`].
pub fn generate_from_pipeline_with_flavor(
    result: &crate::pipeline::ProgramPipelineResult,
    _flavor: CodegenFlavor,
) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-translate canonical pipeline — do not edit.\n\n");

    // Pyre-specific operator tables, concrete computation primitives, and
    // typed `generated_*` operations remain hand-maintained Rust in
    // `pyre-jit-trace/src/trace_helpers.rs`; `OpcodeHandler` implementations
    // likewise live in `opcode_handler_impls.rs`. They are fixed runtime code,
    // not translator output. The consumer-neutral output here therefore
    // describes only the compiled drivers and canonical JitCodes.
    out.push_str("/// Configured portal graph to main JitCode index.\n");
    out.push_str("pub const COMPILED_JIT_DRIVERS: &[(&str, usize)] = &[\n");
    for driver in &result.jit_drivers {
        out.push_str(&format!(
            "    ({:?}, {}),\n",
            driver.portal.canonical_key(),
            driver.main_jitcode_index,
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// Canonical assembled JitCode census: name and byte length.\n");
    out.push_str("pub const CANONICAL_JITCODES: &[(&str, usize)] = &[\n");
    for jitcode in &result.jitcodes {
        out.push_str(&format!(
            "    ({:?}, {}),\n",
            jitcode.name,
            jitcode.code.len(),
        ));
    }
    out.push_str("];\n");
    out
}

/// Recognition report for canonical driver and JitCode output.
///
/// This replaces the former opcode-arm recognition census: once the
/// codewriter owns ordinary portal closures, the meaningful diagnostic is
/// whether each reachable graph produced a non-empty assembled JitCode.
#[derive(Debug, Clone)]
pub struct RecognitionReport {
    /// Number of configured drivers compiled into the artifact.
    pub total_drivers: usize,
    /// Number of JitCodes in allocation order.
    pub total_jitcodes: usize,
    /// Sum of all assembled JitCode byte lengths.
    pub total_code_bytes: usize,
    /// Number of reachable graphs whose assembled body is empty.
    pub empty_jitcodes: usize,
    /// Per-JitCode allocation index and byte count.
    pub per_jitcode: Vec<JitCodeRecognition>,
}

/// One entry in [`RecognitionReport::per_jitcode`].
#[derive(Debug, Clone)]
pub struct JitCodeRecognition {
    /// Diagnostic graph leaf name stored on the JitCode.
    pub name: String,
    /// Allocation-order index used by serialized descriptors and drivers.
    pub index: usize,
    /// Length of the assembled bytecode body.
    pub code_bytes: usize,
}

/// Analyze canonical pipeline output to produce a recognition report.
pub fn recognition_report(result: &crate::pipeline::ProgramPipelineResult) -> RecognitionReport {
    let per_jitcode: Vec<JitCodeRecognition> = result
        .jitcodes
        .iter()
        .enumerate()
        .map(|(index, jitcode)| JitCodeRecognition {
            name: jitcode.name.clone(),
            index,
            code_bytes: jitcode.code.len(),
        })
        .collect();
    RecognitionReport {
        total_drivers: result.jit_drivers.len(),
        total_jitcodes: per_jitcode.len(),
        total_code_bytes: per_jitcode.iter().map(|entry| entry.code_bytes).sum(),
        empty_jitcodes: per_jitcode
            .iter()
            .filter(|entry| entry.code_bytes == 0)
            .count(),
        per_jitcode,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    fn fixture() -> crate::pipeline::ProgramPipelineResult {
        // The emitters read only canonical summary fields. Hand-rolling a
        // ProgramPipelineResult exercises that surface without invoking the
        // full LLBC analysis pipeline in these unit tests.
        let main_jitcode = Arc::new(crate::jitcode::JitCode::new("mainloop"));
        main_jitcode.set_body(crate::jitcode::JitCodeBody::default());
        crate::pipeline::ProgramPipelineResult {
            functions: Vec::new(),
            jit_drivers: vec![crate::pipeline::CompiledJitDriver {
                portal: crate::CallPath::from_segments(["engine", "mainloop"]),
                main_jitcode_index: 0,
            }],
            jitcodes: vec![main_jitcode],
            jitcodes_by_path: indexmap::IndexMap::new(),
            insns: indexmap::IndexMap::new(),
            descrs: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        }
    }

    #[test]
    fn generated_metadata_is_driver_and_jitcode_based() {
        let fixture = fixture();
        let code = generate_from_pipeline(&fixture);
        assert!(code.contains("COMPILED_JIT_DRIVERS"));
        assert!(code.contains("CANONICAL_JITCODES"));
        assert!(!code.contains("OPCODE"));
        assert!(generate_from_graph(&fixture).contains("GRAPH_FUNCTIONS"));
    }

    #[test]
    fn report_counts_jitcodes() {
        let report = recognition_report(&fixture());
        assert_eq!(report.total_drivers, 1);
        assert_eq!(report.total_jitcodes, 1);
    }
}
