//! Tracing code generation from analysis results.
//!
//! Generates Rust source code that implements tracing for each opcode.
//! The generated code is included by pyre-mjit's build.rs via include!().
//!
//! Each recognized TracePattern produces a tracing function that emits
//! the equivalent IR ops. Unrecognized patterns fall back to residual calls.

/// Generate tracing code from graph pipeline results.
///
/// Test-only summary emitter for raw graph pipeline output. Active consumers
/// should use `generate_from_pipeline()`, which is the canonical translator
/// entry point.
#[cfg(test)]
pub fn generate_from_graph(result: &crate::pipeline::ProgramPipelineResult) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-translate graph pipeline — do not edit.\n");
    out.push_str(&format!(
        "// Graph analysis: {} functions, {} blocks, {} flat ops, {} vable rewrites\n\n",
        result.functions.len(),
        result.total_blocks,
        result.total_ops,
        result.total_vable_rewrites,
    ));

    // Function summary
    out.push_str("/// Graph analysis function summary.\n");
    out.push_str("pub const GRAPH_FUNCTIONS: &[(&str, usize, usize)] = &[\n");
    for func in &result.functions {
        out.push_str(&format!(
            "    (\"{}\", {}, {}),\n",
            func.name,
            func.original_blocks,
            func.flattened.insns.len()
        ));
    }
    out.push_str("];\n\n");

    out
}

/// Flavor toggles for `generate_from_pipeline`.
///
/// Retained for API compatibility with non-pyre consumers (e.g. `aheui-jit`)
/// that drive the JIT through the `#[jit_interp]` proc macro. This used to
/// gate emission of pyre-specific trace helpers; those helpers are now
/// hand-maintained Rust in `pyre-jit-trace/src/trace_helpers.rs` (not
/// translator output), so `Full` and `Minimal` currently produce identical
/// output.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenFlavor {
    /// Pyre path.
    Full,
    /// Graph/dispatch metadata only.
    Minimal,
}

/// Generate tracing code directly from the canonical pipeline result.
///
/// This is the RPython-leaning entry point: graph/pipeline output is the only
/// source-of-truth used for emission.
pub fn generate_from_pipeline(result: &crate::pipeline::ProgramPipelineResult) -> String {
    generate_from_pipeline_with_flavor(result, CodegenFlavor::Full)
}

/// Like [`generate_from_pipeline`] but takes a [`CodegenFlavor`]. The flavor
/// is currently a no-op (both variants emit the same output) and retained
/// only so external callers keep compiling; see [`CodegenFlavor`].
pub fn generate_from_pipeline_with_flavor(
    result: &crate::pipeline::ProgramPipelineResult,
    _flavor: CodegenFlavor,
) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by majit-translate canonical pipeline — do not edit.\n\n");

    generate_canonical_dispatch_table(&mut out, result);
    // The pyre-specific trace helpers (operator dispatch tables, concrete
    // computation, unbox/box/binop trace primitives, and the typed
    // `generated_*` operations) are hand-maintained Rust in
    // `pyre-jit-trace/src/trace_helpers.rs`, not emitted here. The
    // `OpcodeHandler` trait impls likewise live in
    // `pyre-jit-trace/src/opcode_handler_impls.rs`. Both are real modules
    // because they are fixed code, not translator output.

    let flattened_count = result
        .opcode_dispatch
        .iter()
        .filter(|a| a.flattened.is_some())
        .count();
    out.push_str(&format!(
        "// Canonical analysis summary: {}/{} flattened\n",
        flattened_count,
        result.opcode_dispatch.len(),
    ));

    out
}

/// Recognition report for pipeline analysis diagnostic.
///
/// Quantifies how much of the input source the pipeline recognizes,
/// surfacing Unknown ops and unresolved calls per opcode arm.
#[derive(Debug, Clone)]
pub struct RecognitionReport {
    pub total_opcodes: usize,
    pub flattened: usize,
    pub total_flat_ops: usize,
    pub unknown_ops: usize,
    pub unresolved_calls: usize,
    pub per_opcode: Vec<OpcodeRecognition>,
}

#[derive(Debug, Clone)]
pub struct OpcodeRecognition {
    pub selector: String,
    pub flat_ops: usize,
    pub unknowns: usize,
    pub unresolved: usize,
}

/// Analyze pipeline results to produce a recognition report.
pub fn recognition_report(result: &crate::pipeline::ProgramPipelineResult) -> RecognitionReport {
    use crate::flatten::FlatOp;
    use crate::model::OpKind;

    let mut report = RecognitionReport {
        total_opcodes: result.opcode_dispatch.len(),
        flattened: 0,
        total_flat_ops: 0,
        unknown_ops: 0,
        unresolved_calls: 0,
        per_opcode: Vec::new(),
    };

    for arm in &result.opcode_dispatch {
        let selector = arm.selector.canonical_key();
        let Some(ssa) = &arm.flattened else {
            report.per_opcode.push(OpcodeRecognition {
                selector,
                flat_ops: 0,
                unknowns: 0,
                unresolved: 0,
            });
            continue;
        };

        report.flattened += 1;
        let mut unknowns = 0;
        let mut unresolved = 0;
        let mut flat_ops = 0;

        for insn in &ssa.insns {
            if let FlatOp::Op(op) = insn {
                flat_ops += 1;
                match &op.kind {
                    OpKind::Abort { .. } => unknowns += 1,
                    OpKind::Call { target, .. } => {
                        if matches!(target, crate::model::CallTarget::UnsupportedExpr) {
                            unresolved += 1;
                        }
                    }
                    _ => {}
                }
            }
        }

        report.total_flat_ops += flat_ops;
        report.unknown_ops += unknowns;
        report.unresolved_calls += unresolved;
        report.per_opcode.push(OpcodeRecognition {
            selector,
            flat_ops,
            unknowns,
            unresolved,
        });
    }

    report
}

fn generate_canonical_dispatch_table(
    out: &mut String,
    result: &crate::pipeline::ProgramPipelineResult,
) {
    out.push_str("/// Canonical analysis summary: opcode → flattened op count.\n");
    out.push_str("pub const CANONICAL_TRACE_PATTERNS: &[(&str, &str)] = &[\n");
    for arm in &result.opcode_dispatch {
        let status = match &arm.flattened {
            Some(f) => format!("Flattened({}ops)", f.insns.len()),
            None => "Unflattened".to_string(),
        };
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            arm.selector.canonical_key().replace('"', "\\\""),
            status.replace('"', "\\\""),
        ));
    }
    out.push_str("];\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_from_graph_produces_function_table() {
        // generate_from_graph reads only `name` / `original_blocks` /
        // `flattened.insns.len()` per function and the four `total_*`
        // counters. Hand-rolling a ProgramPipelineResult covers the same
        // surface without routing through the canonical pipeline.
        let mut pipeline = crate::pipeline::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: Vec::new(),
            jitcodes: Vec::new(),
            jitcodes_by_path: indexmap::IndexMap::new(),
            insns: indexmap::IndexMap::new(),
            descrs: Vec::new(),
            total_blocks: 2,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        for name in ["add", "sub"] {
            pipeline.functions.push(crate::pipeline::PipelineResult {
                name: name.into(),
                original_blocks: 1,
                annotations_count: 0,
                vable_rewrites: 0,
                transform_notes: Vec::new(),
                flattened: crate::flatten::SSARepr {
                    name: name.into(),
                    insns: Vec::new(),
                    num_blocks: 0,
                    insns_pos: None,
                },
            });
        }
        let code = generate_from_graph(&pipeline);

        assert!(
            code.contains("GRAPH_FUNCTIONS"),
            "should contain GRAPH_FUNCTIONS table"
        );
        assert!(code.contains("add"), "should list 'add' function");
        assert!(code.contains("sub"), "should list 'sub' function");
        assert!(
            code.contains("graph pipeline"),
            "should have graph pipeline header"
        );
    }

    #[test]
    fn generate_from_pipeline_emits_canonical_header() {
        let mut pipeline = crate::pipeline::ProgramPipelineResult {
            functions: Vec::new(),
            opcode_dispatch: vec![crate::opcode_dispatch::PipelineOpcodeArm {
                arm_id: 0,
                selector: crate::OpcodeDispatchSelector::Path(crate::CallPath::from_segments([
                    "Instruction",
                    "Add",
                ])),
                entry_jitcode_index: None,
                flattened: None,
            }],
            jitcodes: Vec::new(),
            jitcodes_by_path: indexmap::IndexMap::new(),
            insns: indexmap::IndexMap::new(),
            descrs: Vec::new(),
            total_blocks: 0,
            total_ops: 0,
            total_vable_rewrites: 0,
        };
        pipeline.functions.push(crate::pipeline::PipelineResult {
            name: "add".into(),
            original_blocks: 1,
            annotations_count: 0,
            vable_rewrites: 0,
            transform_notes: Vec::new(),
            flattened: crate::flatten::SSARepr {
                name: "add".into(),
                insns: Vec::new(),
                num_blocks: 0,
                insns_pos: None,
            },
        });
        let code = generate_from_pipeline(&pipeline);
        assert!(code.contains("canonical pipeline"));
        assert!(code.contains("CANONICAL_TRACE_PATTERNS"));
    }
}
